import { Prisma } from "@prisma/client";
import { z } from "zod";
import { requireAdminApi } from "@/lib/admin";
import { prisma } from "@/lib/prisma";

const idSchema = z.string().min(1).max(100);
const updateSchema = z.object({ action: z.enum(["approve", "publish"]), question: z.string().trim().min(10).max(500).optional(), explanation: z.string().trim().min(10).max(5000).optional(), sampleAnswer: z.string().trim().min(10).max(5000).optional() });
const jsonInput = (value: Prisma.JsonValue) => (value === null ? {} : value as Prisma.InputJsonValue);
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { const guard = await requireAdminApi(); if (guard.response) return guard.response; const id = idSchema.safeParse((await context.params).id); const body = updateSchema.safeParse(await request.json()); if (!id.success || !body.success) return Response.json({ error: "Invalid draft update." }, { status: 400 }); const draft = await prisma.aiQuestionDraft.findUnique({ where: { id: id.data } }); if (!draft) return Response.json({ error: "Draft not found." }, { status: 404 }); const updated = await prisma.aiQuestionDraft.update({ where: { id: id.data }, data: { isApproved: true, question: body.data.question ?? draft.question, explanation: body.data.explanation ?? draft.explanation, sampleAnswer: body.data.sampleAnswer ?? draft.sampleAnswer, isPublished: body.data.action === "publish" } }); if (body.data.action === "publish") await prisma.interviewQuestion.upsert({ where: { slug: draft.slug }, update: { question: updated.question, explanation: updated.explanation, sampleAnswer: updated.sampleAnswer, isPublished: true }, create: { question: updated.question, slug: updated.slug, categoryId: updated.categoryId, subcategoryId: updated.subcategoryId, experienceLevel: updated.experienceLevel, difficulty: updated.difficulty, interviewType: updated.interviewType, shortDescription: updated.shortDescription, explanation: updated.explanation, sampleAnswer: updated.sampleAnswer, keyPoints: jsonInput(updated.keyPoints), commonMistakes: jsonInput(updated.commonMistakes), followUpQuestions: jsonInput(updated.followUpQuestions), tags: jsonInput(updated.tags), seoTitle: updated.seoTitle, seoDescription: updated.seoDescription, isPublished: true } }); return Response.json({ draft: updated }); }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string }> }) { const guard = await requireAdminApi(); if (guard.response) return guard.response; const id = idSchema.safeParse((await context.params).id); if (!id.success) return Response.json({ error: "Invalid draft ID." }, { status: 400 }); try { await prisma.aiQuestionDraft.delete({ where: { id: id.data } }); return Response.json({ deleted: true }); } catch { return Response.json({ error: "Draft not found." }, { status: 404 }); } }
