import { PrismaClient, Difficulty, ExperienceLevel, InterviewType } from "@prisma/client";
import { articleSeeds } from "./article-seed";
const prisma = new PrismaClient();
const categories = [
  ["Software Developer", "Technology"], ["Android Developer", "Technology"], ["Java Developer", "Technology"], ["Kotlin Developer", "Technology"], ["Python Developer", "Technology"], ["JavaScript Developer", "Technology"], ["React Developer", "Technology"], ["Web Developer", "Technology"], ["SQL", "Technology"], ["QA Tester", "Technology"], ["Data Analyst", "Technology"], ["Sales", "Business"], ["Marketing", "Business"], ["Human Resources", "Business"], ["Customer Support", "Business"], ["Accountant", "Finance"], ["Banking", "Finance"], ["Finance", "Finance"], ["Fresher", "General"], ["Internship", "General"], ["HR", "General"], ["Behavioral", "General"], ["Situational", "General"],
] as const;
const topics = [
  ["Software Developer", "How would you design a reliable service that processes customer requests?", "architecture", "Describe the trade-offs behind your design and how you would keep it observable.", "A strong response starts with requirements, separates responsibilities, and explains reliability choices in plain language."],
  ["Android Developer", "How would you make an Android screen load quickly on a slow connection?", "performance", "Explain the measurements and improvements you would make before release.", "Mention profiling, lifecycle-aware loading, caching, pagination, and graceful states rather than promising instant results."],
  ["Java Developer", "What makes a Java application maintainable as its team grows?", "maintainability", "Connect design choices to testing and team communication.", "Discuss clear boundaries, focused classes, useful tests, consistent conventions, and deliberate dependency management."],
  ["Kotlin Developer", "When would you use a sealed class in Kotlin?", "language", "Give a practical example and acknowledge alternatives.", "Explain closed type hierarchies, exhaustive when expressions, and why the model communicates intent."],
  ["Python Developer", "How do you investigate a Python function that has become slow?", "debugging", "Walk through a measured investigation rather than guessing.", "Use profiling, representative data, algorithmic complexity, I/O checks, and a regression benchmark."],
  ["JavaScript Developer", "How do you prevent an asynchronous JavaScript feature from showing stale data?", "async", "Explain the race condition and the control you would introduce.", "Mention request identity, cancellation where possible, state ownership, and tests for out-of-order responses."],
  ["React Developer", "How do you decide where state should live in a React application?", "state", "Compare local, shared, and server state with a concrete example.", "Keep state close to its owner, derive values when possible, and avoid duplicating server state in unrelated components."],
  ["Web Developer", "What makes a web form accessible and resilient?", "accessibility", "Describe how you build and test it.", "Cover labels, keyboard flow, errors, focus management, semantic controls, and validation on both client and server."],
  ["SQL", "How would you find and fix a slow SQL query?", "databases", "Explain the evidence you would gather before changing the query.", "Use an execution plan, indexes aligned with filters, query shape, cardinality, and measurement after the change."],
  ["QA Tester", "How do you choose a useful regression test suite?", "quality", "Balance risk, coverage, maintenance, and feedback speed.", "Prioritize critical user journeys, escaped defects, integration boundaries, and stable tests with clear ownership."],
  ["Data Analyst", "How do you explain an unexpected change in a business metric?", "analysis", "Show how you separate data quality issues from real behavior.", "Check definitions, pipelines, segments, comparison windows, and external context before drawing conclusions."],
  ["Sales", "How would you prepare for a discovery call with a new prospect?", "discovery", "Show how preparation helps you listen instead of forcing a pitch.", "Research the business, form hypotheses, prepare open questions, and define a useful next step."],
  ["Marketing", "How do you decide whether a marketing campaign worked?", "measurement", "Describe a measurement plan before looking at results.", "Connect a clear objective to a baseline, relevant leading and lagging measures, attribution limits, and follow-up action."],
  ["Human Resources", "How would you improve an inconsistent hiring process?", "process", "Discuss fairness, speed, candidate experience, and evidence.", "Map the process, define criteria, train interviewers, standardize decisions, and review outcomes for unintended bias."],
  ["Customer Support", "How do you respond when you cannot solve a customer issue immediately?", "service", "Demonstrate ownership without making promises you cannot keep.", "Acknowledge impact, clarify the next action, set an honest update time, document context, and close the loop."],
  ["Accountant", "How do you protect accuracy during a busy close?", "accuracy", "Explain controls that help you work quickly without cutting corners.", "Use reconciliations, review thresholds, checklists, audit trails, and early escalation of unusual items."],
  ["Banking", "How do you evaluate risk in a customer-facing banking decision?", "risk", "Balance policy, evidence, customer needs, and escalation.", "Verify information, apply the relevant policy consistently, document reasoning, and escalate material uncertainty."],
  ["Finance", "How would you explain a forecast variance to a non-finance partner?", "communication", "Turn the variance into a useful decision conversation.", "Start with the headline, separate volume, price, mix, and timing, then state the implication and action."],
  ["Fresher", "Tell me about a project where you had to learn something quickly.", "learning", "Use a specific story from study, work, or personal projects.", "Explain the goal, your learning plan, the obstacle, the result, and what you would repeat next time."],
  ["Internship", "How would you contribute during your first month on a new team?", "onboarding", "Show curiosity paired with useful action.", "Learn the goals and norms, ship a small improvement, ask precise questions, and make progress visible."],
  ["HR", "How do you prepare for the question 'Why do you want this role?'", "motivation", "Connect your interests to the actual role rather than generic enthusiasm.", "Link the company or team context, the work itself, your evidence of fit, and what you hope to contribute."],
  ["Behavioral", "Tell me about a time you received difficult feedback.", "feedback", "Show reflection without blaming the person who gave it.", "Set the context, describe the feedback, explain your response, and show the changed behavior or outcome."],
  ["Situational", "What would you do if two urgent stakeholders needed your time at once?", "prioritization", "Explain how you would make the trade-off visible.", "Clarify impact and deadlines, compare urgency, communicate options, agree on priority, and follow through."],
  ["Software Developer", "How would you review a pull request that works but is difficult to maintain?", "code review", "Balance correctness, risk, and respect for the author.", "Separate blocking issues from suggestions, explain the future cost, ask questions, and propose a focused improvement."],
  ["Android Developer", "How would you handle state restoration after an Android process is killed?", "lifecycle", "Distinguish transient UI state from durable application data.", "Use lifecycle-aware state holders, saved state for small UI values, and durable storage for business data."],
  ["Java Developer", "What would you look for when diagnosing a memory leak in Java?", "diagnostics", "Describe tools and a narrowing strategy.", "Capture evidence, inspect heap paths, identify unintended references, fix ownership, and add a regression check."],
  ["Kotlin Developer", "How do coroutines change the way you structure asynchronous work?", "concurrency", "Explain structured concurrency in practical terms.", "Tie coroutine scope to lifecycle, make cancellation explicit, handle failures, and keep blocking work off the main thread."],
  ["Python Developer", "How would you make a Python data-processing script safe to rerun?", "reliability", "Discuss partial failures and duplicate work.", "Use idempotent writes, checkpoints, deterministic inputs, validation, and clear reporting of completed work."],
  ["JavaScript Developer", "How do you decide whether a browser task belongs in a web worker?", "browser", "Explain the cost of moving work away from the main thread.", "Choose workers for CPU-heavy isolated work, define message boundaries, and measure responsiveness before and after."],
  ["React Developer", "How would you test a React component that depends on loading and error states?", "testing", "Focus on user-observable behavior.", "Test accessible loading, success, error, retry, and interaction states without coupling tests to implementation details."],
] as const;
const angles = ["for a small team", "when requirements are unclear", "under a tight deadline", "with a focus on accessibility", "with limited operational budget", "when a previous solution failed", "for a high-risk release", "when explaining your decision to a non-specialist", "while mentoring a junior teammate", "after measuring an unexpected result"];
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
async function main() {
  const categoryMap = new Map<string, string>();
  for (const [name, group] of categories) { const category = await prisma.category.upsert({ where: { slug: slugify(name) }, update: {}, create: { name, slug: slugify(name), group, description: `Focused ${name} interview preparation.` } }); categoryMap.set(name, category.id); await prisma.subcategory.upsert({ where: { categoryId_slug: { categoryId: category.id, slug: slugify(name) } }, update: {}, create: { name, slug: slugify(name), categoryId: category.id } }); }
  for (let topicIndex = 0; topicIndex < topics.length; topicIndex++) { const [categoryName, baseQuestion, tag, explanation, sampleAnswer] = topics[topicIndex]; const categoryId = categoryMap.get(categoryName)!; const subcategory = await prisma.subcategory.findFirst({ where: { categoryId } }); for (let angleIndex = 0; angleIndex < angles.length; angleIndex++) { const question = `${baseQuestion} ${angles[angleIndex]}?`; const slug = `${slugify(baseQuestion)}-${slugify(angles[angleIndex])}`; const difficulty = [Difficulty.EASY, Difficulty.MEDIUM, Difficulty.HARD][(topicIndex + angleIndex) % 3]; const experienceLevel = [ExperienceLevel.FRESHER, ExperienceLevel.INTERNSHIP, ExperienceLevel.MID_LEVEL, ExperienceLevel.EXPERIENCED][(topicIndex + angleIndex) % 4]; const interviewType = categoryName === "Behavioral" || categoryName === "HR" ? InterviewType.BEHAVIORAL : categoryName === "Situational" ? InterviewType.SITUATIONAL : InterviewType.TECHNICAL; await prisma.interviewQuestion.upsert({ where: { slug }, update: {}, create: { question, slug, categoryId, subcategoryId: subcategory?.id, experienceLevel, difficulty, interviewType, shortDescription: `A practical ${tag} question focused on ${angles[angleIndex]}.`, explanation, sampleAnswer, keyPoints: ["State your assumptions", "Use a specific example", "Explain the trade-off", "Close with the result or next step"], commonMistakes: ["Starting without clarifying the goal", "Listing tools without explaining judgment", "Making claims without evidence"], followUpQuestions: [`What would you measure after making that decision?`, `What would you change with more time?`], tags: [tag, slugify(categoryName)], isPublished: true, seoTitle: question, seoDescription: `Learn how to approach this ${tag} interview question with a clear, practical answer.` } }); } }
  for (const article of articleSeeds) {
    const category = article.slug.includes("technical") ? categoryMap.get("Software Developer") : categoryMap.get("General");
    await prisma.article.upsert({ where: { slug: article.slug }, update: { ...article, categoryId: category, isPublished: true, publishedAt: new Date() }, create: { ...article, categoryId: category, isPublished: true, publishedAt: new Date() } });
  }
  if (process.env.ADMIN_EMAIL) await prisma.user.updateMany({ where: { email: process.env.ADMIN_EMAIL.toLowerCase().trim() }, data: { role: "ADMIN" } });
  console.log(`Seeded ${topics.length * angles.length} interview questions and ${articleSeeds.length} articles.`);
}
main().catch(error => { console.error(error); process.exit(1); }).finally(() => prisma.$disconnect());
