import type { Metadata } from "next";
import type { Difficulty, ExperienceLevel, InterviewType } from "@prisma/client";
import Link from "next/link";
import { SearchFilters } from "@/components/search/search-filters";
import { QuestionCard } from "@/components/questions/question-card";
import { Container } from "@/components/ui/container";
import { searchContent } from "@/services/questions";

export const dynamic = "force-dynamic";
// Search results are query-driven and would otherwise generate a large
// number of thin, near-duplicate indexable URLs (one per query string).
// The search feature itself stays fully usable; it's just excluded from
// Google's index in favor of the canonical /interview-questions and
// /interview-questions/[category] pages, which cover the same content.
export const metadata: Metadata = { title: "Search", description: "Search InterviewPrep's free interview questions, categories, and resources.", robots: { index: false, follow: true } };
type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> };
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
export default async function SearchPage({ searchParams }: Props) {
  const params = await searchParams; const query = one(params.q) ?? ""; const category = one(params.category); const experience = one(params.experience) as ExperienceLevel | undefined; const difficulty = one(params.difficulty) as Difficulty | undefined; const interviewType = one(params.type) as InterviewType | undefined; const sort = one(params.sort) as "relevance" | "newest" | undefined; const rawPage = Number(one(params.page) ?? 1); const page = Number.isFinite(rawPage) ? rawPage : 1;
  const results = await searchContent({ query, category, experience, difficulty, interviewType, sort, page });
  const pageUrl = (nextPage: number) => { const next = new URLSearchParams(); if (query) next.set("q", query); if (category) next.set("category", category); if (experience) next.set("experience", experience); if (difficulty) next.set("difficulty", difficulty); if (interviewType) next.set("type", interviewType); if (sort) next.set("sort", sort); next.set("page", String(nextPage)); return `/search?${next}`; };
  return <section className="py-16 sm:py-20"><Container><p className="text-xs font-bold uppercase tracking-[.18em] text-coral">Find your next prompt</p><h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Search InterviewPrep</h1><p className="mt-4 max-w-2xl leading-7 text-ink/60">Search questions, categories, and practical resources in one place.</p><div className="mt-8"><SearchFilters query={query} category={category} experience={experience} difficulty={difficulty} interviewType={interviewType} sort={sort} /></div>{query ? <p className="mt-8 text-sm font-bold text-ink/55">{results.total} result{results.total === 1 ? "" : "s"} for “{query}”</p> : <p className="mt-8 text-sm font-bold text-ink/55">Browse {results.questionTotal} interview questions and {results.articleTotal} resources</p>}{results.categories.length > 0 && <section className="mt-8"><h2 className="font-display text-2xl font-bold">Categories</h2><div className="mt-4 flex flex-wrap gap-3">{results.categories.map(item => <Link className="rounded-full border border-ink/15 bg-white/70 px-4 py-2 text-sm font-bold hover:border-coral hover:text-coral" href={`/interview-questions/${item.slug}`} key={item.id}>{item.name}</Link>)}</div></section>}{results.questions.length > 0 && <section className="mt-12"><h2 className="font-display text-2xl font-bold">Interview questions</h2><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{results.questions.map(question => <QuestionCard key={question.id} question={question} />)}</div></section>}{results.articles.length > 0 && <section className="mt-12"><h2 className="font-display text-2xl font-bold">Resources</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{results.articles.map(article => <Link className="rounded-2xl border border-ink/10 bg-white/70 p-6 hover:border-coral" href={`/blog/${article.slug}`} key={article.id}><p className="text-xs font-bold uppercase tracking-widest text-coral">Guide</p><h3 className="mt-3 font-display text-xl font-bold">{article.title}</h3><p className="mt-2 text-sm leading-6 text-ink/60">{article.excerpt}</p></Link>)}</div></section>}{results.total === 0 && <div className="mt-8 rounded-2xl border border-dashed border-ink/20 p-12 text-center"><h2 className="font-display text-xl font-bold">No matches yet</h2><p className="mt-2 text-ink/60">Try a broader phrase or clear one of the filters.</p></div>}<div className="mt-10 flex justify-between">{results.page > 1 ? <Link href={pageUrl(results.page - 1)} className="rounded-full border border-ink/15 px-5 py-3 text-sm font-bold hover:border-coral">Previous</Link> : <span />}{results.page < results.pageCount && <Link href={pageUrl(results.page + 1)} className="rounded-full border border-ink/15 px-5 py-3 text-sm font-bold hover:border-coral">Next</Link>}</div></Container></section>;
}
