import { z } from "zod";
import { requireAdminApi } from "@/lib/admin";
import { prisma } from "@/lib/prisma";
import { questionGenerationService } from "@/services/ai/question-generation-service";
import { rateLimit, requestSizeLimit, tooManyRequests } from "@/lib/request-security";
export const runtime = "nodejs";
const schema = z.object({ categoryId: z.string().min(1), subcategoryId: z.string().optional(), experienceLevel: z.enum(["FRESHER", "INTERNSHIP", "MID_LEVEL", "EXPERIENCED"]), difficulty: z.enum(["EASY", "MEDIUM", "HARD"]), interviewType: z.enum(["TECHNICAL", "BEHAVIORAL", "HR", "CASE_STUDY", "SITUATIONAL"]), topic: z.string().trim().min(2).max(160), count: z.number().int().min(1).max(50), instructions: z.string().trim().max(1000).optional() });
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
export async function POST(request: Request) { const limiter = rateLimit(request, "admin-ai", 3, 15 * 60 * 1000); if (!limiter.allowed) return tooManyRequests(limiter.retryAfter); if (!requestSizeLimit(request)) return Response.json({ error: "Request is too large." }, { status: 413 }); const guard = await requireAdminApi(); if (guard.response) return guard.response; try { const input = schema.parse(await request.json()); const category = await prisma.category.findUnique({ where: { id: input.categoryId }, select: { name: true } }); if (!category) return Response.json({ error: "Category not found." }, { status: 400 }); const drafts = await questionGenerationService.generate({ ...input, category: category.name }); const existing = await prisma.interviewQuestion.findMany({ where: { question: { in: drafts.map(item => item.question) } }, select: { question: true } }); const duplicateQuestions = new Set(existing.map(item => item.question.toLowerCase())); const created = []; for (const draft of drafts) { if (duplicateQuestions.has(draft.question.toLowerCase())) continue; created.push(await prisma.aiQuestionDraft.create({ data: { ...draft, slug: slugify(draft.question), categoryId: input.categoryId, subcategoryId: input.subcategoryId, experienceLevel: input.experienceLevel, difficulty: input.difficulty, interviewType: input.interviewType } })); } return Response.json({ drafts: created, skippedDuplicates: drafts.length - created.length }); } catch (error) { if (error instanceof z.ZodError) return Response.json({ error: "Invalid generation request." }, { status: 400 }); return Response.json({ error: error instanceof Error ? error.message : "AI generation failed safely." }, { status: 503 }); } }
