import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Container } from "@/components/ui/container";
import { getCachedPublicCategories } from "@/lib/public-content";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Interview categories", description: "Browse free interview questions by career category and role." };
export default async function CategoriesPage() { const categories = await getCachedPublicCategories(); const groups = [...new Set(categories.map(category => category.group))]; return <section className="py-16 sm:py-20"><Container><nav aria-label="Breadcrumb" className="text-sm text-ink/55"><Link href="/">Home</Link><span className="px-2">/</span><span className="font-semibold text-ink">Categories</span></nav><p className="mt-12 text-xs font-bold uppercase tracking-[.18em] text-coral">Find your focus</p><h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Interview categories</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-ink/60">Choose a role or topic to find practical questions and answer guidance for your next interview.</p><div className="mt-12 grid gap-12">{groups.map(group => <section key={group}><h2 className="font-display text-2xl font-bold">{group}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{categories.filter(category => category.group === group).map(category => <Link href={`/interview-questions/${category.slug}`} className="group rounded-2xl border border-ink/10 bg-white/70 p-5 hover:-translate-y-1 hover:border-coral" key={category.id}><div className="flex items-center justify-between"><h3 className="font-display text-lg font-bold">{category.name}</h3><ArrowRight size={18} className="text-ink/35 group-hover:text-coral" /></div><p className="mt-3 text-sm text-ink/55">{category._count.questions} interview questions</p></Link>)}</div></section>)}</div></Container></section>; }
