import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/ui/container";
import { listArticles } from "@/services/articles";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Interview resources", description: "Practical, original guides for preparing for interviews with more clarity." };
type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> };
const one = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value;
export default async function BlogPage({ searchParams }: Props) { const params = await searchParams; const category = one(params.category); const rawPage = Number(one(params.page) ?? 1); const result = await listArticles(Number.isFinite(rawPage) ? rawPage : 1, category); const pageUrl = (page: number) => `/blog?${new URLSearchParams({ ...(category ? { category } : {}), page: String(page) })}`; return <section className="py-16 sm:py-20"><Container><nav aria-label="Breadcrumb" className="text-sm text-ink/55"><Link href="/">Home</Link><span className="px-2">/</span><span className="font-semibold text-ink">Resources</span></nav><p className="mt-12 text-xs font-bold uppercase tracking-[.18em] text-coral">Resource center</p><h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Practical guidance for the next conversation</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-ink/60">Original notes on preparation, communication, and the decisions that make interviews clearer.</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/blog" className={`rounded-full border px-4 py-2 text-sm font-bold ${!category ? "border-coral text-coral" : "border-ink/15"}`}>All resources</Link>{["General", "Technology"].map(item => <Link href={`/blog?category=${item.toLowerCase()}`} className="rounded-full border border-ink/15 px-4 py-2 text-sm font-bold hover:border-coral hover:text-coral" key={item}>{item}</Link>)}</div>{result.articles.length ? <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{result.articles.map(article => <article className="rounded-2xl border border-ink/10 bg-white/70 p-6" key={article.id}><p className="text-xs font-bold uppercase tracking-widest text-coral">{article.category?.name ?? "Interview guide"}</p><h2 className="mt-4 font-display text-2xl font-bold leading-tight"><Link href={`/blog/${article.slug}`} className="hover:text-coral">{article.title}</Link></h2><p className="mt-3 text-sm leading-7 text-ink/60">{article.excerpt}</p><Link href={`/blog/${article.slug}`} className="mt-6 inline-block text-sm font-bold text-coral">Read guide</Link></article>)}</div> : <div className="mt-10 rounded-2xl border border-dashed border-ink/20 p-12 text-center text-ink/60">No resources match this category yet.</div>}<div className="mt-10 flex justify-between">{result.page > 1 ? <Link href={pageUrl(result.page - 1)} className="rounded-full border border-ink/15 px-5 py-3 text-sm font-bold">Previous</Link> : <span />}{result.page < result.pageCount && <Link href={pageUrl(result.page + 1)} className="rounded-full border border-ink/15 px-5 py-3 text-sm font-bold">Next</Link>}</div></Container></section>; }
