import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
import { ContentOwner } from "@/components/editorial/content-owner";

export const metadata: Metadata = { title: "About", description: "Learn what InstantInterviewPrep offers, who it is for, and how its interview-preparation content is organized.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <LegalPage title="About InstantInterviewPrep" lastUpdated="September 13, 2026" intro="InstantInterviewPrep is a free interview-preparation resource for people who want focused practice before a job conversation. This page explains who maintains it, what it covers, and what readers can expect from its content.">
    <ContentOwner />
    <h2>Who operates the site</h2><p>InstantInterviewPrep is owned and maintained by <a href="/author/suresh-mali">Suresh Mali</a>. Suresh oversees the website, its public interview-preparation content, and the systems used for questions, learning material, practice, and feedback. The author page describes this role without adding credentials or a professional biography that has not been provided.</p>
    <h2>Why InstantInterviewPrep exists</h2><p>Interview preparation can become a long list of disconnected topics. The site organizes that work into searchable questions, answer guidance, practice sessions, learning topics, daily challenges, mock interviews, and a resume builder. The aim is to help a candidate understand a prompt, practice explaining an answer, and then adapt that answer to their own experience rather than memorize a script.</p>
    <h2>Who it is for</h2><p>The material is intended for students, freshers, career changers, and experienced candidates preparing for a job conversation. It covers technical, behavioral, HR, situational, and role-specific preparation across the categories published in the question library.</p>
    <h2>How we create interview content</h2><p>Questions and learning materials enter the site through seed data, administrator imports, and the site&apos;s learning-content workflows. A question can be organized by category, subcategory, experience level, difficulty, and interview type, then structured with an explanation, key points, a sample spoken answer, common mistakes, follow-up prompts, and related learning material when those sections are useful. The depth varies by subject; sections are not added just to make a page longer.</p>
    <h2>How technical information is checked</h2><p>Automated checks help validate required fields, publication state, formatting, duplicate slugs, and potentially similar questions. These checks improve consistency but cannot establish that a technical answer is correct. When version-specific or safety-sensitive details matter, maintainers use relevant official documentation as a reference. Readers should verify important implementation details against the documentation and version they use.</p>
    <h2>Corrections and updates</h2><p>Readers can report incorrect information, broken code or links, outdated guidance, missing context, or typographical errors through <a href="/contact">Contact</a>. Reports are assessed individually and may lead to an edit, an update, or no change when the report cannot be verified. Material edits update the stored modification date. A current modification date means the record changed; it is not a claim that every page received a complete manual review on that date.</p>
    <h2>Editorial boundaries</h2><p>Optional AI assistance is restricted to the administrator area and produces unpublished drafts only when explicitly enabled and configured. Those drafts must be reviewed, edited, approved, and published by an administrator; they are not automatically published or treated as authoritative. InstantInterviewPrep does not claim an expert-review panel, human review of every page, professional certifications, or error-free content. The full workflow and correction process are described in the <a href="/editorial-policy">editorial policy</a>.</p>
  </LegalPage>;
}
