// ---- 200 Java Developer Questions (Fresher to Advanced) ----
import { Difficulty, ExperienceLevel, InterviewType, PrismaClient } from "@prisma/client";

// ---- 200 Docker Interview Questions (Fresher to Advanced) ----
// ---- Categories ----
export const categories = [
  ["JAVA", "JAVA"]
] as const;

// ---- 200 Git & GitHub Interview Questions (Fresher to Advanced) ----
export const topics = [
  // ==================== CORE JAVA BASICS (Easy) ====================
  ["Java Developer", "What are the main principles of Object-Oriented Programming (OOP)?", "oop-principles", "The interviewer expects a clear definition of the four pillars.", "The four main principles are Encapsulation (bundling data and methods), Inheritance (creating new classes based on existing ones), Polymorphism (ability to take many forms, i.e., method overloading/overriding), and Abstraction (hiding implementation details)."],
  ["Java Developer", "What is the difference between an abstract class and an interface?", "abstract-class-vs-interface", "Compare their features, especially post-Java 8.", "An abstract class can have instance variables and constructors, and can define state. An interface, before Java 8, only had public abstract methods. From Java 8 onward, interfaces can have default and static methods. A class can implement multiple interfaces but can only extend one class."],
  ["Java Developer", "Explain the difference between `String`, `StringBuilder`, and `StringBuffer`.", "string-vs-stringbuilder-vs-stringbuffer", "Focus on mutability, thread-safety, and performance.", "`String` is immutable, meaning any operation creates a new object, making it inefficient for heavy string manipulation. `StringBuffer` is mutable and thread-safe (synchronized methods), while `StringBuilder` is mutable and not thread-safe, making it the fastest for single-threaded operations."],
  ["Java Developer", "What is the difference between `==` and `.equals()` in Java?", "equals-vs-operator", "Clarify reference comparison vs content comparison.", "`==` compares memory addresses (references) for objects, checking if they point to the same instance. `.equals()` is a method intended to compare the content or logical equality of two objects, and it can be overridden by classes like `String`."],
  ["Java Developer", "What is method overloading and method overriding?", "overloading-vs-overriding", "Distinguish between compile-time and runtime polymorphism.", "Method overloading (compile-time) occurs when multiple methods in the same class share the same name but have different parameters. Method overriding (runtime) occurs when a subclass provides a specific implementation for a method already defined in its parent class."],
  ["Java Developer", "What is the `static` keyword in Java?", "static-keyword", "Explain its usage for variables, methods, and blocks.", "`static` indicates that a member belongs to the class itself rather than to any specific instance. Static variables are shared across all instances. Static methods can be called without creating an object, but they cannot access instance variables directly."],
  ["Java Developer", "Explain the `final` keyword in Java.", "final-keyword", "Cover variables, methods, and classes.", "`final` on a variable makes it a constant (cannot be reassigned). `final` on a method prevents it from being overridden. `final` on a class prevents it from being subclassed."],
  ["Java Developer", "What is the `super` keyword used for?", "super-keyword", "Explain its role in constructors and accessing parent members.", "`super` is used to call the parent class's constructor (`super()`), and to access parent class methods or variables that might have been overridden or hidden in the child class."],
  ["Java Developer", "What is a constructor in Java?", "constructor", "Explain its purpose and types.", "A constructor is a special method invoked when an object is instantiated. It is used to initialize the object's state. If not defined, Java provides a default no-argument constructor. Constructors can be overloaded."],
  ["Java Developer", "Can a constructor be `private`? What is the use of a private constructor?", "private-constructor", "Explain the Singleton pattern and utility classes.", "Yes, a constructor can be private. It is used to prevent external instantiation of a class, commonly employed in the Singleton design pattern and for utility classes that only contain static methods."],
  ["Java Developer", "What is the Java classloader? How does it work?", "classloader", "Explain the delegation model.", "The Java Classloader is part of the JVM that dynamically loads Java classes. It follows the delegation hierarchy: the Bootstrap ClassLoader loads core JDK classes, the Extension ClassLoader loads `jre/lib/ext`, and the Application ClassLoader loads the classpath. It delegates requests to the parent loader first."],
  ["Java Developer", "What is a package in Java and why is it used?", "package", "Explain namespace management and access control.", "A package is a namespace that organizes a set of related classes and interfaces. It helps avoid naming conflicts and provides access protection (default and protected access specifiers are package-level)."],
  ["Java Developer", "What are primitive data types in Java? List them.", "primitive-types", "Test basic syntax knowledge.", "Java has 8 primitive types: `byte`, `short`, `int`, `long`, `float`, `double`, `char`, and `boolean`."],
  ["Java Developer", "What is type casting in Java? Explain upcasting and downcasting.", "type-casting", "Differentiate implicit vs explicit casting.", "Type casting is converting one data type to another. Upcasting (implicit) is casting a subclass object to a superclass type. Downcasting (explicit) is casting a superclass reference to a subclass type, which can throw `ClassCastException` if not checked."],
  ["Java Developer", "What is an array in Java and how is it different from an `ArrayList`?", "array-vs-arraylist", "Compare fixed vs dynamic size, and primitives vs objects.", "An array is a fixed-length data structure that can hold primitives or objects. `ArrayList` is a dynamic array (resizable) from the Collections Framework that can only hold objects and provides many utility methods."],

  // ==================== OOP & DESIGN PRINCIPLES (Easy-Medium) ====================
  ["Java Developer", "Explain the Single Responsibility Principle (SRP).", "srp", "Part of SOLID principles.", "SRP states that a class should have only one reason to change, meaning it should have only one job or responsibility. This improves maintainability and testability."],
  ["Java Developer", "Explain the Open/Closed Principle.", "open-closed-principle", "Part of SOLID.", "OCP states that software entities (classes, modules, functions) should be open for extension but closed for modification. You should be able to add new behavior without altering existing code, typically achieved via inheritance or interfaces."],
  ["Java Developer", "Explain the Liskov Substitution Principle (LSP).", "liskov-substitution", "Key SOLID principle for inheritance.", "LSP states that objects of a superclass should be replaceable with objects of a subclass without affecting the correctness of the program. Subclasses should extend, not restrict, the base class functionality."],
  ["Java Developer", "Explain the Interface Segregation Principle (ISP).", "interface-segregation", "Part of SOLID.", "ISP states that clients should not be forced to depend on interfaces they do not use. It means larger interfaces should be split into smaller, more specific ones."],
  ["Java Developer", "Explain the Dependency Inversion Principle (DIP).", "dependency-inversion", "Part of SOLID.", "DIP states that high-level modules should not depend on low-level modules; both should depend on abstractions (interfaces). Abstractions should not depend on details; details should depend on abstractions."],
  ["Java Developer", "What is the difference between composition and inheritance?", "composition-vs-inheritance", "Explain the 'Has-A' vs 'Is-A' relationship.", "Inheritance represents an 'Is-A' relationship (e.g., Dog is an Animal). Composition represents a 'Has-A' relationship (e.g., Car has an Engine). Composition offers more flexibility and is favored over inheritance to avoid tight coupling and the diamond problem."],
  ["Java Developer", "What is the `transient` keyword in Java?", "transient-keyword", "Explain its use in serialization.", "The `transient` keyword is applied to instance variables to indicate that they should not be serialized. When an object is serialized, transient fields are skipped, making them useful for sensitive data or derived fields."],
  ["Java Developer", "What is the `volatile` keyword?", "volatile-keyword", "Explain its role in multi-threading.", "The `volatile` keyword ensures that a variable's value is always read from main memory, not from thread-local caches. It guarantees visibility of changes across threads but does not guarantee atomicity."],
  ["Java Developer", "What is a marker interface? Give an example.", "marker-interface", "Explain its purpose.", "A marker interface is an empty interface (no methods) used to signal or mark a class for special handling by the JVM or framework. Examples include `Serializable`, `Cloneable`, and `Remote`."],
  ["Java Developer", "What is polymorphism? Provide a real-world example.", "polymorphism", "Demonstrate runtime and compile-time polymorphism.", "Polymorphism allows one interface to be used for a general class of actions. A real-world example is a `Shape` class with a `draw()` method; subclasses like `Circle` and `Square` implement `draw()` differently. At runtime, the correct `draw()` is called based on the actual object type."],

  // ==================== EXCEPTION HANDLING (Easy-Medium) ====================
  ["Java Developer", "What is the difference between checked and unchecked exceptions?", "checked-vs-unchecked", "Define the two types of exceptions.", "Checked exceptions (e.g., `IOException`, `SQLException`) are checked at compile-time. The compiler forces you to handle them (using try-catch or `throws`). Unchecked exceptions (e.g., `NullPointerException`, `ArithmeticException`) are subclasses of `RuntimeException` and are not checked at compile-time."],
  ["Java Developer", "What is the `finally` block and is it always executed?", "finally-block", "Clarify the purpose of `finally`.", "The `finally` block is used to execute important code such as closing resources. It is always executed when the try-catch block exits, except in cases where the JVM exits abruptly (e.g., `System.exit()`) or a fatal error occurs."],
  ["Java Developer", "What is the difference between `throw` and `throws`?", "throw-vs-throws", "Compare the keywords.", "`throw` is used inside a method to explicitly throw an exception. `throws` is used in the method signature to declare that the method might throw one or more checked exceptions, delegating handling to the caller."],
  ["Java Developer", "What is a custom exception and why would you create one?", "custom-exception", "Explain user-defined exceptions.", "A custom exception is a user-defined class extending `Exception` (checked) or `RuntimeException` (unchecked). You create them to provide more meaningful error messages and to encapsulate specific business logic failures."],
  ["Java Developer", "How does exception handling work in method overriding?", "exception-overriding", "Rules for overriding methods that throw exceptions.", "When overriding a method, the overriding method can throw only the same checked exceptions, subclasses of those checked exceptions, or no exceptions. It cannot throw broader checked exceptions."],
  ["Java Developer", "What is the try-with-resources statement?", "try-with-resources", "Explain auto-closable resources.", "Introduced in Java 7, try-with-resources automatically closes resources that implement `AutoCloseable` (e.g., `FileInputStream`, `Connection`) at the end of the try block, reducing boilerplate and improving code safety."],

  // ==================== COLLECTIONS FRAMEWORK (Medium) ====================
  ["Java Developer", "What is the Java Collections Framework? Name its core interfaces.", "collections-framework", "List the core interfaces.", "The Java Collections Framework provides architecture to store and manipulate a group of objects. Core interfaces include `Collection` (root interface), `List`, `Set`, `Queue`, `Deque`, and `Map`."],
  ["Java Developer", "What is the difference between `ArrayList` and `LinkedList`?", "arraylist-vs-linkedlist", "Compare time complexity and use cases.", "`ArrayList` uses a dynamic array, providing O(1) random access but O(n) insertion/deletion in the middle. `LinkedList` uses a doubly-linked list, providing O(1) insertion/deletion at ends and O(n) random access. `LinkedList` is better for frequent insertion/deletion; `ArrayList` is better for frequent access."],
  ["Java Developer", "How does `HashMap` work internally?", "hashmap-internal", "Explain hashing, buckets, and collision handling.", "`HashMap` stores key-value pairs. It uses an array of `Node` (buckets). The key's `hashCode()` determines the bucket index. In case of collisions (same bucket), entries are stored as a linked list (or tree if the list grows beyond a threshold) in the same bucket. When retrieving, the `equals()` method is used to find the exact key."],
  ["Java Developer", "What is the difference between `HashMap` and `HashTable`?", "hashmap-vs-hashtable", "Compare synchronization and null handling.", "`HashMap` is not synchronized (not thread-safe) and allows one `null` key and multiple `null` values. `HashTable` is synchronized (thread-safe) and does not allow `null` keys or values. `HashMap` is generally preferred in non-concurrent scenarios."],
  ["Java Developer", "What is the difference between `HashSet` and `TreeSet`?", "hashset-vs-treeset", "Compare order and performance.", "`HashSet` is backed by a `HashMap` and does not maintain any order of elements; it offers O(1) performance. `TreeSet` is backed by a `TreeMap` (Red-Black tree) and maintains elements in sorted ascending order (natural or custom order), offering O(log n) performance."],
  ["Java Developer", "What is a `ConcurrentHashMap` and how does it differ from `HashMap`?", "concurrenthashmap", "Explain thread-safety and performance.", "`ConcurrentHashMap` is a thread-safe implementation of `Map`. Unlike `HashTable`, it uses lock striping (locking only a portion of the map) or `synchronized` on the node level (Java 8+) to allow concurrent reads and writes without blocking the entire map, providing better concurrency performance."],
  ["Java Developer", "What is the `Comparable` and `Comparator` interface?", "comparable-vs-comparator", "Differentiate natural ordering vs custom sorting.", "`Comparable` (implemented by the class) defines the natural ordering of objects via `compareTo()`. `Comparator` defines a custom ordering that can be passed to sorting methods (e.g., `Collections.sort(list, comparator)`)."],
  ["Java Developer", "What is `Collection` vs `Collections` in Java?", "collection-vs-collections", "Explain interface vs utility class.", "`Collection` is the root interface of the collection hierarchy (e.g., `List`, `Set`). `Collections` is a utility class that provides static methods for performing operations on collections (e.g., `sort()`, `shuffle()`, `synchronizedList()`)."],
  ["Java Developer", "What is a `TreeMap` and how does it work?", "treemap", "Explain sorted map and Red-Black tree.", "`TreeMap` is a Map implementation that stores key-value pairs in a sorted order (natural ordering or by a custom comparator). It uses a Red-Black tree data structure, providing guaranteed O(log n) time complexity for `get`, `put`, and `remove` operations."],
  ["Java Developer", "What are the differences between `List`, `Set`, and `Map`?", "list-set-map", "Compare their characteristics.", "`List` is an ordered collection allowing duplicates. `Set` is an unordered collection that does not allow duplicates. `Map` stores key-value pairs and does not allow duplicate keys."],
  ["Java Developer", "What is the `fail-fast` and `fail-safe` iterator?", "fail-fast-vs-fail-safe", "Discuss concurrent modification.", "A `fail-fast` iterator (e.g., `ArrayList` iterator) throws a `ConcurrentModificationException` if the collection is modified structurally after the iterator is created. A `fail-safe` iterator (e.g., `ConcurrentHashMap` iterator) operates on a snapshot of the collection and does not throw exceptions but may not reflect recent modifications."],

  // ==================== JAVA 8 & LAMBDA / STREAMS (Medium) ====================
  ["Java Developer", "What are the main features introduced in Java 8?", "java-8-features", "List key features.", "Key features include Lambda Expressions, Stream API, Optional, Date/Time API (`java.time`), Default methods in interfaces, and the new `CompletableFuture` for asynchronous programming."],
  ["Java Developer", "What is a lambda expression in Java?", "lambda-expression", "Explain the syntax and purpose.", "A lambda expression is an anonymous function that can be used to implement a functional interface. Syntax: `(parameters) -> { body }`. It allows functional programming in Java, enabling concise code, particularly for event listeners and collection operations."],
  ["Java Developer", "What is a functional interface? Name a few examples.", "functional-interface", "Define the interface with a single abstract method.", "A functional interface is an interface with exactly one abstract method. Examples include `Runnable`, `Callable`, `Comparator`, `ActionListener`, and interfaces in `java.util.function` like `Predicate`, `Function`, `Consumer`, and `Supplier`."],
  ["Java Developer", "What is the `Optional` class in Java 8?", "optional-class", "Explain its purpose in avoiding `NullPointerException`.", "`Optional` is a container object used to represent the presence or absence of a value. It helps avoid `NullPointerException` by forcing the developer to handle the scenario of absence explicitly using methods like `isPresent()`, `orElse()`, `orElseGet()`, and `orElseThrow()`."],
  ["Java Developer", "Explain the Stream API in Java 8.", "stream-api", "Describe its purpose and common operations.", "The Stream API allows processing sequences of data (collections) in a declarative way (like SQL). It supports common operations like `filter`, `map`, `reduce`, `collect`, and `forEach`. Streams can be sequential or parallel and do not modify the source data."],
  ["Java Developer", "What is the difference between `map` and `flatMap` in Streams?", "map-vs-flatmap", "Compare the mapping operations.", "`map` applies a function to each element and returns a Stream of the results (one-to-one mapping). `flatMap` applies a function that returns a Stream for each element, and then flattens these streams into a single Stream (one-to-many mapping)."],
  ["Java Developer", "What is method reference in Java 8? Explain different types.", "method-reference", "Define and give examples.", "Method references are shorthand for lambda expressions. Types include: `Class::staticMethod` (static), `instance::instanceMethod` (instance), `Class::instanceMethod` (instance of arbitrary object), and `Class::new` (constructor)."],
  ["Java Developer", "What is the `default` keyword in interfaces?", "default-method", "Explain default methods.", "`default` allows adding new methods to interfaces without breaking existing implementations. The implementing class can use the default implementation or override it."],
  ["Java Developer", "What is the `java.time` API?", "java-time", "Explain its advantages over `java.util.Date`.", "`java.time` (JSR-310) is the modern Date/Time API introduced in Java 8. It is immutable, thread-safe, and provides clear separation of concerns with classes like `LocalDate`, `LocalTime`, `LocalDateTime`, `ZonedDateTime`, and `DateTimeFormatter`."],
  ["Java Developer", "Explain the difference between `Stream.findFirst()` and `Stream.findAny()`.", "findfirst-vs-findany", "Discuss parallel processing.", "`findFirst()` returns the first element in the encounter order of the stream. `findAny()` may return any element (non-deterministic) and is often used in parallel streams for better performance when order doesn't matter."],
  ["Java Developer", "What is a `Collector` in Streams? Name a few common ones.", "collector", "Define and give examples.", "A `Collector` is used to accumulate elements of a stream into a result container, such as a `List`, `Set`, or `Map`. Common collectors are `Collectors.toList()`, `Collectors.toSet()`, `Collectors.toMap()`, `Collectors.joining()`, and `Collectors.groupingBy()`."],
  ["Java Developer", "What is the `Predicate` functional interface?", "predicate", "Define its method and usage.", "`Predicate<T>` represents a boolean-valued function of one argument. It has a `test(T t)` method. It is commonly used with streams for `filter` operations and can be chained using `and()`, `or()`, and `negate()`."],
  ["Java Developer", "What is the `Consumer` functional interface?", "consumer", "Define its method and usage.", "`Consumer<T>` represents an operation that accepts a single input argument and returns no result. It has an `accept(T t)` method. It is commonly used with `forEach` for side-effect operations."],

  // ==================== MULTITHREADING & CONCURRENCY (Medium-Hard) ====================
  ["Java Developer", "What are the different ways to create a thread in Java?", "create-thread", "List the approaches.", "You can create a thread by extending the `Thread` class, implementing the `Runnable` interface, or implementing the `Callable` interface (which returns a value via `Future`). The `ExecutorService` framework is also a common way to manage threads."],
  ["Java Developer", "What is the difference between `Runnable` and `Callable`?", "runnable-vs-callable", "Compare return values and exceptions.", "`Runnable` does not return a result and cannot throw checked exceptions. `Callable` returns a value (via `Future`) and can throw checked exceptions."],
  ["Java Developer", "What is the lifecycle of a thread in Java?", "thread-lifecycle", "List the states.", "The thread lifecycle states are: `NEW` (created), `RUNNABLE` (ready to run or running), `BLOCKED` (waiting for a lock), `WAITING` (waiting indefinitely for another thread), `TIMED_WAITING` (waiting for a specific time), and `TERMINATED` (completed)."],
  ["Java Developer", "What is the `synchronized` keyword used for?", "synchronized", "Explain its use for thread safety.", "The `synchronized` keyword ensures that only one thread can access a block or method at a time. It provides intrinsic locking (monitor). It guarantees visibility and atomicity for the synchronized block."],
  ["Java Developer", "What is a `deadlock` and how can you prevent it?", "deadlock", "Define and provide prevention strategies.", "Deadlock occurs when two or more threads are blocked forever, each waiting on the other to release a resource. Prevention strategies include: lock ordering (acquire locks in a fixed order), using timeouts (tryLock), using higher-level concurrency utilities, and minimizing lock granularity."],
  ["Java Developer", "What is the difference between `wait()` and `sleep()`?", "wait-vs-sleep", "Compare the methods.", "`wait()` is an instance method of `Object` that releases the monitor/lock and causes the thread to wait until notified. It must be called within a synchronized block. `sleep()` is a static method of `Thread` that pauses execution for a specified time, does not release any locks, and does not require synchronization."],
  ["Java Developer", "What is `notify()` and `notifyAll()`?", "notify-notifyall", "Explain thread notification.", "`notify()` wakes up a single thread waiting on the object's monitor. `notifyAll()` wakes up all threads waiting on the object's monitor. `notifyAll()` is generally safer to prevent indefinite waiting."],
  ["Java Developer", "What is the `ExecutorService`?", "executorservice", "Explain the thread pool concept.", "`ExecutorService` is a framework for managing threads provided in `java.util.concurrent`. It abstracts away thread creation and lifecycle management. You can submit `Runnable` or `Callable` tasks to a pool (e.g., `FixedThreadPool`, `CachedThreadPool`) and manage their execution and results."],
  ["Java Developer", "What is a `Future` in Java concurrency?", "future", "Define its purpose.", "`Future` represents the result of an asynchronous computation. It provides methods to check if the computation is complete, to cancel it, and to retrieve the result (blocking if necessary) via `get()`."],
  ["Java Developer", "What is `CompletableFuture`?", "completablefuture", "Explain its advantages over `Future`.", "`CompletableFuture` is a more flexible `Future` that allows chaining, composing, and combining asynchronous tasks. It supports callback methods like `thenApply`, `thenAccept`, `thenRun`, and can be completed manually, making it very powerful for complex asynchronous workflows."],
  ["Java Developer", "What is `ThreadLocal` and when would you use it?", "threadlocal", "Explain thread-scoped variables.", "`ThreadLocal` provides per-thread variables. Each thread accessing a `ThreadLocal` variable gets its own independent copy. It is often used to maintain context like transaction IDs, user sessions, or `SimpleDateFormat` (which is not thread-safe) without synchronization."],
  ["Java Developer", "What is a `Semaphore`?", "semaphore", "Explain counting semaphores.", "A `Semaphore` is a concurrency utility that controls access to a shared resource via permits. It can be used to limit the number of threads accessing a resource concurrently."],
  ["Java Developer", "What is the difference between `ReentrantLock` and `synchronized`?", "reentrantlock-vs-synchronized", "Compare the locking mechanisms.", "`ReentrantLock` provides more flexibility than `synchronized`, such as `tryLock` (non-blocking), `lockInterruptibly`, and fairness policies. However, `synchronized` is simpler and automatically releases the lock. `ReentrantLock` requires explicit unlock in a `finally` block."],
  ["Java Developer", "What is `CountDownLatch`?", "countdownlatch", "Explain its use for thread synchronization.", "`CountDownLatch` is a synchronization aid that allows one or more threads to wait until a set of operations in other threads completes. It uses a counter that is decremented, and threads waiting on `await()` resume when the counter reaches zero."],
  ["Java Developer", "What is a `CyclicBarrier`?", "cyclicbarrier", "Explain its use for synchronization.", "`CyclicBarrier` allows a fixed number of threads to wait for each other at a barrier point before proceeding. It is 'cyclic' because it can be reused after the barrier is broken. It differs from `CountDownLatch` in that it is reusable and uses a different countdown mechanism."],
  ["Java Developer", "What is a `ReentrantReadWriteLock`?", "reentrantreadwritelock", "Explain read-write locking.", "This lock allows multiple readers to hold the lock simultaneously while the lock is not held by a writer. Writes are exclusive (only one writer can hold the lock). It improves performance for read-heavy data structures."],

  // ==================== JVM, MEMORY, & PERFORMANCE (Hard) ====================
  ["Java Developer", "What is the architecture of the Java Virtual Machine (JVM)?", "jvm-architecture", "Describe the main components.", "The JVM consists of the Class Loader subsystem, Runtime Data Areas (Method Area, Heap, Stack, PC Registers, Native Method Stack), and the Execution Engine (Interpreter, JIT Compiler, Garbage Collector)."],
  ["Java Developer", "Explain the Java Memory Model (JMM).", "jmm", "Define the abstract model for concurrency.", "The Java Memory Model specifies how the JVM interacts with the hardware memory (RAM). It defines the rules for visibility of shared variables across threads and the `happens-before` guarantee. It ensures that changes made by one thread become visible to others in a predictable order."],
  ["Java Developer", "What is the JIT compiler and how does it work?", "jit-compiler", "Explain Just-In-Time compilation.", "The JIT compiler is part of the Execution Engine. It compiles frequently executed bytecode (hot spots) into native machine code at runtime. This significantly improves performance as native code runs much faster than interpreted bytecode."],
  ["Java Developer", "What is the difference between Heap and Stack memory?", "heap-vs-stack", "Explain memory allocation.", "Heap memory is used for dynamic allocation of objects and JRE classes. It is shared across all threads. Stack memory is used for execution of a thread and stores method-specific values and references to objects (local primitives and object references). Stack is thread-private and has a fixed size."],
  ["Java Developer", "What is garbage collection in Java? How does it work?", "garbage-collection", "Explain automatic memory management.", "Garbage collection is the automatic process of identifying and discarding objects that are no longer referenced by the program, freeing heap memory. It works by marking reachable objects, sweeping (removing) unreachable objects, and optionally compacting the heap."],
  ["Java Developer", "What are the different garbage collectors available in Java?", "gc-types", "List the major collectors.", "Common garbage collectors include: Serial GC (single-threaded, good for small heaps), Parallel GC (throughput collector, multi-threaded), CMS GC (low pause, deprecated in modern JDK), G1 GC (region-based, balanced throughput and pause times), and ZGC/Shenandoah (ultra-low pause, for large heaps)."],
  ["Java Developer", "What is the `Metaspace` and how is it different from `PermGen`?", "metaspace-vs-permgen", "Explain the modern memory area for class metadata.", "`PermGen` (Permanent Generation) was a fixed-size memory area storing class metadata, interned strings, and static variables, which often led to `OutOfMemoryError`. `Metaspace` replaced it in Java 8; it uses native memory and automatically grows to the OS limit, reducing memory constraints."],
  ["Java Developer", "How do you diagnose a memory leak in Java?", "diagnose-memory-leak", "Explain tools and methods.", "Memory leaks occur when objects are unintentionally kept alive. You can diagnose them using tools like `jmap` (heap dumps), `jvisualvm`, `jconsole`, or profilers like YourKit/Async Profiler. Heap dumps can be analyzed to find object retention paths using MAT (Memory Analyzer Tool) or JProfiler."],
  ["Java Developer", "What are `soft`, `weak`, and `phantom` references?", "reference-types", "Explain the different `java.lang.ref` classes.", "`SoftReference` objects are cleared at the discretion of the GC in response to memory demand (used for caching). `WeakReference` objects are cleared when the GC runs (used for `WeakHashMap`). `PhantomReference` is used for pre-mortem cleanup actions and is queued for processing after the GC determines the object is phantom-reachable."],
  ["Java Developer", "What is a `ClassNotFoundException` and how is it different from `NoClassDefFoundError`?", "classnotfound-vs-noclassdeffound", "Differentiate the two.", "`ClassNotFoundException` is thrown when an application tries to load a class using `Class.forName()` or `ClassLoader.findSystemClass()` but the class is not found on the classpath. `NoClassDefFoundError` is thrown when a class was present at compile-time but is missing at runtime, often due to a classpath issue."],
  ["Java Developer", "What is the `-Xmx` and `-Xms` JVM parameters?", "jvm-xmx-xms", "Explain heap sizing.", "`-Xms` sets the initial and minimum heap size for the JVM. `-Xmx` sets the maximum heap size. For example, `-Xms512m -Xmx2g`."],

  // ==================== SPRING & SPRING BOOT (Medium-Hard) ====================
  ["Java Developer", "What is Spring Framework?", "spring-framework", "Define its purpose.", "Spring is a lightweight, open-source application framework for Java. It provides comprehensive infrastructure support for developing Java applications, primarily by offering Dependency Injection (DI) and Aspect-Oriented Programming (AOP)."],
  ["Java Developer", "What is Dependency Injection (DI) and how does Spring implement it?", "dependency-injection", "Explain the inversion of control.", "Dependency Injection is a design pattern where objects receive their dependencies from an external source rather than creating them internally. Spring implements DI through the Inversion of Control (IoC) container, which manages beans and injects dependencies via constructor, setter, or field injection."],
  ["Java Developer", "What is the Spring IoC Container?", "ioc-container", "Define the core container.", "The IoC container is responsible for instantiating, configuring, and assembling the Spring beans. It does this by reading configuration metadata (XML, annotations, or Java config). The main implementations are `BeanFactory` and `ApplicationContext`."],
  ["Java Developer", "What is `@Autowired` in Spring?", "autowired", "Explain its usage for dependency injection.", "`@Autowired` is an annotation used to automatically wire beans by type. It can be applied to constructors, setters, and fields to tell Spring to inject the required dependency."],
  ["Java Developer", "Explain the `@Component`, `@Service`, `@Repository`, and `@Controller` annotations.", "spring-stereotypes", "Differentiate the specialized annotations.", "All are specialized versions of `@Component` for automatic bean detection. `@Service` is used for business logic, `@Repository` for DAO (data access) and translates persistence exceptions, and `@Controller` for MVC controllers (web layer)."],
  ["Java Developer", "What is the difference between `@Bean` and `@Component`?", "bean-vs-component", "Compare the two instantiation methods.", "`@Component` is a class-level annotation used for auto-detection via classpath scanning. `@Bean` is a method-level annotation in a configuration class (`@Configuration`) used to explicitly declare a bean, allowing custom instantiation logic."],
  ["Java Developer", "What is Spring Boot? How does it simplify Spring development?", "spring-boot", "Explain its autoconfiguration.", "Spring Boot is an extension of Spring that aims to simplify configuration and deployment. It uses 'auto-configuration' to automatically configure beans based on dependencies in the classpath. It provides embedded servers (Tomcat, Jetty) and starter POMs for easy setup."],
  ["Java Developer", "What is the purpose of `application.properties` or `application.yml` in Spring Boot?", "spring-boot-config", "Explain externalized configuration.", "These files are used for externalizing configuration. They allow setting properties for the application (e.g., server port, database URLs, logging levels). Spring Boot automatically loads these properties."],
  ["Java Developer", "What is a `@RestController` in Spring Boot?", "restcontroller", "Explain its purpose in building REST APIs.", "`@RestController` is a convenience annotation combining `@Controller` and `@ResponseBody`. It is used to create RESTful web services. It automatically serializes the return value (e.g., JSON) into the HTTP response body."],
  ["Java Developer", "What is Aspect-Oriented Programming (AOP) in Spring?", "spring-aop", "Explain cross-cutting concerns.", "AOP allows separating cross-cutting concerns (like logging, security, transaction management) from business logic. In Spring, AOP is implemented using proxies and advice (e.g., `@Before`, `@After`, `@Around`)."],
  ["Java Developer", "What are Spring Profiles?", "spring-profiles", "Explain environment-specific configuration.", "Spring Profiles provide a way to segregate parts of your application configuration based on environment (e.g., `dev`, `test`, `prod`). You can activate profiles via `spring.profiles.active` and use `@Profile` to annotate beans or configuration."],
  ["Java Developer", "How does Spring manage transactions?", "spring-transactions", "Explain declarative transaction management.", "Spring provides declarative transaction management using `@Transactional`. It uses AOP to wrap methods and manage transaction boundaries (begin, commit, rollback). It supports propagation levels and isolation levels."],
  ["Java Developer", "What is a Spring Boot Starter?", "starter", "Explain its purpose.", "A starter is a set of convenient dependency descriptors that you can include in your application to get specific functionalities (e.g., `spring-boot-starter-web` for web, `spring-boot-starter-data-jpa` for JPA). They simplify the process of bringing in required libraries."],
  ["Java Developer", "Explain the difference between `@ComponentScan` and `@EnableAutoConfiguration`.", "componentscan-vs-enableautoconfig", "Differentiate their roles.", "`@ComponentScan` tells Spring where to look for components (classes annotated with `@Component`). `@EnableAutoConfiguration` tells Spring Boot to automatically configure beans based on dependencies on the classpath. Together with `@SpringBootApplication`, they orchestrate the context setup."],
  ["Java Developer", "What is the Spring `ApplicationContext`?", "applicationcontext", "Define the central interface.", "`ApplicationContext` is the central interface to provide configuration information to the Spring IoC container. It is a superset of `BeanFactory` and adds more features like event propagation, internationalization, and easier integration with resources."],
  ["Java Developer", "What is Spring `@RequestMapping`? What are its variants?", "requestmapping", "Explain routing in Spring MVC.", "`@RequestMapping` maps HTTP requests to specific controller methods. Shortcut annotations include `@GetMapping`, `@PostMapping`, `@PutMapping`, `@DeleteMapping`, and `@PatchMapping`."],
  ["Java Developer", "What are `Spring Boot Actuator` endpoints?", "actuator", "Explain monitoring and management.", "Spring Boot Actuator provides production-ready endpoints to monitor and manage your application. Common endpoints include `/health` (health status), `/metrics` (application metrics), `/info` (custom info), and `/env` (environment properties)."],
  ["Java Developer", "What is the difference between `@PathVariable` and `@RequestParam`?", "pathvariable-vs-requestparam", "Compare the two annotation types.", "`@PathVariable` binds a method parameter to a URI template variable (e.g., `/users/{id}`). `@RequestParam` binds a method parameter to a web request parameter (e.g., `?name=John`)."],
  ["Java Developer", "How does Spring Security work at a high level?", "spring-security", "Explain filter chain and authentication.", "Spring Security is based on a chain of servlet `Filter`s. Authentication is often handled by `AuthenticationManager` and `ProviderManager`. Authorization is managed through `AccessDecisionManager` or role-based annotations like `@PreAuthorize`. It integrates with various authentication mechanisms (LDAP, JWT, OAuth2)."],
  ["Java Developer", "What is `@Async` in Spring?", "async", "Explain asynchronous method execution.", "`@Async` marks a method for asynchronous execution. Spring runs it in a separate thread using a `TaskExecutor`. It must be enabled using `@EnableAsync`."],

  // ==================== SPRING DATA JPA / HIBERNATE (Medium) ====================
  ["Java Developer", "What is JPA and Hibernate?", "jpa-hibernate", "Define the specification and the implementation.", "JPA (Jakarta Persistence API) is a Java specification for managing relational data in applications. Hibernate is a popular implementation of JPA, providing ORM (Object-Relational Mapping) capabilities."],
  ["Java Developer", "Explain the concept of ORM (Object-Relational Mapping).", "orm", "Define its purpose.", "ORM is a technique that maps Java objects to database tables and vice versa. It simplifies data persistence by allowing developers to work with objects rather than writing SQL queries manually, reducing boilerplate code."],
  ["Java Developer", "What is Spring Data JPA?", "spring-data-jpa", "Explain its role.", "Spring Data JPA is a part of the larger Spring Data family. It provides a repository abstraction over JPA/Hibernate, significantly reducing the boilerplate code required for DAOs. It provides interfaces like `JpaRepository` with common CRUD methods."],
  ["Java Developer", "What is the difference between `JpaRepository` and `CrudRepository`?", "jparepository-vs-crudrepository", "Compare the repository interfaces.", "`CrudRepository` provides basic CRUD operations. `JpaRepository` extends `CrudRepository` and adds additional methods specific to JPA, like batch operations and flushing."],
  ["Java Developer", "What are the different fetch strategies in JPA? (`EAGER` vs `LAZY`)", "eager-vs-lazy", "Explain the loading strategies.", "`EAGER` loads related entities immediately (in the same query or join). `LAZY` loads related entities on-demand (proxies are used, and data is fetched when accessed). `LAZY` is preferred to avoid loading unnecessary data."],
  ["Java Developer", "What is the difference between `@Entity` and `@Table`?", "entity-vs-table", "Explain the JPA annotations.", "`@Entity` marks a class as a JPA entity (mapped to a database table). `@Table` is optional and allows you to specify the exact table name, schema, and catalog."],
  ["Java Developer", "What is `@Transactional` in Spring and how does it work?", "transactional", "Explain declarative transaction management.", "`@Transactional` declares that the method execution must be performed within a transaction. Spring uses AOP to intercept the method, starts a transaction before, and commits/rolls back after execution based on exceptions thrown."],
  ["Java Developer", "What is the persistence context in JPA?", "persistence-context", "Explain the first-level cache.", "The persistence context is a set of managed entity instances. It acts as a first-level cache, tracking entity changes and ensuring that within the same transaction, the same entity instance is returned for the same database row, maintaining consistency."],
  ["Java Developer", "What is the difference between `save()` and `saveAndFlush()` in Spring Data JPA?", "save-vs-saveandflush", "Explain immediate persistence.", "`save()` persists an entity but may not immediately synchronize the changes with the database (the flush happens when the transaction commits). `saveAndFlush()` immediately flushes the changes to the database."],
  ["Java Developer", "How do you define a custom query in Spring Data JPA?", "custom-query", "Explain `@Query` and method naming conventions.", "You can define custom queries by using the `@Query` annotation with JPQL or native SQL. Alternatively, you can use method naming conventions (e.g., `findByFirstName(String firstName)`) where Spring Data JPA derives the query from the method name."],

  // ==================== TESTING (Medium) ====================
  ["Java Developer", "What is JUnit and how is it used?", "junit", "Explain the testing framework.", "JUnit is a popular unit testing framework for Java. It uses annotations like `@Test`, `@BeforeEach`, and `@AfterEach`. Developers write test methods to verify individual units of code, ensuring correctness and preventing regressions."],
  ["Java Developer", "What is Mockito and how does it help in testing?", "mockito", "Explain mocking frameworks.", "Mockito is a mocking framework that allows creating mock objects for dependencies in unit tests. It helps isolate the class under test and verify behavior (e.g., `when(mock.method()).thenReturn(value)` and `verify(mock).methodCalled()`)."],
  ["Java Developer", "What is the difference between `@Before` and `@BeforeClass` (or `@BeforeEach` and `@BeforeAll`)?", "before-vs-beforeclass", "Explain lifecycle setup.", "`@BeforeEach` runs before each test method, used for common setup. `@BeforeAll` runs once for the entire test class, used for expensive setup (must be static)."],
  ["Java Developer", "What is `@SpringBootTest` used for?", "springboottest", "Explain integration testing.", "`@SpringBootTest` is an annotation used to bootstrap the full Spring application context for integration testing. It helps test the entire application, enabling features like `@Autowired` and loading `application.properties`."],
  ["Java Developer", "What is the difference between unit testing and integration testing?", "unit-vs-integration-test", "Differentiate the test types.", "Unit testing focuses on testing individual components/classes in isolation, mocking dependencies. Integration testing focuses on verifying the interaction between components (e.g., database, external services, or modules) to ensure they work correctly together."],

  // ==================== GENERAL & ARCHITECTURE (Medium-Hard) ====================
  ["Java Developer", "What is REST? Explain the principles.", "rest-principles", "Define RESTful architecture.", "REST (Representational State Transfer) is an architectural style for designing networked applications. Principles include statelessness, client-server separation, cacheability, uniform interface (using HTTP methods like GET, POST, PUT, DELETE), and layered system."],
  ["Java Developer", "What are Microservices? What are their advantages and disadvantages?", "microservices", "Explain the architecture style.", "Microservices are an architectural style where applications are composed of small, independent services deployed separately. Advantages include independent deployability, scalability, and technology diversity. Disadvantages include increased operational complexity, network latency, and data consistency challenges."],
  ["Java Developer", "What is a `Docker` container? How does it relate to Java?", "docker", "Explain containerization.", "Docker is a platform for containerizing applications. It packages an application and its dependencies into an isolated, lightweight container. For Java, it ensures the application runs the same on any environment and simplifies dependency management (like JVM version)."],
  ["Java Developer", "What is the difference between a `Maven` and `Gradle`?", "maven-vs-gradle", "Compare the build tools.", "Maven uses an XML-based (`pom.xml`) declarative structure and follows convention over configuration. Gradle uses a Groovy/Kotlin DSL, is more flexible, and is faster for large projects due to incremental builds and caching."],
  ["Java Developer", "What is a `WebSocket` and how is it different from REST?", "websocket-vs-rest", "Compare the communication protocols.", "REST is request-response (HTTP) and stateless. WebSocket is a full-duplex, persistent connection protocol that allows real-time bidirectional communication, ideal for chat or live updates."],
  ["Java Developer", "What is an API Gateway? Why is it used in microservices?", "api-gateway", "Explain its role.", "An API Gateway acts as a single entry point for clients to access multiple microservices. It handles request routing, load balancing, authentication, rate limiting, and response aggregation, simplifying the client-side interaction."],
  ["Java Developer", "What is a distributed transaction? How do you handle it in microservices?", "distributed-transaction", "Explain saga pattern.", "A distributed transaction spans multiple services. Handling it directly (2PC) is often impractical. The Saga pattern is commonly used, where a saga is a sequence of local transactions. If one fails, compensating transactions are executed to rollback the previous ones."],
  ["Java Developer", "How do you handle security (JWT/OAuth2) in a Java REST API?", "jwt-oauth2", "Explain token-based authentication.", "JWT (JSON Web Token) is a stateless authentication mechanism. The server issues a signed token upon login. The client includes the token in the Authorization header for subsequent requests. Spring Security integrates with JWT via filters."],
  ["Java Developer", "What are the considerations for high availability and scalability in a Java application?", "ha-scalability", "Discuss horizontal scaling and resilience.", "Scalability (horizontal) involves adding more instances. High availability requires redundancy. Considerations include load balancing, statelessness, distributing the load, caching, using a robust message queue, and implementing circuit breakers (Resilience4j) to handle failures gracefully."],
  ["Java Developer", "What is the `SLF4J` and why is it used?", "slf4j", "Explain logging frameworks.", "SLF4J (Simple Logging Facade for Java) is a facade that allows using different logging frameworks (like Logback, Log4j) via a single API. It provides a simple way to switch implementations and supports parameterized logging for better performance."],

  // ==================== ADVANCED / CONCURRENCY (Hard) ====================
  ["Java Developer", "What is `Structured Concurrency` in Java (Project Loom)?", "structured-concurrency", "Explain virtual threads and structured concurrency.", "Project Loom introduces virtual threads (lightweight threads) to simplify concurrency and improve scalability. Structured concurrency ensures that when a task is split into subtasks, they are managed as a unit, ensuring proper cancellation and error handling, making code more reliable and observable."],
  ["Java Developer", "What is a `Virtual Thread` vs a `Platform Thread`?", "virtual-thread-vs-platform", "Compare the two thread types.", "Platform threads are thin wrappers around OS threads, expensive to create. Virtual threads are user-mode threads managed by the JVM, decoupled from OS threads. They are extremely lightweight, allowing millions of virtual threads to coexist, dramatically simplifying high-concurrency applications."],
  ["Java Developer", "Explain `Fork/Join` framework in Java.", "fork-join", "Define its purpose for parallel processing.", "The Fork/Join framework is designed for parallel processing of large datasets. It divides a task into smaller subtasks (fork) and then combines the results (join). It uses the `Work-Stealing` algorithm, where idle threads steal tasks from busy ones, improving efficiency."],
  ["Java Developer", "What is a `ConcurrentSkipListMap` and when would you use it?", "concurrentskiplistmap", "Explain the concurrent sorted map.", "It is a thread-safe implementation of `NavigableMap` (sorted map) based on a skip list. It provides average O(log n) performance and is highly concurrent, used when you need a thread-safe, sorted, scalable map."],

  // ==================== ADVANCED / DESIGN PATTERNS (Medium-Hard) ====================
  ["Java Developer", "What is the Singleton design pattern? How do you implement it in Java?", "singleton", "Explain the pattern and thread-safe implementation.", "Singleton ensures a class has only one instance. A thread-safe implementation uses a private static final instance, or an enum, or a double-checked locking mechanism (with `volatile`) to ensure it is safe in multi-threaded environments."],
  ["Java Developer", "What is the Factory design pattern?", "factory-pattern", "Explain the creational pattern.", "Factory pattern provides an interface for creating objects without specifying the exact class. It allows creation logic to be decoupled from the client code, often used with dependency injection."],
  ["Java Developer", "What is the Observer design pattern?", "observer-pattern", "Define the behavioral pattern.", "Observer defines a one-to-many dependency between objects so that when one object (the subject) changes state, all its dependents (observers) are notified and updated automatically. Java's `Observable`/`Observer` (deprecated) or event listeners exemplify this."],
  ["Java Developer", "What is the Strategy design pattern?", "strategy-pattern", "Explain the behavioral pattern.", "Strategy pattern allows defining a family of algorithms, encapsulating each one, and making them interchangeable. It lets the algorithm vary independently from clients that use it, often used for sorting or payment methods."],
  ["Java Developer", "What is the Builder design pattern? Why is it useful?", "builder-pattern", "Explain the creational pattern.", "Builder pattern separates the construction of a complex object from its representation. It's useful for creating objects with many optional parameters, improving readability and avoiding telescoping constructors. It is used in `StringBuilder` and `Stream.Builder`."],
  ["Java Developer", "What is the Decorator design pattern?", "decorator-pattern", "Explain the structural pattern.", "Decorator pattern allows behavior to be added to an individual object, either statically or dynamically, without affecting the behavior of other objects from the same class. Java I/O classes (`BufferedReader`, `InputStreamReader`) are classic examples."],

  // ==================== DATA STRUCTURES & ALGORITHMS (Medium-Hard) ====================
  ["Java Developer", "Explain the Time Complexity of different `List` implementations in Java.", "list-time-complexity", "Cover `ArrayList` and `LinkedList`.", "`ArrayList` has O(1) access and O(n) insertion/deletion in the middle. `LinkedList` has O(n) access and O(1) insertion/deletion at ends. For middle insertion, both are O(n) due to traversal, though `ArrayList` shifts elements while `LinkedList` traverses."],
  ["Java Developer", "What is a `PriorityQueue` in Java and how does it work?", "priorityqueue", "Explain the min-heap implementation.", "`PriorityQueue` is a unbounded priority queue based on a priority heap (binary heap by default). It orders elements by their natural ordering or a custom comparator. The head of the queue is the least element."],
  ["Java Developer", "Explain the `Map` interface and its common implementations.", "map-interface", "List implementations.", "Common implementations are `HashMap` (unsynchronized, O(1)), `TreeMap` (sorted, O(log n)), `LinkedHashMap` (insertion-order iteration), and `ConcurrentHashMap` (thread-safe)."],
  ["Java Developer", "What is a `BlockingQueue` and its common implementations?", "blockingqueue", "Explain the concurrent queue.", "A `BlockingQueue` is a queue that supports blocking operations: `take()` (retrieves and removes head, waiting if empty) and `put()` (inserts element, waiting if full). Common implementations are `ArrayBlockingQueue`, `LinkedBlockingQueue`, and `PriorityBlockingQueue`."],
  ["Java Developer", "How do you handle large numbers in Java (beyond 64-bit)?", "biginteger-bigdecimal", "Explain `BigInteger` and `BigDecimal`.", "`BigInteger` and `BigDecimal` are classes in `java.math` to handle arbitrary precision. `BigInteger` is for immutable arbitrary-precision integers. `BigDecimal` is for immutable arbitrary-precision signed decimal numbers, suitable for financial calculations requiring exact precision."],
  ["Java Developer", "What is the difference between `String` and `String` intern pool?", "string-intern", "Explain string pooling.", "The String intern pool is a special memory region in the heap where Java stores literal strings. When a new string literal is created, the JVM checks the pool; if it exists, it returns the reference, saving memory."],

  // ==================== JAVA 9-21 FEATURES (Medium) ====================
  ["Java Developer", "What is a `var` keyword introduced in Java 10?", "var-keyword", "Explain local variable type inference.", "`var` allows the compiler to infer the type of local variables based on the initializer expression. It promotes cleaner code but is restricted to local variables with initializers."],
  ["Java Developer", "What are Java `Records` (Java 14/16)?", "records", "Explain data carriers.", "Records are a new kind of class in Java designed to be transparent data carriers. They provide a concise way to define classes whose main purpose is to hold data, automatically generating constructors, accessors, `equals`, `hashCode`, and `toString`."],
  ["Java Developer", "What are `Text Blocks` in Java (Java 13/15)?", "text-blocks", "Explain multi-line strings.", "Text blocks are multi-line string literals that simplify writing HTML, JSON, or SQL strings. They avoid the need for most escape sequences and preserve indentation."],
  ["Java Developer", "What is Pattern Matching in Java (Java 16+)?", "pattern-matching", "Explain instance-of pattern.", "Pattern matching simplifies the `instanceof` check and cast into a single operation. For example, `if (obj instanceof String s) { ... }` directly defines the variable `s`."],
  ["Java Developer", "What is the `Optional` class and its common pitfalls?", "optional-pitfalls", "Discuss misuse of `Optional`.", "`Optional` should not be used as a field, method parameter, or serializable object. It is designed for return types to clearly indicate the absence of a value. Misusing it as a general-purpose wrapper defeats its purpose."],
  ["Java Developer", "What are modules in Java (Project Jigsaw)?", "java-modules", "Explain Java 9 modules.", "Java modules encapsulate code and explicitly declare dependencies (via `module-info.java`). This improves security, performance, and maintainability by reducing classpath pollution and enforcing strong encapsulation."],
  ["Java Developer", "What are `Sealed Classes` (Java 15/17)?", "sealed-classes", "Explain restrictions on subclasses.", "Sealed classes allow you to restrict which other classes or interfaces can extend or implement them. They provide a more controlled inheritance hierarchy, useful for representing fixed possibilities (e.g., `Either` or `Result` types)."],

  // ==================== SPRING CLOUD & MICROSERVICES (Hard) ====================
  ["Java Developer", "What is Spring Cloud?", "spring-cloud", "Explain its role in microservices.", "Spring Cloud provides tools for building distributed systems and microservices. It offers features like service discovery (Netflix Eureka), configuration management (Spring Cloud Config), circuit breakers (Resilience4j), and distributed tracing (Sleuth/Zipkin)."],
  ["Java Developer", "What is a Circuit Breaker pattern and how is it implemented in Java?", "circuit-breaker", "Define and explain Resilience4j.", "The Circuit Breaker pattern prevents a system from repeatedly trying to invoke a failing operation. It is implemented in Java using libraries like Resilience4j or Netflix Hystrix. It has states: CLOSED (calls pass), OPEN (calls fail fast), and HALF-OPEN (testing recovery)."],
  ["Java Developer", "What is `Eureka` and `Spring Cloud Config`?", "eureka-config", "Explain service discovery and config server.", "Eureka is a service discovery client-server where microservices register themselves and discover others via a REST API. Spring Cloud Config provides externalized configuration in a distributed system, serving properties from Git or other backends."],

  // ==================== JPA / HIBERNATE ADVANCED (Medium-Hard) ====================
  ["Java Developer", "Explain the Hibernate `Session` and how it differs from `EntityManager`.", "session-vs-entitymanager", "Compare JPA and Hibernate APIs.", "`Session` is Hibernate's core API for persistence operations, while `EntityManager` is the standard JPA interface. `Session` contains Hibernate-specific methods, but `EntityManager` is preferred for portability across JPA implementations."],
  ["Java Developer", "What is the N+1 query problem in Hibernate and how do you solve it?", "n-plus-1", "Explain the performance issue and solution.", "The N+1 problem occurs when fetching an entity and its associated collection triggers N additional queries for each entity. It is solved by using `JOIN FETCH` in JPQL, or using `@EntityGraph` to specify eager loading, or using Hibernate's fetch strategies."],
  ["Java Developer", "What is the difference between `FetchType.LAZY` and `FetchType.EAGER` performance implications?", "lazy-vs-eager-performance", "Discuss performance trade-offs.", "`EAGER` can cause performance issues because it loads unnecessary data, especially in large object graphs. `LAZY` avoids loading data until needed, but can lead to `LazyInitializationException` if accessed outside the persistence context."],

  // ==================== EXCEPTION HANDLING & LOGGING (Medium) ====================
  ["Java Developer", "How do you create a custom exception in Java?", "custom-exception", "Write a custom exception class.", "You extend `Exception` for checked exceptions or `RuntimeException` for unchecked. Provide constructors to pass a message, cause, or both. Example: `class MyException extends Exception { public MyException(String msg) { super(msg); } }`"],
  ["Java Developer", "What is logging and why is it important? Compare Log4j and SLF4J.", "logging-frameworks", "Explain the facade pattern.", "Logging is crucial for debugging and monitoring. SLF4J is a facade that abstracts the underlying logging implementation. Log4j is a concrete implementation. Using SLF4J with Log4j allows switching to Logback or other frameworks without code changes."],

  // ==================== PERFORMANCE TUNING (Hard) ====================
  ["Java Developer", "How do you profile a Java application for performance bottlenecks?", "profiling", "Explain tools and methods.", "You can use profilers like JProfiler, YourKit, or Java VisualVM to monitor CPU usage, memory allocation, and thread activity. Async Profiler is excellent for low-overhead profiling. Analyzing GC logs and heap dumps also helps identify bottlenecks."],
  ["Java Developer", "What is the concept of `escape analysis` in JVM?", "escape-analysis", "Explain JIT optimization.", "Escape analysis is a technique where the JIT compiler determines if an object is confined to a single method (does not escape). If it doesn't escape, the JVM can allocate it on the stack (rather than the heap) and even eliminate synchronization, improving performance."],

  // ==================== COMMUNICATION & STREAMS (Medium) ====================
  ["Java Developer", "What are `InputStream` and `OutputStream` in Java?", "io-streams", "Explain byte streams.", "`InputStream` and `OutputStream` are abstract classes for reading and writing raw byte data. They are the foundation of Java's I/O. Common subclasses are `FileInputStream`, `FileOutputStream`, `BufferedInputStream`, etc."],
  ["Java Developer", "What is the NIO (New I/O) package?", "nio", "Explain non-blocking I/O.", "NIO (java.nio) introduced in Java 1.4 provides non-blocking I/O operations. It uses channels and buffers (`ByteBuffer`). It is highly scalable for network servers as it allows a single thread to manage multiple connections using `Selector`s."],

  // ==================== ADDITIONAL FRESHER & BEHAVIORAL ====================
  ["Java Developer", "Describe a challenging Java project you have worked on.", "challenging-project", "Showcase your practical experience.", "I built a high-throughput REST API using Spring Boot that processed large CSV files. The challenge was handling memory efficiently, so I used streams and batch processing with JPA to avoid `OutOfMemoryError`."],
  ["Java Developer", "How do you prioritize between performance and code readability?", "performance-vs-readability", "Demonstrate balanced judgement.", "Readability is generally prioritized for maintainability. However, if performance metrics indicate a specific bottleneck, I optimize that part while keeping the rest of the code clean and well-documented."],
  ["Java Developer", "What does a typical daily routine look like for you as a Java developer?", "daily-routine", "Describe your workflow.", "It includes stand-up meetings, reviewing code, writing new features or fixing bugs, attending design discussions, and occasionally helping other team members with technical blockers."]
] as const;

const prisma = new PrismaClient();

const buildWhyInterviewersAsk = (question: string, shortDescription: string) =>
  `Interviewers ask this to check whether you can explain JAVA concepts clearly and connect them to practical engineering decisions. ${shortDescription} A strong response should address the purpose, the relevant trade-offs, and how you would verify the result rather than reciting a command or definition.`;

const buildCommonMistakes = (question: string) => [
  `Giving a memorized definition without explaining how it applies to: ${question}`,
  "Listing JAVA commands without explaining the safety, performance, or operational trade-off.",
  "Ignoring security boundaries, persistence, failure handling, or how the solution would be tested.",
];

async function main() {
  const category = await prisma.category.upsert({
    where: { slug: "java" },
    update: { name: "Java", group: "Technology", description: "Java interview questions." },
    create: { name: "Java", slug: "java", group: "Technology", description: "Java interview questions." },
  });
  const subcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: category.id, slug: "Java" } },
    update: {},
    create: { name: "Java", slug: "java", categoryId: category.id },
  });

  for (let topicIndex = 0; topicIndex < topics.length; topicIndex += 1) {
    const [, question, slug, shortDescription, sampleAnswer] = topics[topicIndex];
    const commonMistakes = buildCommonMistakes(question);
    const followUpQuestions = [
      topics[(topicIndex + 1) % topics.length][1],
      topics[(topicIndex + 2) % topics.length][1],
      topics[(topicIndex + 3) % topics.length][1],
    ];
    await prisma.interviewQuestion.upsert({
      where: { slug },
      update: {
        question,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["Java"],
        isPublished: true,
      },
      create: {
        question,
        slug,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["Java"],
        isPublished: true,
      },
    });
  }

  console.log(`Imported ${topics.length} Java questions.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());

export const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");