// ---- 200 Microservices Interview Questions (Fresher to Advanced) ----
// ---- 200 Linux System Engineering Questions (Fresher to Advanced) ----
// ---- 200 Kubernetes Interview Questions (Fresher to Advanced) ----
// ---- 200 Java Developer Questions (Fresher to Advanced) ----
import { Difficulty, ExperienceLevel, InterviewType, PrismaClient } from "@prisma/client";

// ---- 200 Docker Interview Questions (Fresher to Advanced) ----
// ---- Categories ----
export const categories = [
  ["Microservices", "Microservices"]
] as const;

// ---- 200 Git & GitHub Interview Questions (Fresher to Advanced) ----
export const topics = [
  // ==================== CORE CONCEPTS (Easy) ====================
  ["Microservices", "What are microservices? How do they differ from monolithic architecture?", "microservices-vs-monolith", "Define microservices and contrast with monoliths.", "Microservices are small, independent services that communicate over a network. They are loosely coupled, independently deployable, and organized around business capabilities. A monolith is a single, tightly coupled application where all components are deployed together."],
  ["Microservices", "What are the main characteristics of microservices?", "microservices-characteristics", "List the key traits.", "Key characteristics: componentization via services, organized around business capabilities, products not projects, smart endpoints and dumb pipes, decentralized governance, decentralized data management, infrastructure automation, design for failure, and evolutionary design."],
  ["Microservices", "What are the advantages and disadvantages of microservices?", "microservices-pros-cons", "List the pros and cons.", "Advantages: independent scaling, technology diversity, faster deployment, resilience, and team autonomy. Disadvantages: complexity, network latency, distributed transactions, increased operational overhead, and debugging challenges."],
  ["Microservices", "What is the difference between a monolithic and a microservice architecture in terms of deployment?", "deployment-monolith-vs-microservices", "Explain deployment differences.", "In a monolith, the entire application is deployed as a single unit. In microservices, each service is deployed independently, allowing more frequent and safer releases. Microservices enable blue-green, canary, and rolling deployments per service."],
  ["Microservices", "What is Domain-Driven Design (DDD) and how does it relate to microservices?", "ddd-microservices", "Explain DDD's role in service boundaries.", "DDD is a software design approach that models complex domains by focusing on the core business logic. It helps define bounded contexts, which become natural service boundaries in microservices, ensuring services are aligned with business capabilities."],
  ["Microservices", "What is the bounded context in DDD?", "bounded-context", "Define the concept.", "A bounded context is a logical boundary within which a particular domain model is defined and applicable. It ensures that terms, concepts, and business rules are consistent. Each microservice typically owns one bounded context."],
  ["Microservices", "What is the difference between a service and a microservice?", "service-vs-microservice", "Clarify the terminology.", "All microservices are services, but not all services are microservices. A microservice is a specific architectural style characterized by being small, independently deployable, and focused on a single business capability. A service is a broader term for any unit of functionality."],
  ["Microservices", "What are the challenges of data consistency in microservices?", "data-consistency-challenges", "Explain the difficulty.", "In microservices, each service owns its own database, making ACID transactions across services impossible. This leads to challenges in maintaining data consistency, requiring eventual consistency and patterns like sagas."],
  ["Microservices", "What is the role of an API Gateway in microservices?", "api-gateway-role", "Explain the gateway's responsibilities.", "An API Gateway acts as a single entry point for clients. It routes requests to appropriate services, handles cross-cutting concerns like authentication, rate limiting, caching, request/response transformation, and aggregates results from multiple services."],
  ["Microservices", "What is service discovery and why is it needed?", "service-discovery", "Explain dynamic locating of services.", "Service discovery allows services to locate each other dynamically without hardcoded endpoints. It is needed because microservices can be deployed on dynamic IPs and scales horizontally. It enables resilience and load balancing."],

  // ==================== COMMUNICATION PATTERNS (Medium) ====================
  ["Microservices", "What are the different ways microservices communicate with each other?", "microservices-communication", "List synchronous and asynchronous methods.", "Synchronous: REST (HTTP), gRPC, GraphQL. Asynchronous: messaging queues (RabbitMQ), event streaming (Kafka), WebSockets. The choice depends on the need for immediate response vs. decoupling and resilience."],
  ["Microservices", "What is the difference between REST and gRPC in microservices?", "rest-vs-grpc", "Compare the protocols.", "REST uses HTTP/1.1 with JSON, is text-based, and supports CRUD operations. gRPC uses HTTP/2 with Protocol Buffers (binary serialization), supports bidirectional streaming, and is more efficient. gRPC is ideal for internal service-to-service communication."],
  ["Microservices", "What is the difference between synchronous and asynchronous communication?", "sync-vs-async-microservices", "Explain the two styles.", "Synchronous communication (e.g., REST, gRPC) requires the caller to wait for the response. Asynchronous communication (e.g., messaging, events) does not block the caller, enabling decoupling and better fault tolerance."],
  ["Microservices", "What is a message broker and when would you use it?", "message-broker", "Explain the intermediate layer.", "A message broker (e.g., RabbitMQ, Kafka) facilitates asynchronous communication by storing and forwarding messages between services. Use it for decoupling, event-driven architectures, and handling spikes in traffic."],
  ["Microservices", "What is Apache Kafka and how is it used in microservices?", "kafka-microservices", "Explain Kafka's role.", "Kafka is a distributed event streaming platform used for building real-time data pipelines and streaming applications. In microservices, it enables event-driven communication, log aggregation, and stream processing."],
  ["Microservices", "What is the difference between a queue and a topic in messaging?", "queue-vs-topic", "Explain the messaging models.", "A queue implements point-to-point messaging: one message is consumed by one consumer. A topic implements publish-subscribe: messages are broadcast to all subscribers. Kafka uses topics with partitions for scalability."],
  ["Microservices", "What is the Circuit Breaker pattern and why is it important?", "circuit-breaker-pattern", "Explain the resilience pattern.", "The Circuit Breaker pattern prevents a service from repeatedly invoking a failing operation. It has three states: Closed (normal), Open (fails fast), and Half-Open (tests for recovery). It stops cascading failures and gives the failing service time to recover."],
  ["Microservices", "What is the Retry pattern and how does it differ from Circuit Breaker?", "retry-vs-circuit-breaker", "Compare the patterns.", "Retry attempts to re-invoke a failed operation, often with exponential backoff, to handle transient failures. Circuit Breaker short-circuits calls after repeated failures to prevent overloading. They are complementary."],
  ["Microservices", "What is the Bulkhead pattern?", "bulkhead-pattern", "Explain resource isolation.", "The Bulkhead pattern isolates resources (e.g., thread pools, connections) so that a failure in one part does not deplete resources in another. It improves resilience by limiting the blast radius of failures."],
  ["Microservices", "What is the difference between Orchestration and Choreography in sagas?", "orchestration-vs-choreography-saga", "Compare the two approaches.", "Orchestration uses a central coordinator (orchestrator) to manage the saga's steps and decisions. Choreography relies on events – each service publishes events and reacts to events from others, with no central controller. Orchestration is easier to monitor; choreography is more decoupled."],
  ["Microservices", "What is the Saga pattern and when would you use it?", "saga-pattern", "Explain distributed transactions.", "The Saga pattern manages distributed transactions across microservices by breaking them into a sequence of local transactions, each with a compensating action. It ensures eventual consistency without using distributed transactions (2PC)."],
  ["Microservices", "What is the difference between a saga and a two-phase commit (2PC)?", "saga-vs-2pc", "Compare the two distributed transaction approaches.", "2PC is a synchronous, blocking protocol that provides strong consistency but is not suitable for microservices due to latency and single point of failure. Saga is asynchronous, non-blocking, and provides eventual consistency, making it the preferred choice for microservices."],
  ["Microservices", "What is the Event Sourcing pattern?", "event-sourcing", "Explain storing state as events.", "Event Sourcing stores the state of a system as a sequence of events. The current state is derived by replaying events. It provides a complete audit trail and enables temporal queries. Often used with CQRS in microservices."],
  ["Microservices", "What is CQRS (Command Query Responsibility Segregation)?", "cqrs", "Explain separating read and write models.", "CQRS separates the models for reading (queries) and writing (commands) data. It allows optimizing each side independently – writes are often stored as events (Event Sourcing), and reads use denormalized views for performance."],
  ["Microservices", "What is the difference between Event Sourcing and CQRS?", "event-sourcing-vs-cqrs", "Explain the relationship.", "Event Sourcing is a storage pattern where state is stored as events. CQRS is an architectural pattern that separates read and write models. They are often used together but are independent: you can have CQRS without Event Sourcing and vice versa."],

  // ==================== DATA MANAGEMENT (Medium-Hard) ====================
  ["Microservices", "How do you handle data consistency in microservices?", "data-consistency", "Explain strategies.", "Use eventual consistency, sagas, compensating transactions, and idempotent operations. Accept that consistency may take time. Design APIs to be tolerant of stale data where possible."],
  ["Microservices", "What is the Database per Service pattern?", "database-per-service", "Explain the decentralized data approach.", "Each microservice owns its own database schema. Services do not share databases; they communicate only via APIs or messages. This ensures loose coupling and allows each service to choose the database that best fits its needs."],
  ["Microservices", "What are the challenges of the Database per Service pattern?", "database-per-service-challenges", "List the difficulties.", "Challenges include: maintaining data consistency across services, handling distributed transactions, managing data replication and synchronization, and reporting across services."],
  ["Microservices", "What is the API Composition pattern?", "api-composition", "Explain aggregating data from multiple services.", "API Composition is a pattern where a client or gateway queries multiple services and aggregates the results. It is a simple way to get data from multiple sources but can introduce performance overhead."],
  ["Microservices", "What is the CQRS pattern and how does it help with reporting?", "cqrs-reporting", "Explain read model optimization.", "CQRS allows building separate read models optimized for reporting and queries. These read models can be denormalized, pre-joined, and stored in a cache or a separate database, making reports fast and efficient."],
  ["Microservices", "What is the Strangler Fig pattern?", "strangler-fig", "Explain incremental migration.", "The Strangler Fig pattern incrementally replaces parts of a monolithic system with microservices. New features are built as microservices, and over time, the monolith is 'strangled' by routing traffic to the new services."],
  ["Microservices", "What is the importance of idempotency in microservices?", "idempotency", "Explain duplicate handling.", "Idempotency ensures that performing the same operation multiple times has the same effect as doing it once. It is crucial for microservices to handle duplicate requests (e.g., due to retries) without unintended side effects. Implement using idempotency keys."],
  ["Microservices", "How do you handle database migrations in a microservices environment?", "db-migrations-microservices", "Explain schema evolution.", "Use backward-compatible changes (e.g., adding columns). Perform migrations in phases: add new columns, deploy code that uses them, then remove old columns. Use online schema change tools. Each service manages its own migrations."],
  ["Microservices", "What is the difference between shared database and database per service?", "shared-db-vs-db-per-service", "Compare the two approaches.", "Shared database couples services and leads to tight coupling. Database per service decouples services, allows independent scaling and technology choice, but introduces distributed data challenges. Database per service is the preferred pattern for microservices."],
  ["Microservices", "What is a distributed transaction in microservices and why is it avoided?", "distributed-transaction", "Explain why 2PC is discouraged.", "A distributed transaction spans multiple services and databases. Two-phase commit (2PC) is often avoided because it is synchronous, blocks resources, and introduces a single point of failure, reducing availability. Sagas are preferred for eventual consistency."],

  // ==================== SECURITY & IDENTITY (Medium) ====================
  ["Microservices", "How do you secure microservices?", "secure-microservices", "List security strategies.", "Use OAuth2 / OpenID Connect for authentication, JWT for stateless authorization, API Gateway for enforcing security policies, mutual TLS (mTLS) for service-to-service authentication, and role-based access control (RBAC)."],
  ["Microservices", "What is JWT and how is it used in microservices?", "jwt-microservices", "Explain JSON Web Tokens.", "JWT is a self-contained token containing claims (e.g., user ID, roles). It is used for stateless authentication: the client presents the token in requests, and the service validates it without needing to query a centralized session store."],
  ["Microservices", "What is OAuth2 and how does it relate to microservices?", "oauth2-microservices", "Explain the authorization framework.", "OAuth2 is a delegation protocol that allows clients to obtain access tokens from an authorization server. In microservices, the API Gateway or resource servers validate these tokens to authorize requests, often using OAuth2 together with JWT."],
  ["Microservices", "What is the difference between authentication and authorization?", "authentication-vs-authorization", "Define the two terms.", "Authentication verifies who a user or service is (identity). Authorization determines what actions they are allowed to perform (permissions)."],
  ["Microservices", "What is mutual TLS (mTLS) and why is it used in microservices?", "mtls", "Explain two-way TLS.", "mTLS is a security mechanism where both client and server authenticate each other using certificates. It ensures that only authorized services can communicate with each other, providing strong security for service-to-service communication."],
  ["Microservices", "What is a service account and how is it used?", "service-account", "Explain non-human identities.", "A service account is an identity used by applications (not human users) to authenticate with other services. It is commonly used with JWT or OAuth2 client credentials flow to allow services to obtain tokens."],
  ["Microservices", "What is role-based access control (RBAC) in microservices?", "rbac-microservices", "Explain access control.", "RBAC assigns permissions to roles, and users or services are assigned roles. In microservices, roles are often stored in JWT claims, and each service enforces its own authorization rules based on these roles."],
  ["Microservices", "How do you manage secrets in a microservices environment?", "secrets-management", "Explain secure storage.", "Use a secrets management tool like HashiCorp Vault, AWS Secrets Manager, or Kubernetes Secrets. Secrets are injected into services at runtime, never stored in code or configuration files."],
  ["Microservices", "What is the Principle of Least Privilege in microservices?", "least-privilege", "Explain the security principle.", "Each service should have only the minimum permissions required to perform its function. This limits the blast radius of a security breach."],
  ["Microservices", "What is an OAuth2 scope and how is it used?", "oauth2-scope", "Explain fine-grained authorization.", "Scopes are used to define fine-grained permissions (e.g., `read:orders`, `write:users`). OAuth2 tokens can include scopes, and services can enforce access based on these scopes."],

  // ==================== OBSERVABILITY & MONITORING (Medium) ====================
  ["Microservices", "What is observability in microservices?", "observability-microservices", "Define the concept.", "Observability is the ability to understand the internal state of a system by examining its outputs (logs, metrics, traces). In microservices, it is crucial for debugging, performance tuning, and understanding distributed interactions."],
  ["Microservices", "What are the three pillars of observability?", "observability-pillars", "List logs, metrics, and traces.", "Logging (structured events), Metrics (numerical measurements), and Distributed Tracing (request flow). Together they provide comprehensive visibility into a microservices ecosystem."],
  ["Microservices", "What is distributed tracing and why is it important?", "distributed-tracing", "Explain tracing across services.", "Distributed tracing tracks a single request as it propagates through multiple services. It helps identify latency bottlenecks, understand service dependencies, and debug errors. Tools: Jaeger, Zipkin."],
  ["Microservices", "What is the difference between logging and tracing?", "logging-vs-tracing", "Compare the two.", "Logging records discrete events (e.g., errors, state changes) at a point in time. Tracing tracks the flow of a request across services, showing the sequence and timing of operations. They are complementary."],
  ["Microservices", "What is a correlation ID and how is it used?", "correlation-id", "Explain request tracking.", "A correlation ID is a unique identifier generated for each request and propagated across all services. It is used to correlate logs and traces from different services to debug a single user request."],
  ["Microservices", "What is the difference between metrics and logs?", "metrics-vs-logs", "Compare the two.", "Metrics are numerical measurements over time (e.g., request count, latency) used for monitoring and alerting. Logs are textual records of events used for debugging and auditing. Metrics are aggregated; logs are detailed."],
  ["Microservices", "What is the role of a dashboard in microservices observability?", "dashboard-observability", "Explain visualization.", "Dashboards visualize key metrics and SLIs (e.g., latency, error rates, throughput) in real-time. They provide a high-level overview of system health and are used by operations teams to monitor the system."],
  ["Microservices", "What is the difference between black-box and white-box monitoring?", "black-white-box-monitoring", "Explain the two approaches.", "Black-box monitoring observes the system from outside, simulating user behavior (e.g., synthetic checks). White-box monitoring collects internal metrics (e.g., JVM heap, request counts) to understand system health."],
  ["Microservices", "What is an SLI, SLO, and SLA?", "sli-slo-sla", "Define the terms.", "SLI (Service Level Indicator): a metric measuring service performance (e.g., latency). SLO (Service Level Objective): a target for an SLI (e.g., 99.9% of requests < 200ms). SLA (Service Level Agreement): a formal agreement with the customer, often with penalties for violations."],
  ["Microservices", "How do you implement health checks in microservices?", "health-checks", "Explain endpoints.", "Health check endpoints (e.g., `/health`, `/readiness`, `/liveness`) are exposed by each service. Orchestrators (Kubernetes) use these to determine if a service is ready to receive traffic (readiness) or should be restarted (liveness)."],

  // ==================== DEPLOYMENT & INFRASTRUCTURE (Medium) ====================
  ["Microservices", "What is a container and how does it help microservices?", "container-microservices", "Explain containerization benefits.", "Containers package an application with its dependencies, providing isolation and consistency across environments. They enable lightweight, fast deployment, which is essential for microservices, and are often orchestrated by Kubernetes."],
  ["Microservices", "What is Kubernetes and how does it orchestrate microservices?", "kubernetes-microservices", "Explain the orchestration platform.", "Kubernetes automates the deployment, scaling, and management of containerized applications. It provides service discovery, load balancing, self-healing (restarting failed containers), and rolling updates, making it the standard for running microservices."],
  ["Microservices", "What is a Pod in Kubernetes?", "pod-kubernetes", "Define the smallest deployable unit.", "A Pod is the smallest deployable unit in Kubernetes. It can contain one or more containers that share networking and storage. In microservices, each service typically runs in its own Pod."],
  ["Microservices", "What is the difference between a Deployment and a StatefulSet in Kubernetes?", "deployment-vs-statefulset", "Compare the controllers.", "Deployment is used for stateless applications; it manages rolling updates and scaling. StatefulSet is for stateful applications; it provides stable network identities and persistent storage."],
  ["Microservices", "What is a Service in Kubernetes and what are its types?", "kubernetes-service", "Explain service types.", "A Service provides a stable IP and DNS name for a set of Pods. Types: ClusterIP (internal), NodePort (exposed on node port), LoadBalancer (cloud LB), and Ingress (HTTP routing)."],
  ["Microservices", "What is a ConfigMap and a Secret in Kubernetes?", "configmap-secret", "Explain configuration management.", "ConfigMap stores non-sensitive configuration data. Secret stores sensitive data (e.g., passwords) in an encoded format. They decouple configuration from the container image."],
  ["Microservices", "What is the difference between Blue-Green and Canary deployment?", "blue-green-vs-canary", "Compare the strategies.", "Blue-Green: two identical environments (blue and green); traffic is switched after validation. Canary: rollout to a small subset of users, then gradually increase. Canary is more gradual and reduces risk."],
  ["Microservices", "What is a rolling update in Kubernetes?", "rolling-update", "Explain gradual updates.", "A rolling update gradually replaces old Pods with new ones, ensuring zero downtime. It can be controlled by parameters like `maxSurge` and `maxUnavailable`."],
  ["Microservices", "What is the role of a service mesh in microservices?", "service-mesh", "Explain the infrastructure layer.", "A service mesh (e.g., Istio, Linkerd) is a dedicated infrastructure layer for service-to-service communication. It provides features like traffic management, security (mTLS), and observability via sidecar proxies, offloading these concerns from the application."],
  ["Microservices", "What is the difference between a service mesh and an API Gateway?", "service-mesh-vs-api-gateway", "Compare their roles.", "An API Gateway handles external client-to-service communication (east-west traffic). A service mesh handles internal service-to-service communication (north-south traffic). They can be used together."],

  // ==================== TRANSACTION & DATA PATTERNS (Hard) ====================
  ["Microservices", "What is the Outbox pattern?", "outbox-pattern", "Explain reliable event publishing.", "The Outbox pattern ensures reliable message publishing in a transaction. The service writes the event to an 'outbox' table as part of the local database transaction. A separate process polls the outbox table and publishes the event to the message broker, ensuring at-least-once delivery."],
  ["Microservices", "What is the Transactional Outbox pattern and how does it solve dual-write problems?", "transactional-outbox", "Explain the pattern.", "Dual-write problem occurs when a service writes to a database and publishes an event. If one fails, data is inconsistent. The Transactional Outbox stores the event in the same database transaction, and a publisher asynchronously sends it, guaranteeing both or none."],
  ["Microservices", "What is the Eventual Consistency pattern?", "eventual-consistency", "Define the consistency model.", "Eventual consistency guarantees that, given enough time without updates, all replicas will converge to the same value. It is used in distributed systems to achieve high availability and is the foundation of many data consistency strategies in microservices."],
  ["Microservices", "What is the difference between a domain event and an integration event?", "domain-vs-integration-event", "Explain the two event types.", "A domain event is internal to a bounded context (service) and represents a change in state. An integration event is published to other services to notify them of changes. Integration events enable loose coupling."],
  ["Microservices", "What is the role of an event store in Event Sourcing?", "event-store", "Explain the event storage system.", "An event store is a database that stores events immutably. It is the source of truth in Event Sourcing. It supports appending events, querying events, and replaying them to reconstruct state."],
  ["Microservices", "How do you handle event ordering in a distributed system?", "event-ordering", "Explain ordering guarantees.", "Use a message broker that supports ordered partitions (e.g., Kafka) to preserve order within a partition. Use timestamps and sequence numbers. For cross-partition ordering, use a global ordering service."],
  ["Microservices", "What is the difference between a message and an event?", "message-vs-event", "Clarify the concepts.", "A message is a generic unit of communication that can be a command or a query. An event is a message that signifies something has happened (past tense). Events are the basis of event-driven architectures."],
  ["Microservices", "What is the Command pattern in the context of CQRS?", "command-pattern", "Explain write operations.", "A command is an operation that changes the state of the system (e.g., `CreateOrder`). In CQRS, commands are handled by the command model (write side). Commands should be idempotent."],
  ["Microservices", "What is the Query pattern in CQRS?", "query-pattern", "Explain read operations.", "A query retrieves data without changing state (e.g., `GetOrderDetails`). In CQRS, queries are handled by the query model (read side), which is optimized for fast reads and may use denormalized views."],
  ["Microservices", "What is the difference between a saga and a process manager?", "saga-vs-process-manager", "Compare the patterns.", "A saga is a sequence of local transactions with compensating actions. A process manager is a stateful component that orchestrates a business process across multiple services, handling events and deciding next steps. Process managers are often used to implement sagas in a choreographed way."],

  // ==================== RESILIENCY & FAULT TOLERANCE (Medium-Hard) ====================
  ["Microservices", "What is the Timeout pattern and why is it important?", "timeout-pattern", "Explain setting timeouts.", "A timeout defines how long a service will wait for a response before aborting. It prevents resources from being tied up indefinitely and helps avoid cascading failures."],
  ["Microservices", "What is the Deadline pattern?", "deadline-pattern", "Explain time limits.", "A deadline is a time limit for the entire request chain. It ensures that the system does not spend more time than allowed on a request, and it can propagate deadlines across services to enforce total time limits."],
  ["Microservices", "What is the Retry pattern with exponential backoff?", "retry-exponential-backoff", "Explain the retry strategy.", "Exponential backoff is a retry policy where the delay between attempts increases exponentially (e.g., 1s, 2s, 4s). It prevents thundering herd and gives the system time to recover."],
  ["Microservices", "What is the Fallback pattern?", "fallback-pattern", "Explain graceful degradation.", "The Fallback pattern provides an alternative response when a service fails (e.g., returning cached data or a default value). It improves user experience by not failing completely."],
  ["Microservices", "What is the Difference between circuit breaker and bulkhead?", "circuit-breaker-vs-bulkhead", "Compare the patterns.", "Circuit breaker prevents repeated calls to a failing service. Bulkhead isolates resources (e.g., thread pools) to prevent failure in one part from affecting others. They are complementary."],
  ["Microservices", "What is the Health Check pattern?", "health-check-pattern", "Explain service health endpoints.", "Health check endpoints expose the health status of a service (e.g., `/health`). They are used by load balancers and orchestrators to determine if a service is alive and ready to receive traffic."],
  ["Microservices", "What is the role of a service mesh in resilience?", "service-mesh-resilience", "Explain how service mesh helps.", "A service mesh can provide built-in resilience features like retries, timeouts, circuit breakers, and fault injection at the proxy level, without requiring application code changes."],
  ["Microservices", "What is a dead letter queue (DLQ) and why is it used?", "dlq", "Explain failure handling.", "A DLQ is a queue that stores messages that cannot be processed (e.g., due to errors). It prevents message loss and allows for later analysis and reprocessing."],
  ["Microservices", "How do you test resilience in microservices?", "test-resilience", "Explain chaos engineering.", "Use Chaos Engineering (e.g., Chaos Mesh, Gremlin) to inject failures (e.g., network latency, node crashes) in a controlled environment to test the system's resilience and validate that circuit breakers, retries, and fallbacks work correctly."],
  ["Microservices", "What is the difference between a hard timeout and a soft timeout?", "hard-vs-soft-timeout", "Explain the two types.", "A hard timeout aborts the request immediately after the time limit. A soft timeout logs a warning but allows the request to continue, useful for detecting slow operations without failing them."],

  // ==================== DESIGN SCENARIOS (Hard) ====================
  ["Microservices", "How would you design a notification service in microservices?", "design-notification-service", "Outline the design.", "It would be a separate service that receives events (e.g., user registration) and sends notifications via email, SMS, push. Use a message queue to decouple from other services. Use a template engine for message formatting. Store notification logs."],
  ["Microservices", "How would you design a distributed logging solution?", "design-distributed-logging", "Explain log aggregation.", "Each service logs structured JSON to stdout/stderr. Use a log shipper (Fluentd, Filebeat) to send logs to a central log store (Elasticsearch). Use Kibana for visualization. Ensure correlation IDs are included."],
  ["Microservices", "How would you design a payment processing system with microservices?", "design-payment-system", "Outline the architecture.", "Use a payment service that handles transactions, integrates with external payment gateways, and maintains idempotency keys. Use a saga to coordinate with order and inventory services. Use a circuit breaker for external gateways."],
  ["Microservices", "How would you design a shopping cart service?", "design-cart-service", "Explain the design.", "Use a stateless service that stores cart data in a cache (Redis) for fast reads. Use events to update inventory when a cart is checked out. Handle eventual consistency with order service."],
  ["Microservices", "How would you design a social media feed service?", "design-feed-service", "Explain feed aggregation.", "Use a fan-out-on-write approach: pre-compute feeds for active users and store them in a timeline database (Cassandra). Use a cache for hot data. Use asynchronous processing for posts to avoid blocking."],
  ["Microservices", "How would you design a recommendation service?", "design-recommendation-service", "Explain the approach.", "Offline batch processing (Spark) computes recommendations and stores them in a key-value store (Redis). Online service serves recommendations. Use A/B testing to evaluate different algorithms."],
  ["Microservices", "How would you design a distributed lock for a specific operation?", "design-distributed-lock", "Explain the implementation.", "Use Redis (Redlock) or ZooKeeper to acquire a lock. Store a unique identifier (owner) and a TTL. Use a watchdog (background process) to extend the lock if needed. Ensure safe release to avoid deadlocks."],
  ["Microservices", "How would you design a real-time analytics pipeline?", "design-analytics-pipeline", "Explain the architecture.", "Use a stream processing framework (e.g., Flink) to process events from Kafka. Aggregate metrics in a time-series database (e.g., InfluxDB) and push dashboards via WebSockets. Use a separate service for long-term storage."],
  ["Microservices", "How would you design a microservices architecture for an e-commerce platform?", "design-ecommerce-microservices", "Describe the high-level design.", "Services: Product, Order, Cart, Payment, Inventory, Shipping, User, Notification. Use an API Gateway, service discovery (Eureka), asynchronous communication for order processing (saga), and event-driven updates for inventory."],
  ["Microservices", "How would you design a multi-tenant microservices system?", "design-multi-tenant", "Explain tenant isolation.", "Use a separate database per tenant or schema per tenant. Use a tenant-aware routing mechanism (e.g., header-based) to direct requests to the correct tenant context. Ensure data isolation and security."],

  // ==================== ADDITIONAL ADVANCED TOPICS (Hard) ====================
  ["Microservices", "What is the difference between a service mesh and an API gateway?", "service-mesh-vs-api-gateway", "Compare their roles.", "An API Gateway handles external client-to-service communication (east-west traffic). A service mesh handles internal service-to-service communication (north-south traffic). They can be used together."],
  ["Microservices", "What is the difference between a sidecar and a daemon set in Kubernetes?", "sidecar-vs-daemonset", "Explain the two concepts.", "A sidecar is a container that runs alongside the main container in the same Pod, providing auxiliary functions. A DaemonSet ensures a copy of a Pod runs on every node, often used for logging agents or monitoring."],
  ["Microservices", "What is the difference between an ingress controller and a load balancer?", "ingress-vs-loadbalancer", "Compare the two.", "A load balancer (e.g., AWS ELB) distributes traffic at Layer 4 or 7. An Ingress controller manages HTTP/HTTPS routing to services based on hostnames and paths, providing more advanced routing rules."],
  ["Microservices", "What is the role of a service registry in service discovery?", "service-registry", "Explain the registration process.", "A service registry stores the network locations of service instances. Services register themselves (e.g., via health checks) and others query the registry to find them. It is the heart of client-side and server-side discovery."],
  ["Microservices", "What is the difference between client-side and server-side service discovery?", "client-vs-server-side-discovery", "Compare the two.", "Client-side discovery: the client queries the registry directly and chooses an instance. Server-side discovery: a load balancer queries the registry and forwards the request. Client-side is more decoupled; server-side is simpler for clients."],
  ["Microservices", "What is the role of the `config server` in microservices?", "config-server", "Explain centralized configuration.", "The config server provides externalized configuration to all services. It centralizes configuration, supports versioning, and allows changes without redeploying services. Spring Cloud Config is a common implementation."],
  ["Microservices", "What is the difference between a service and a deployment in Kubernetes?", "service-vs-deployment-kubernetes", "Explain the distinction.", "A Deployment manages the lifecycle of Pods (rolling updates, scaling). A Service exposes the Pods to the network with a stable IP and DNS name. They work together."],
  ["Microservices", "What is the difference between a rollout and a rollback in Kubernetes?", "rollout-vs-rollback", "Explain update management.", "A rollout is the process of updating a Deployment to a new version. A rollback reverts to a previous revision. Kubernetes keeps history, allowing easy rollbacks."],
  ["Microservices", "What is the role of a container runtime in microservices?", "container-runtime", "Explain the underlying technology.", "The container runtime (e.g., containerd, CRI-O) is responsible for starting, running, and stopping containers. It is the interface between Kubernetes and the OS."],
  ["Microservices", "What is the difference between a Docker image and a container?", "docker-image-vs-container", "Explain the distinction.", "A Docker image is a read-only template that contains the application and its dependencies. A container is a runnable instance of an image. Images are built once and run many times."],

  // ==================== MISCELLANEOUS (Medium) ====================
  ["Microservices", "What is the difference between a microservice and a nanoservice?", "micro-vs-nanoservice", "Clarify the terms.", "A nanoservice is an extremely small service, often with just one endpoint. It is considered an anti-pattern because it leads to excessive network overhead and complexity. Microservices are larger and more cohesive."],
  ["Microservices", "What is the difference between a service and a function in serverless?", "service-vs-function", "Explain the difference.", "A service is a long-running application that handles multiple requests. A function (serverless) is a short-lived execution unit that runs in response to events. Serverless is often used for event-driven tasks."],
  ["Microservices", "What is the role of distributed caching in microservices?", "distributed-caching", "Explain caching strategies.", "Distributed caching (e.g., Redis) is used to improve performance by storing frequently accessed data (session data, API responses). It can be shared across service instances to reduce database load."],
  ["Microservices", "What is the difference between a cache-aside and a read-through cache?", "cache-aside-vs-read-through", "Compare the patterns.", "Cache-aside: the application manages the cache (checks cache, if miss, queries DB and populates cache). Read-through: the cache itself is responsible for loading data from the DB when a miss occurs."],
  ["Microservices", "What is the difference between a write-through and write-behind cache?", "write-through-vs-write-behind", "Compare the patterns.", "Write-through: writes go to both cache and DB synchronously. Write-behind: writes go to cache, and writes to DB asynchronously. Write-behind improves write performance but risks data loss."],
  ["Microservices", "What is the role of a load balancer in microservices?", "load-balancer-role", "Explain traffic distribution.", "A load balancer distributes incoming traffic across multiple instances of a service to improve availability and performance. It can operate at Layer 4 (TCP) or Layer 7 (HTTP)."],
  ["Microservices", "What is the difference between a hardware and a software load balancer?", "hardware-vs-software-lb", "Compare the two.", "Hardware load balancers are physical appliances, expensive and scalable. Software load balancers (e.g., Nginx, HAProxy) are cheaper, more flexible, and often used in cloud environments."],
  ["Microservices", "What is the role of a reverse proxy in microservices?", "reverse-proxy", "Explain its function.", "A reverse proxy sits in front of services and forwards requests to them. It provides load balancing, caching, SSL termination, and security."],
  ["Microservices", "What is the difference between a gateway and a reverse proxy?", "gateway-vs-reverse-proxy", "Clarify the distinction.", "A reverse proxy is a component that forwards client requests to backend servers. An API gateway is a reverse proxy with additional capabilities like request transformation, rate limiting, and authentication."],
  ["Microservices", "What is the role of a service mesh in security?", "service-mesh-security", "Explain security features.", "A service mesh can enforce mTLS for service-to-service communication, provide access control, and serve as a policy enforcement point, improving security without changing application code."],

  // ==================== SCENARIO-BASED (Hard) ====================
  ["Microservices", "You have a service that is slow. How do you debug it?", "debug-slow-service", "Walk through the steps.", "1. Check logs for errors. 2. Check metrics (CPU, memory, latency). 3. Use distributed tracing to see where time is spent. 4. Check database queries and indexes. 5. Check external dependencies. 6. Scale up the service or optimize the code."],
  ["Microservices", "How do you handle a situation where a service fails and cannot process requests?", "handle-service-failure", "Explain recovery steps.", "1. Check health checks and logs. 2. Restart the service (Kubernetes self-healing). 3. If a dependency fails, use circuit breaker to fallback. 4. If the service is down, route to a fallback service or show a user-friendly error. 5. Investigate root cause and fix."],
  ["Microservices", "How do you ensure that a microservice is not a bottleneck?", "avoid-bottleneck", "Explain scaling and optimization.", "Monitor performance metrics; scale horizontally (add instances); optimize database queries; use caching; implement asynchronous processing; and use a circuit breaker to handle overloads."],
  ["Microservices", "You need to introduce a new service. How do you plan it?", "plan-new-service", "Outline the planning steps.", "1. Define the bounded context and domain model. 2. Design the API (REST/gRPC). 3. Choose database and storage. 4. Define events for communication. 5. Plan deployment and CI/CD. 6. Consider observability (logs, metrics, tracing)."],
  ["Microservices", "How do you handle a database migration across multiple services?", "db-migration-across-services", "Explain phased migration.", "1. Add new columns/tables without removing old ones. 2. Deploy services that can read both old and new schemas. 3. Migrate data in batches. 4. After validation, remove old columns. Ensure backward compatibility at each step."],
  ["Microservices", "A service is sending too many requests to another service, causing overload. How do you fix it?", "handle-overload", "Explain mitigation strategies.", "1. Implement rate limiting at the client side. 2. Use a circuit breaker on the caller to stop requests if the service is slow. 3. Scale the receiving service. 4. Use a message queue to decouple. 5. Use caching to reduce requests."],
  ["Microservices", "How do you maintain API versioning in microservices?", "api-versioning-microservices", "Explain strategies.", "Use URL versioning (e.g., `/v1/orders`), header versioning (`Accept-Version: v1`), or query parameter versioning. Ensure backward compatibility by supporting multiple versions temporarily."],
  ["Microservices", "How do you test microservices effectively?", "test-microservices", "Explain testing strategies.", "Use unit tests for individual services, contract tests (e.g., Pact) for API compatibility, integration tests with test containers, and end-to-end tests for critical flows. Automate tests in CI/CD."],
  ["Microservices", "How do you monitor microservices in production?", "monitor-microservices-prod", "Describe monitoring setup.", "Use Prometheus for metrics, Grafana for dashboards, ELK stack for logs, and Jaeger/Zipkin for distributed tracing. Set up alerts based on SLOs. Use health checks and service discovery."],
  ["Microservices", "What is the role of a service mesh in canary deployments?", "service-mesh-canary", "Explain traffic splitting.", "A service mesh can split traffic between different versions of a service (e.g., 90% to v1, 10% to v2) for canary deployments. It can also collect metrics on the canary version to validate."],
  ["Microservices", "How do you handle rollback of a service deployment?", "rollback-microservices", "Explain rollback strategies.", "Use Kubernetes rollback (revert to previous revision). If using blue-green, switch back to the old environment. In canary, stop the canary and shift all traffic to the stable version. Ensure rollback is quick and safe."],
  ["Microservices", "What is the difference between a circuit breaker and a health check?", "circuit-breaker-vs-health-check", "Compare the two.", "A health check determines if a service is alive. A circuit breaker is a client-side pattern that decides whether to attempt calls to a service based on recent failures. They are complementary."],
  ["Microservices", "How do you ensure idempotency in a microservice API?", "idempotency-api", "Explain implementation.", "Use idempotency keys: the client generates a unique key for each operation, which the service stores (e.g., in the database). If the same key is seen again, the service returns the previous result without performing the operation again."],
  ["Microservices", "How do you handle network latency between services?", "handle-network-latency", "Explain strategies.", "Use connection pooling, keep-alive connections, and use efficient serialization (e.g., Protocol Buffers). Deploy services close to each other (same region). Use caching and asynchronous communication where possible."],
  ["Microservices", "What is the role of a sidecar proxy in microservices?", "sidecar-proxy", "Explain the proxy pattern.", "A sidecar proxy (e.g., Envoy) runs alongside a service and handles all network communication. It provides features like traffic management, security (mTLS), and observability, offloading these from the application."],
  ["Microservices", "How do you handle distributed tracing in a microservices environment?", "distributed-tracing-implementation", "Explain the implementation.", "Generate a Trace ID at the entry point and propagate it in HTTP headers (e.g., `X-B3-TraceId`). Each service adds its own Span ID and sends spans to a collector (e.g., Jaeger). Use an instrumented client or a service mesh for automatic injection."],
  ["Microservices", "What is the role of a config map in Kubernetes?", "configmap-role", "Explain configuration.", "A ConfigMap stores configuration key-value pairs. It is injected into containers as environment variables or mounted as files, allowing configuration changes without rebuilding images."],
  ["Microservices", "What is the difference between a secret and a configmap in Kubernetes?", "secret-vs-configmap", "Compare the two.", "A ConfigMap is for non-sensitive data. A Secret is for sensitive data (e.g., passwords, tokens). Secrets are base64-encoded and can be encrypted at rest. Secrets have stricter access controls."],
  ["Microservices", "How do you handle cross-cutting concerns (logging, monitoring) in microservices?", "cross-cutting-concerns", "Explain standardization.", "Use a service mesh or sidecar proxies for consistent logging and monitoring. Use centralized logging and monitoring tools. Use a common logging library that includes correlation IDs. Standardize metrics."],
  ["Microservices", "What is the role of an event-driven architecture in microservices?", "event-driven-architecture", "Explain decoupling.", "Event-driven architecture uses events to communicate between services. It decouples services, allowing them to react to changes asynchronously. It is used for eventual consistency, real-time updates, and building reactive systems."]
] as const;



const prisma = new PrismaClient();

const buildWhyInterviewersAsk = (question: string, shortDescription: string) =>
  `Interviewers ask this to check whether you can explain Microservices concepts clearly and connect them to practical engineering decisions. ${shortDescription} A strong response should address the purpose, the relevant trade-offs, and how you would verify the result rather than reciting a command or definition.`;

const buildCommonMistakes = (question: string) => [
  `Giving a memorized definition without explaining how it applies to: ${question}`,
  "Listing Microservices commands without explaining the safety, performance, or operational trade-off.",
  "Ignoring security boundaries, persistence, failure handling, or how the solution would be tested.",
];

async function main() {
  const category = await prisma.category.upsert({
    where: { slug: "microservices" },
    update: { name: "Microservices", group: "Technology", description: "Microservices interview questions." },
    create: { name: "Microservices", slug: "microservices", group: "Technology", description: "Microservices interview questions." },
  });
  const subcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: category.id, slug: "microservices" } },
    update: {},
    create: { name: "Microservices", slug: "microservices", categoryId: category.id },
  });

  for (let topicIndex = 0; topicIndex < topics.length; topicIndex += 1) {
    const [, question, slug, shortDescription, sampleAnswer] = topics[topicIndex];
    const commonMistakes = buildCommonMistakes(question);
    const followUpQuestions = [
      topics[(topicIndex + 1) % topics.length][1],
      topics[(topicIndex + 2) % topics.length][1],
      topics[(topicIndex + 3) % topics.length][1],
    ];
    await prisma.interviewQuestion.upsert({
      where: { slug },
      update: {
        question,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["Microservices"],
        isPublished: true,
      },
      create: {
        question,
        slug,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["Microservices"],
        isPublished: true,
      },
    });
  }

  console.log(`Imported ${topics.length} Microservices questions.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());

export const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");