// ---- 200+ Python Interview Questions (Fresher to Advanced) ----
import { Difficulty, ExperienceLevel, InterviewType, PrismaClient } from "@prisma/client";

// ---- Categories ----
export const categories = [
  ["Python", "Python"]
] as const;

// ---- Topics ----
export const topics = [
  // ==================== BASICS (20) ====================
  ["Python", "What is Python and what are its main features?", "python-overview", "Define Python and list its key features.", "Python is a high-level, interpreted, dynamically typed programming language known for its readability and versatility. Key features: easy-to-learn syntax, extensive standard library, dynamic typing, automatic memory management (garbage collection), support for multiple paradigms (procedural, OOP, functional), and a large ecosystem of third-party libraries."],
  ["Python", "What is the difference between Python 2 and Python 3?", "python2-vs-python3", "Compare the two major versions.", "Python 3 is the future; Python 2 reached end-of-life in 2020. Key differences: print is a function in Python 3 (`print()`), integer division returns float in Python 3 (`/`), Unicode strings by default, range() returns an iterator (not list), and many syntax changes (except as, metaclasses). Always use Python 3 for new projects."],
  ["Python", "How is Python interpreted?", "python-interpreter", "Explain the execution model.", "Python is an interpreted language: source code is compiled to bytecode (.pyc) which is then executed by the Python Virtual Machine (PVM). The interpreter (CPython) reads, tokenizes, parses, compiles, and runs the bytecode. There are also alternative implementations like PyPy (JIT), Jython (Java), and IronPython (.NET)."],
  ["Python", "What is PEP 8 and why is it important?", "pep8", "Explain the style guide.", "PEP 8 is the Python Enhancement Proposal that provides coding conventions for Python code. It covers naming conventions, indentation (4 spaces), line length (79 characters), whitespace, and more. Following PEP 8 improves code readability and consistency across projects."],
  ["Python", "What are the built-in data types in Python?", "builtin-data-types", "List the main data types.", "Python's built-in types include: Numeric (int, float, complex), Sequence (list, tuple, range), Text (str), Mapping (dict), Set (set, frozenset), Boolean (bool), Binary (bytes, bytearray, memoryview), and NoneType."],
  ["Python", "What is the difference between a list and a tuple?", "list-vs-tuple", "Compare the two sequence types.", "Lists are mutable (can be modified after creation), tuples are immutable. Lists use square brackets `[]`, tuples use parentheses `()`. Tuples are generally faster and can be used as dictionary keys; lists cannot. Use tuples for fixed data."],
  ["Python", "What is a dictionary and how does it work?", "dict-data-type", "Explain dictionaries.", "A dictionary is an unordered collection of key-value pairs, implemented as a hash table. Keys must be immutable (e.g., strings, numbers, tuples). Dictionaries provide O(1) average time complexity for lookups, insertions, and deletions. They are used for fast data retrieval."],
  ["Python", "What is the difference between a set and a frozenset?", "set-vs-frozenset", "Compare set types.", "Sets are mutable, unordered collections of unique elements. Frozensets are immutable versions of sets. Frozensets can be used as dictionary keys; sets cannot. Both support set operations like union, intersection, difference."],
  ["Python", "What is the `None` keyword in Python?", "none-keyword", "Explain `None`.", "`None` is a singleton object representing the absence of a value. It is used as a default return value for functions that don't explicitly return anything. It is not equal to `False`, `0`, or empty containers. Use `is None` or `is not None` for comparisons."],
  ["Python", "What is the difference between `==` and `is`?", "equals-vs-is", "Compare equality and identity.", "`==` checks for value equality (content). `is` checks for object identity (whether two references point to the same object). For immutable objects, sometimes `is` may match due to interning, but use `==` for value comparison and `is` for `None` or singleton checks."],
  ["Python", "What is a variable in Python?", "variable-definition", "Explain Python variables.", "Variables are names that refer to objects in memory. Python is dynamically typed: variables do not have a fixed type; they can be reassigned to different types. Assignment creates a reference to an object, not a copy."],
  ["Python", "What is the `pass` statement?", "pass-statement", "Explain `pass`.", "`pass` is a null operation – it does nothing. It is used as a placeholder in syntactic constructs where code is required but not yet implemented (e.g., empty functions, classes, or loops)."],
  ["Python", "What is the difference between `range` and `xrange` in Python 2?", "range-vs-xrange", "Explain the difference (historical).", "In Python 2, `range` returned a list, while `xrange` returned an iterator (lazy). In Python 3, `range` behaves like `xrange` – it returns an iterable range object. Always use `range` in Python 3."],
  ["Python", "What are comments in Python and how are they written?", "python-comments", "Explain comment syntax.", "Single-line comments start with `#`. Multi-line comments can use triple quotes `'''` or `\"\"\"` but these are actually docstrings; they are not ignored by the interpreter like real comments. For true multi-line comments, use multiple `#` lines."],
  ["Python", "What is the `__name__` variable?", "name-variable", "Explain the special variable.", "`__name__` is a built-in variable that is set to `'__main__'` when the script is executed directly, otherwise it's set to the module's name. It is used to conditionally execute code only when the script is run as the main program."],
  ["Python", "What is the `if __name__ == '__main__'` idiom?", "main-idiom", "Explain the common pattern.", "This pattern allows a Python file to be both imported as a module and executed as a script. When the file is run directly, the code inside the block runs; when imported, it does not. It's used for testing or standalone functionality."],
  ["Python", "What is the difference between `break`, `continue`, and `return`?", "break-continue-return", "Compare loop control statements.", "`break` exits the nearest enclosing loop. `continue` skips the rest of the current iteration and proceeds to the next. `return` exits a function and optionally returns a value."],
  ["Python", "What is the use of the `enumerate` function?", "enumerate-function", "Explain enumeration.", "`enumerate(iterable, start=0)` returns an iterator of tuples (index, value) for each element. It's commonly used in loops to get both the index and value without manually maintaining a counter."],
  ["Python", "What is the `zip` function?", "zip-function", "Explain zipping.", "`zip(*iterables)` aggregates elements from multiple iterables into tuples. It stops when the shortest iterable is exhausted. Often used to iterate over multiple lists in parallel or to transpose data."],
  ["Python", "What are Python's basic operators?", "basic-operators", "List operator types.", "Operators: arithmetic (`+`, `-`, `*`, `/`, `//`, `%`, `**`), comparison (`==`, `!=`, `<`, `>`, `<=`, `>=`), logical (`and`, `or`, `not`), assignment (`=`, `+=`, etc.), membership (`in`, `not in`), identity (`is`, `is not`), and bitwise (`&`, `|`, `^`, `~`, `<<`, `>>`)."],

  // ==================== DATA STRUCTURES (20) ====================
  ["Python", "How do you create a list and what operations can you perform?", "list-operations", "Explain list creation and common operations.", "Lists: `my_list = [1, 2, 3]`. Operations: append, extend, insert, remove, pop, index, count, sort, reverse, slicing `[start:stop:step]`, and concatenation (`+`). Lists are mutable and ordered."],
  ["Python", "What is list comprehension and how is it used?", "list-comprehension", "Explain the concise syntax.", "List comprehension is a concise way to create lists: `[expression for item in iterable if condition]`. It is faster and more readable than manual loops. Example: `[x**2 for x in range(10) if x % 2 == 0]`."],
  ["Python", "How do you use tuples and what are their advantages?", "tuple-usage", "Explain tuple usage.", "Tuples are immutable sequences; use them for fixed data (e.g., coordinates, database records). Advantages: faster than lists, can be used as dictionary keys, provide data integrity (cannot be changed accidentally)."],
  ["Python", "What is dictionary comprehension?", "dict-comprehension", "Explain the concise syntax.", "Dictionary comprehension: `{key_expression: value_expression for item in iterable}`. Example: `{x: x**2 for x in range(5)}` creates a dict of squares."],
  ["Python", "How do you merge two dictionaries?", "dict-merge", "Explain merging.", "In Python 3.9+, use `{**dict1, **dict2}` or `dict1 | dict2`. In older versions, use `dict1.update(dict2)` (modifies in place) or `{**dict1, **dict2}`."],
  ["Python", "What is the difference between `del`, `pop()`, and `remove()` on lists?", "del-pop-remove", "Compare deletion methods.", "`del list[index]` removes by index. `list.pop(index)` removes and returns the item (default last). `list.remove(value)` removes the first occurrence of a value by value."],
  ["Python", "How do you copy a list?", "list-copy", "Explain copying.", "Shallow copy: `new_list = my_list.copy()` or `my_list[:]`. Deep copy: `import copy; new_list = copy.deepcopy(my_list)` to clone nested objects."],
  ["Python", "What is the `collections` module?", "collections-module", "Explain the module.", "The `collections` module provides specialized container datatypes: `Counter` (frequency), `defaultdict` (default values), `OrderedDict` (ordered dict), `namedtuple` (tuple with named fields), `deque` (double-ended queue), and `ChainMap` (multiple dicts as one)."],
  ["Python", "What is a `defaultdict` and how does it work?", "defaultdict", "Explain `defaultdict`.", "`defaultdict` is a subclass of dict that provides a default value for missing keys. You pass a factory function (e.g., `int`, `list`, `set`) to the constructor. When accessing a missing key, it creates the key with the default value."],
  ["Python", "What is a `Counter`?", "counter", "Explain `Counter`.", "`Counter` is a dict subclass for counting hashable objects. It provides methods like `most_common()`, `elements()`, and arithmetic operations (`+`, `-`, `&`, `|`). Useful for frequency counting."],
  ["Python", "What is a `deque` and when would you use it?", "deque", "Explain `deque`.", "`deque` (double-ended queue) is a thread-safe, memory-efficient sequence with O(1) appends/pops from both ends. It's faster than lists for queue/stack operations. Use it for FIFO/LIFO, sliding windows."],
  ["Python", "What is the difference between `sort()` and `sorted()`?", "sort-vs-sorted", "Compare the two.", "`sort()` is a list method that sorts the list in place and returns `None`. `sorted()` is a built-in function that returns a new sorted list from any iterable, leaving the original unchanged. Both accept `key` and `reverse`."],
  ["Python", "How do you handle missing keys in a dictionary?", "dict-missing-keys", "Explain ways to handle missing keys.", "Use `dict.get(key, default)` to return a default. Use `dict.setdefault(key, default)` to set the key if missing. Use `collections.defaultdict`. Or use `try/except KeyError`."],
  ["Python", "What is the difference between `tuple` and `list` in terms of memory?", "tuple-list-memory", "Explain memory efficiency.", "Tuples are smaller and faster than lists because they are immutable and have less overhead. Lists allocate extra capacity for future growth; tuples allocate exactly the required space."],
  ["Python", "What is the difference between `dict` and `OrderedDict`?", "dict-vs-ordereddict", "Compare ordered dicts.", "Before Python 3.7, `dict` did not preserve insertion order; `OrderedDict` did. In Python 3.7+, both preserve order, but `OrderedDict` provides additional methods like `move_to_end` and `popitem(last=False)`."],
  ["Python", "What is a `namedtuple`?", "namedtuple", "Explain namedtuple.", "`namedtuple` is a factory function that creates tuple subclasses with named fields. It combines the memory efficiency of tuples with readability. Example: `Point = namedtuple('Point', ['x', 'y'])`."],
  ["Python", "What is the `array` module?", "array-module", "Explain the array module.", "The `array` module provides a more memory-efficient array of basic types (e.g., `'i'` for signed int). It's like a list but with a fixed type. Useful for large numerical data."],
  ["Python", "What is the difference between shallow copy and deep copy?", "shallow-vs-deep-copy", "Explain the copy concepts.", "Shallow copy creates a new container object but populates it with references to the same elements as the original. Deep copy recursively copies all nested objects, creating completely independent copies. Use `copy.copy()` and `copy.deepcopy()`."],
  ["Python", "What is the use of `isinstance()` vs `type()`?", "isinstance-vs-type", "Compare the two.", "`isinstance(obj, class)` checks if `obj` is an instance of the class or a subclass. `type(obj)` returns the exact type. Use `isinstance` for flexibility with inheritance; `type` for exact type checks."],
  ["Python", "What is the `in` operator for containers?", "in-operator", "Explain membership testing.", "`in` checks if a value exists in a container (list, tuple, dict, set, string). For dict, it checks keys. Behind the scenes, it calls `__contains__`."],

  // ==================== CONTROL FLOW & FUNCTIONS (15) ====================
  ["Python", "What are the conditional statements in Python?", "conditional-statements", "Explain if/elif/else.", "Python uses `if`, `elif`, and `else` for conditional execution. Indentation defines blocks. There is no `switch` statement; use `if-elif-else` or dictionaries for multiple cases."],
  ["Python", "How do you write a `while` loop?", "while-loop", "Explain while loop.", "A `while` loop repeatedly executes a block as long as a condition is true. It's used when the number of iterations is not known in advance. Ensure the loop condition eventually becomes false to avoid infinite loops."],
  ["Python", "What is a `for` loop in Python?", "for-loop", "Explain for loop.", "The `for` loop iterates over an iterable (list, tuple, dict, string, etc.). It assigns each element to the loop variable. Use `range()` for numeric sequences. Python's `for` is a foreach-style loop."],
  ["Python", "How do you define a function in Python?", "function-definition", "Explain function syntax.", "Use `def function_name(parameters):` followed by indented body. Functions can return values with `return`; if no return, they return `None`. Parameters can have default values and can be positional, keyword, or variable-length."],
  ["Python", "What are default arguments in Python?", "default-arguments", "Explain default parameters.", "Default arguments are set in the function definition: `def greet(name='World'):`. Defaults are evaluated at function definition time, so mutable defaults (e.g., `def f(lst=[])`) can cause issues. Use `None` as a sentinel for mutable defaults."],
  ["Python", "What is the difference between `*args` and `**kwargs`?", "args-kwargs", "Explain variable-length arguments.", "`*args` collects positional arguments into a tuple. `**kwargs` collects keyword arguments into a dict. They allow functions to accept arbitrary number of arguments. Used in wrappers, decorators, and forwarding."],
  ["Python", "What is a lambda function?", "lambda-function", "Explain lambda.", "Lambda is an anonymous function defined using `lambda arguments: expression`. It can have only one expression and is used where a simple function is needed for a short period (e.g., in `sort(key=...)`)."],
  ["Python", "What is a decorator?", "decorator", "Explain decorators.", "A decorator is a function that takes another function as argument and extends its behavior without modifying it. It uses the `@decorator_name` syntax. Decorators are used for logging, timing, access control, caching, etc."],
  ["Python", "How do you write a decorator?", "decorator-example", "Show decorator implementation.", "A simple decorator: `def my_decorator(func): def wrapper(*args, **kwargs): # before; result = func(*args, **kwargs); # after; return result; return wrapper`. Use `@my_decorator` to apply."],
  ["Python", "What is a closure?", "closure", "Explain closures.", "A closure is a nested function that captures variables from its enclosing scope. It retains the environment even after the outer function returns. Closures are used to create function factories and for data hiding."],
  ["Python", "What is the difference between a function and a method?", "function-vs-method", "Compare the two.", "A function is a standalone block of code. A method is a function that is defined inside a class and is called on an instance (`obj.method()`). Methods automatically receive `self` as the first argument (or `cls` for classmethods)."],
  ["Python", "What is the `global` statement?", "global-statement", "Explain global variables.", "`global` declares a variable as global, allowing modification inside a function scope. Without `global`, assignment creates a local variable. Use global variables sparingly."],
  ["Python", "What is the `nonlocal` statement?", "nonlocal-statement", "Explain nonlocal variables.", "`nonlocal` is used inside nested functions to modify variables in the nearest enclosing scope (excluding global). It's used in closures to modify the captured variable."],
  ["Python", "What is recursion and what are its limitations in Python?", "recursion", "Explain recursion.", "Recursion is a function calling itself. Python has a recursion limit (default ~1000) to prevent stack overflow. Recursion can be elegant for tree traversal but is often slower than iteration due to function call overhead."],
  ["Python", "What are docstrings and how are they used?", "docstrings", "Explain documentation strings.", "Docstrings are string literals that appear as the first statement in a module, function, class, or method. They are accessible via `__doc__` and are used by tools like `help()`, Sphinx, and IDEs for documentation."],

  // ==================== OOP (20) ====================
  ["Python", "How do you define a class in Python?", "class-definition", "Explain class syntax.", "Use `class ClassName:` followed by methods. The `__init__` method is the constructor. Methods have `self` as the first argument (instance reference). Class attributes are defined at the class level."],
  ["Python", "What is `self` in Python classes?", "self-keyword", "Explain the `self` parameter.", "`self` refers to the current instance of the class. It is passed automatically when calling instance methods. You can name it anything, but `self` is convention. It allows accessing instance attributes and methods."],
  ["Python", "What is the `__init__` method?", "init-method", "Explain the constructor.", "`__init__` is a special method (constructor) called when an object is instantiated. It initializes instance attributes. It is not a true constructor but an initializer."],
  ["Python", "What is inheritance in Python?", "inheritance", "Explain inheritance.", "Inheritance allows a class (child) to derive attributes and methods from another class (parent). Use `class Child(Parent):`. Python supports multiple inheritance. Override methods by redefining them in child."],
  ["Python", "What is method overriding?", "method-overriding", "Explain overriding.", "Method overriding occurs when a child class defines a method with the same name as a parent class method, replacing its behavior. Use `super()` to call the parent method if needed."],
  ["Python", "What is `super()` and how is it used?", "super-function", "Explain `super()`.", "`super()` returns a proxy object that delegates method calls to a parent or sibling class. It is used to call parent class methods, especially in `__init__` to ensure proper initialization. It avoids hardcoding parent names."],
  ["Python", "What is multiple inheritance and what are the issues?", "multiple-inheritance", "Explain multiple inheritance.", "Multiple inheritance allows a class to inherit from more than one parent. The main issue is the diamond problem (method resolution order). Python uses C3 linearization (MRO) to resolve conflicts. Use `super()` carefully."],
  ["Python", "What is the Method Resolution Order (MRO) in Python?", "mro", "Explain MRO.", "MRO determines the order in which base classes are searched for methods. Python uses C3 linearization, which can be viewed via `ClassName.__mro__`. It ensures a consistent and monotonic order."],
  ["Python", "What are magic methods (dunder methods)? Give examples.", "magic-methods", "Explain magic methods.", "Magic methods are special methods with double underscores (e.g., `__init__`, `__str__`, `__add__`). They define behavior for built-in operations: `__str__` for `str()`, `__len__` for `len()`, `__eq__` for `==`, etc. They allow operator overloading."],
  ["Python", "What is `__str__` and `__repr__`?", "str-repr", "Explain the differences.", "`__str__` is used by `str()` and `print()` to produce a readable string. `__repr__` is used by `repr()` and is meant to be unambiguous (often used for debugging). If `__str__` is missing, Python falls back to `__repr__`."],
  ["Python", "What is the `@staticmethod` decorator?", "staticmethod", "Explain static methods.", "`@staticmethod` defines a method that does not receive `self` or `cls`. It's just a function inside a class, useful for utility functions that are logically related to the class but don't need instance or class data."],
  ["Python", "What is the `@classmethod` decorator?", "classmethod", "Explain class methods.", "`@classmethod` defines a method that receives the class (`cls`) as the first argument. It can modify class state (class variables). Often used as alternative constructors."],
  ["Python", "What is the difference between `@staticmethod` and `@classmethod`?", "static-vs-classmethod", "Compare the two.", "`@staticmethod` does not receive `self` or `cls`; it behaves like a normal function. `@classmethod` receives the class as first argument and can modify class-level data. Use classmethod for factory methods."],
  ["Python", "What are properties in Python?", "properties", "Explain `@property`.", "Properties allow you to define getter, setter, and deleter methods for an attribute, enabling controlled access. Use `@property` decorator on a method to make it a getter, and `@attribute.setter` to define a setter."],
  ["Python", "What is encapsulation in Python?", "encapsulation", "Explain encapsulation.", "Encapsulation is bundling data and methods within a class, hiding internal state. Python uses naming conventions: `_single_leading_underscore` for protected, `__double_leading_underscore` for name mangling (weak private). However, it's not truly private; it's a convention."],
  ["Python", "What is polymorphism in Python?", "polymorphism", "Explain polymorphism.", "Polymorphism means the ability to present the same interface for different data types. In Python, it's achieved through duck typing (if it walks like a duck...). Different classes can implement the same method names, and functions can work on any object that supports the required methods."],
  ["Python", "What are abstract classes and how are they implemented?", "abstract-classes", "Explain abstract base classes.", "Abstract classes are templates that cannot be instantiated. They define methods that must be implemented by subclasses. Use the `abc` module: `from abc import ABC, abstractmethod` and decorate methods with `@abstractmethod`."],
  ["Python", "What is composition in OOP?", "composition", "Explain composition.", "Composition is a design principle where a class contains instances of other classes, rather than inheriting from them. It promotes code reuse and flexibility (prefer composition over inheritance)."],
  ["Python", "What is the difference between `isinstance` and `issubclass`?", "isinstance-vs-issubclass", "Compare the two.", "`isinstance(obj, class)` checks if `obj` is an instance of the class (or a subclass). `issubclass(cls1, cls2)` checks if `cls1` is a subclass of `cls2`."],
  ["Python", "What are data classes (Python 3.7+)?", "dataclasses", "Explain dataclasses.", "`dataclasses` provide a decorator and functions for creating classes that are primarily containers for data. They auto-generate `__init__`, `__repr__`, `__eq__`, etc., reducing boilerplate. Example: `@dataclass class Point: x: int; y: int`."],

  // ==================== MODULES & PACKAGES (10) ====================
  ["Python", "How do you import a module in Python?", "import-module", "Explain import syntax.", "Use `import module_name`, `from module import something`, `import module as alias`. Modules are Python files. The import mechanism searches in `sys.path`."],
  ["Python", "What is the difference between a module and a package?", "module-vs-package", "Compare module and package.", "A module is a single Python file (`.py`). A package is a directory containing an `__init__.py` file (or namespace package) and multiple modules/subpackages. Packages allow hierarchical structuring."],
  ["Python", "What is the `__init__.py` file?", "init-py", "Explain `__init__.py`.", "`__init__.py` is executed when a package is imported. It can initialize the package, set `__all__`, and import submodules. In Python 3.3+, it's not strictly required but recommended for regular packages."],
  ["Python", "What is `sys.path` and how is it modified?", "sys-path", "Explain `sys.path`.", "`sys.path` is a list of directory paths where Python looks for modules. You can modify it by appending new paths (`sys.path.append('/path')`) or using environment variable `PYTHONPATH`."],
  ["Python", "What is the `__all__` variable?", "all-variable", "Explain `__all__`.", "`__all__` is a list of public objects that are imported when `from module import *` is used. It restricts which names are exported. Good practice to define it to avoid unintended exports."],
  ["Python", "What are namespace packages?", "namespace-packages", "Explain namespace packages.", "Namespace packages allow splitting a package across multiple directories. They do not contain `__init__.py`. They are used in large projects to distribute parts of a package separately. Supported via `pkgutil` or `importlib`."],
  ["Python", "How do you handle relative imports?", "relative-imports", "Explain relative imports.", "Relative imports use dots: `.` for current package, `..` for parent. They are used within packages to import sibling modules. Example: `from . import module` or `from ..subpackage import something`."],
  ["Python", "What is `pip` and how do you use it?", "pip", "Explain pip.", "`pip` is the package installer for Python. Use `pip install package`, `pip uninstall`, `pip freeze` (list installed). For development, use `pip install -e .` for editable installs."],
  ["Python", "What is a virtual environment?", "virtualenv", "Explain virtual environments.", "A virtual environment is an isolated Python environment with its own Python interpreter and libraries. It prevents dependency conflicts between projects. Use `venv` (built-in) or `virtualenv`. Commands: `python -m venv venv`, then `source venv/bin/activate`."],
  ["Python", "How do you create and install a Python package?", "create-package", "Explain packaging.", "Create a package with `setup.py` or `pyproject.toml`. Use `setuptools`. Install with `pip install .` (local) or `pip install -e .` (editable). Distribute via PyPI using `twine`."],

  // ==================== EXCEPTION HANDLING (10) ====================
  ["Python", "How do you handle exceptions in Python?", "exception-handling", "Explain try/except.", "Use `try` block for risky code, `except` to catch specific exceptions. Optionally, `else` (runs if no exception) and `finally` (always runs). Use `raise` to throw exceptions. Catch specific exceptions rather than broad `Exception`."],
  ["Python", "What is the `finally` clause?", "finally-clause", "Explain `finally`.", "`finally` block is always executed after `try` and `except`, regardless of whether an exception was raised. It is used for cleanup actions (closing files, releasing locks)."],
  ["Python", "What is the `else` clause in `try/except`?", "else-clause", "Explain `else`.", "`else` runs if the `try` block does not raise an exception. It is useful for code that should only run if no errors occurred, separating it from the `try` block."],
  ["Python", "How do you raise an exception?", "raise-exception", "Explain `raise`.", "Use `raise ExceptionType('message')` to raise an exception. You can also re-raise an exception using `raise` inside an `except` block without arguments."],
  ["Python", "What are the common built-in exceptions?", "builtin-exceptions", "List common exceptions.", "`SyntaxError`, `TypeError`, `ValueError`, `NameError`, `IndexError`, `KeyError`, `AttributeError`, `IOError` (now `OSError`), `ZeroDivisionError`, `ImportError`, `RuntimeError`."],
  ["Python", "What is the difference between `except` and `except Exception as e`?", "except-vs-except-exception", "Compare exception catching.", "`except:` catches all exceptions (including `KeyboardInterrupt` and `SystemExit`). `except Exception as e` catches only exceptions derived from `Exception` (excluding system exits). It's better to catch specific exceptions."],
  ["Python", "How do you create a custom exception?", "custom-exception", "Explain custom exceptions.", "Define a class that inherits from `Exception` (or a subclass). You can add attributes and methods. Example: `class MyError(Exception): pass`. Raise it with `raise MyError('message')`."],
  ["Python", "What is the `assert` statement?", "assert-statement", "Explain `assert`.", "`assert condition, message` checks if a condition is true; if false, it raises `AssertionError`. Used for debugging and testing. Can be disabled with `-O` flag."],
  ["Python", "What are the best practices for exception handling?", "exception-best-practices", "List best practices.", "Catch specific exceptions, don't suppress exceptions silently, use `finally` for cleanup, use custom exceptions for domain errors, and avoid using exceptions for control flow."],
  ["Python", "What is the `with` statement and how does it relate to exceptions?", "with-statement", "Explain context managers.", "`with` statement is used with context managers (e.g., file operations). It ensures that resources are properly acquired/released even if an exception occurs. It relies on `__enter__` and `__exit__` methods."],

  // ==================== FILE I/O (10) ====================
  ["Python", "How do you read a file in Python?", "file-read", "Explain reading files.", "Use `open('file.txt', 'r')` and `read()`, `readline()`, or `readlines()`. Better to use `with open(...) as f:` for automatic closure. Example: `with open('file.txt') as f: content = f.read()`."],
  ["Python", "How do you write to a file?", "file-write", "Explain writing files.", "Open with mode `'w'` (write), `'a'` (append), `'x'` (exclusive create). Use `write()` or `writelines()`. Example: `with open('file.txt', 'w') as f: f.write('Hello')`."],
  ["Python", "What is the difference between `read()` and `readline()`?", "read-vs-readline", "Compare reading methods.", "`read(size)` reads the entire file (or `size` bytes) as a single string. `readline()` reads the next line, including newline. `readlines()` returns a list of lines."],
  ["Python", "What is the `with` statement and why is it used for files?", "with-file", "Explain context managers for files.", "`with` ensures that the file is properly closed after the block, even if an exception occurs. It is the recommended way to handle files."],
  ["Python", "How do you work with JSON in Python?", "json-module", "Explain JSON handling.", "Use the `json` module: `json.loads()` (string to dict), `json.dumps()` (dict to string), `json.load()` (read from file), `json.dump()` (write to file)."],
  ["Python", "How do you read and write CSV files?", "csv-module", "Explain CSV handling.", "Use the `csv` module: `csv.reader()` and `csv.writer()`. For dicts, use `csv.DictReader` and `csv.DictWriter`. Also, use `pandas` for more complex data."],
  ["Python", "How do you handle binary files?", "binary-files", "Explain binary mode.", "Open with `'rb'` (read binary) or `'wb'` (write binary). Use `read()` and `write()` with bytes objects. Example: `with open('image.jpg', 'rb') as f: data = f.read()`."],
  ["Python", "What is the `os` module and how is it used for file operations?", "os-module", "Explain `os`.", "The `os` module provides operating system interfaces: `os.remove()`, `os.rename()`, `os.mkdir()`, `os.listdir()`, `os.path` for path manipulations, etc. For higher-level operations, use `pathlib`."],
  ["Python", "What is `pathlib` and how does it improve file handling?", "pathlib", "Explain `pathlib`.", "`pathlib` offers an object-oriented approach to path manipulation. It's more readable and cross-platform. Example: `Path('file.txt').read_text()`, `Path('dir').mkdir()`. Preferred over `os.path` in modern Python."],
  ["Python", "What is the `tempfile` module?", "tempfile", "Explain temporary files.", "`tempfile` creates temporary files and directories. It is useful for temporary data storage. Use `tempfile.TemporaryFile()` or `tempfile.mkdtemp()`."],

  // ==================== ADVANCED FEATURES (15) ====================
  ["Python", "What are iterators and how do they work?", "iterators", "Explain iterators.", "An iterator is an object implementing `__iter__()` and `__next__()`. It yields values one at a time. Iterators are used in `for` loops. Built-in iterators: list, tuple, dict, etc. You can create custom iterators."],
  ["Python", "What are generators?", "generators", "Explain generators.", "Generators are functions that use `yield` to produce a sequence of values lazily. They are iterators. They save memory by generating values on the fly. Use generator expressions: `(x**2 for x in range(10))`."],
  ["Python", "What is the difference between `yield` and `return`?", "yield-vs-return", "Compare the two.", "`return` terminates a function and returns a value. `yield` pauses the function, returns a value, and preserves state for next call. Generators can yield multiple times."],
  ["Python", "What are decorators used for besides functions?", "decorators-use", "Explain decorator applications.", "Decorators can be applied to functions, methods, classes, and even class definitions (class decorators). They are used for logging, timing, memoization, access control, validation, and more."],
  ["Python", "What is a context manager and how do you create one?", "context-manager", "Explain context managers.", "A context manager defines `__enter__` and `__exit__` methods. It's used with `with`. You can also use `@contextlib.contextmanager` to create one using a generator function with `yield`."],
  ["Python", "What is the `contextlib` module?", "contextlib", "Explain `contextlib`.", "`contextlib` provides utilities for working with context managers: `contextmanager` decorator, `closing`, `suppress`, `redirect_stdout`, `ExitStack` for combining context managers."],
  ["Python", "What are metaclasses in Python?", "metaclasses", "Explain metaclasses.", "Metaclasses are classes of classes. They define how a class behaves. The default metaclass is `type`. Metaclasses allow intercepting class creation, modifying class attributes, and implementing frameworks like ORMs. Advanced and rarely used."],
  ["Python", "What is the `__slots__` attribute?", "slots", "Explain `__slots__`.", "`__slots__` is a class attribute that restricts instance attributes to a fixed set, reducing memory usage and improving attribute access speed. It prevents the creation of `__dict__` for instances, saving memory."],
  ["Python", "What is the `@property` decorator and its use?", "property-decorator", "Explain property.", "`@property` turns a method into a read-only attribute. With `@setter`, you can define assignment behavior. Used for computed attributes, validation, and encapsulation."],
  ["Python", "What is the `functools` module?", "functools", "Explain `functools`.", "`functools` provides higher-order functions: `partial` (fix arguments), `lru_cache` (memoization), `wraps` (preserve metadata in decorators), `reduce`, `cmp_to_key`, etc."],
  ["Python", "What is the `itertools` module?", "itertools", "Explain `itertools`.", "`itertools` provides functions for efficient iteration: `chain`, `combinations`, `permutations`, `product`, `cycle`, `repeat`, `groupby`, `islice`, `takewhile`, etc. They are memory-efficient."],
  ["Python", "What is the `typing` module?", "typing-module", "Explain type hints.", "`typing` provides type hints for static analysis: `List`, `Dict`, `Optional`, `Union`, `Callable`, `TypeVar`, etc. Type hints improve code readability and enable tools like mypy to catch errors."],
  ["Python", "What are coroutines in Python?", "coroutines", "Explain coroutines.", "Coroutines are functions that can pause and resume execution, using `async/await` (asynchronous programming). They are used for concurrency with `asyncio`. Coroutines differ from generators by using `await` for I/O."],
  ["Python", "What is the `asyncio` module?", "asyncio", "Explain asyncio.", "`asyncio` is a library for asynchronous I/O using coroutines. It allows writing concurrent code using `async`/`await`. It's event-driven and suitable for I/O-bound tasks (networking, web servers)."],
  ["Python", "What are the differences between threading, multiprocessing, and asyncio?", "concurrency-comparison", "Compare concurrency models.", "Threading (concurrent) is for I/O-bound tasks, uses GIL (CPython), and is suitable for light concurrency. Multiprocessing (parallel) is for CPU-bound tasks, uses separate processes, bypasses GIL. Asyncio (concurrent) is for high-level I/O, event-driven, and single-threaded with coroutines."],

  // ==================== CONCURRENCY (15) ====================
  ["Python", "What is the Global Interpreter Lock (GIL)?", "gil", "Explain the GIL.", "The GIL is a mutex that protects access to Python objects, preventing multiple threads from executing Python bytecode simultaneously in CPython. It simplifies memory management but limits parallelism for CPU-bound tasks. It does not affect I/O-bound tasks much."],
  ["Python", "How do you achieve concurrency in Python?", "concurrency-python", "Explain concurrency methods.", "Use threading (for I/O-bound), multiprocessing (for CPU-bound), asyncio (for high-level I/O), or concurrent.futures for a higher-level interface. Choose based on the task type."],
  ["Python", "What is the `threading` module?", "threading-module", "Explain threading.", "The `threading` module provides thread-based concurrency. It's suitable for I/O-bound tasks. However, due to the GIL, threads do not run in parallel for CPU-bound code. Use locks (`Lock`, `RLock`) to avoid race conditions."],
  ["Python", "What is the `multiprocessing` module?", "multiprocessing-module", "Explain multiprocessing.", "`multiprocessing` spawns separate processes, each with its own Python interpreter and memory space, bypassing the GIL. It allows true parallelism for CPU-bound tasks. Communication via queues, pipes, and shared memory."],
  ["Python", "What is the `concurrent.futures` module?", "concurrent-futures", "Explain `concurrent.futures`.", "`concurrent.futures` provides a high-level interface for asynchronously executing callables using threads (`ThreadPoolExecutor`) or processes (`ProcessPoolExecutor`). It simplifies concurrent execution with `submit` and `map`."],
  ["Python", "What is the difference between `Lock` and `RLock`?", "lock-vs-rlock", "Compare locks.", "`Lock` can be acquired once. `RLock` (reentrant lock) can be acquired multiple times by the same thread without deadlock. Use `RLock` when a thread may need to acquire the same lock again."],
  ["Python", "What is a `Semaphore`?", "semaphore", "Explain semaphore.", "A semaphore controls access to a shared resource by multiple threads. It maintains a counter. Acquire decrements, release increments. Used to limit concurrency (e.g., pool size)."],
  ["Python", "What is the `Queue` module?", "queue-module", "Explain `queue`.", "`queue` provides thread-safe queues: `Queue` (FIFO), `LifoQueue` (LIFO), and `PriorityQueue`. They are useful for communication between threads in producer-consumer patterns."],
  ["Python", "What is `asyncio` and how does it differ from threading?", "asyncio-vs-threading", "Compare asyncio and threading.", "Asyncio is single-threaded, uses an event loop, and is based on coroutines. It is efficient for many I/O-bound tasks with high concurrency. Threading uses OS threads, may have more overhead, and is better for blocking I/O."],
  ["Python", "What is the `async` and `await` syntax?", "async-await", "Explain async/await.", "`async def` defines a coroutine. `await` suspends a coroutine until the awaited result is ready. Used with `asyncio` for non-blocking I/O."],
  ["Python", "What is the `asyncio.run()` function?", "asyncio-run", "Explain running async code.", "`asyncio.run(main())` is the entry point for async programs. It creates an event loop, runs the coroutine, and closes the loop. Available in Python 3.7+."],
  ["Python", "What is a `Task` in asyncio?", "asyncio-task", "Explain tasks.", "`Task` is a coroutine wrapped in a future-like object that schedules the coroutine on the event loop. Use `asyncio.create_task()` to run coroutines concurrently."],
  ["Python", "What is a `Future` in Python?", "future", "Explain future.", "A `Future` is an object that represents a result that hasn't been computed yet. It's used in concurrent programming to get results asynchronously. In asyncio, `Future` is the base for `Task`."],
  ["Python", "How do you handle exceptions in asyncio?", "asyncio-exceptions", "Explain exception handling.", "Exceptions in coroutines propagate to the caller. Use `try/except` inside coroutines. When gathering tasks with `asyncio.gather()`, use `return_exceptions=True` to collect exceptions."],
  ["Python", "What is the difference between `asyncio` and `trio`?", "asyncio-vs-trio", "Compare async libraries.", "`trio` is an alternative async library with a more ergonomic API, stricter cancellation, and multi-tasking via nurseries. `asyncio` is built-in and more widely used."],

  // ==================== LIBRARIES & FRAMEWORKS (10) ====================
  ["Python", "What is NumPy and what are its key features?", "numpy", "Explain NumPy.", "NumPy is a library for numerical computing in Python. Key features: N-dimensional arrays, broadcasting, vectorized operations, linear algebra, Fourier transforms, random number generation. It is the foundation for pandas, SciPy, and machine learning libraries."],
  ["Python", "What is pandas and how is it used?", "pandas", "Explain pandas.", "pandas is a library for data manipulation and analysis. It provides DataFrame and Series data structures. Features: reading/writing data (CSV, Excel, SQL), data cleaning, grouping, merging, reshaping, and time-series functionality."],
  ["Python", "What is the difference between NumPy and pandas?", "numpy-vs-pandas", "Compare the two.", "NumPy provides multi-dimensional arrays and mathematical operations. pandas provides higher-level data structures (DataFrame) with labeled axes, more flexible indexing, and data manipulation tools. pandas is built on NumPy."],
  ["Python", "What is Django?", "django", "Explain the web framework.", "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. It includes an ORM, authentication, admin interface, and follows the MVC pattern (MTV). Batteries-included."],
  ["Python", "What is Flask?", "flask", "Explain Flask.", "Flask is a micro web framework for Python. It is lightweight and extensible, providing the essentials (routing, templates, request/response). It does not include an ORM or admin interface, but can be extended with extensions."],
  ["Python", "What is the difference between Django and Flask?", "django-vs-flask", "Compare the two.", "Django is full-stack, includes ORM, admin, auth, and more; suitable for large projects. Flask is minimal and flexible, allowing you to choose components; better for small projects, APIs, or microservices."],
  ["Python", "What is FastAPI?", "fastapi", "Explain FastAPI.", "FastAPI is a modern web framework for building APIs with Python 3.7+ using type hints. It is fast (like Node.js), supports automatic OpenAPI documentation, and validates request data with Pydantic. Asynchronous support."],
  ["Python", "What is the `requests` library?", "requests-library", "Explain requests.", "`requests` is a popular HTTP library for making HTTP requests in Python. It simplifies GET, POST, etc., handles sessions, cookies, SSL verification, and follows redirects."],
  ["Python", "What is SQLAlchemy?", "sqlalchemy", "Explain SQLAlchemy.", "SQLAlchemy is an ORM (Object Relational Mapper) for Python, providing a full suite of tools for working with databases. It offers both a low-level SQL toolkit and a high-level ORM, supporting multiple database backends."],
  ["Python", "What is Pytest?", "pytest", "Explain Pytest.", "Pytest is a testing framework for Python that makes it easy to write simple and scalable test cases. It supports fixtures, parameterization, assertions, plugins, and more. It's more concise than unittest."],

  // ==================== TESTING (10) ====================
  ["Python", "What is the `unittest` module?", "unittest", "Explain unittest.", "`unittest` is Python's built-in testing framework, inspired by JUnit. Use `unittest.TestCase` classes, `assert` methods (`assertEqual`, `assertTrue`, etc.), `setUp`/`tearDown`. Can run tests with `unittest.main()`."],
  ["Python", "What is Pytest and why is it popular?", "pytest-overview", "Explain Pytest.", "Pytest is a popular testing framework that simplifies test writing with less boilerplate than unittest. It uses plain `assert` statements, supports fixtures, parametrization, plugins, and detailed output."],
  ["Python", "How do you write a simple test in Pytest?", "pytest-example", "Show a test example.", "Define a function starting with `test_`. Use `assert` to check conditions. Example: `def test_addition(): assert 1+1 == 2`. Run with `pytest`."],
  ["Python", "What are fixtures in Pytest?", "pytest-fixtures", "Explain fixtures.", "Fixtures are functions that provide a fixed baseline for tests. They are decorated with `@pytest.fixture` and can be used to set up resources (database connections, temporary files). They can be autoused, scoped, and parametrized."],
  ["Python", "What is mocking in Python?", "mocking", "Explain mocking.", "Mocking is replacing parts of the system with fake objects to isolate the code under test. Use `unittest.mock` or pytest-mock. It allows patching functions, methods, or classes to control behavior and verify calls."],
  ["Python", "What is the `patch` decorator?", "patch-decorator", "Explain `patch`.", "`@patch('module.ClassName')` replaces the target with a mock object for the duration of the test. It can be used as a decorator or context manager. Useful for mocking external dependencies."],
  ["Python", "How do you test exceptions in Python?", "test-exceptions", "Explain exception testing.", "In unittest: `self.assertRaises(Error, func, *args)`. In Pytest: `with pytest.raises(Error): ...`."],
  ["Python", "What is code coverage and how do you measure it?", "coverage", "Explain coverage.", "Code coverage measures how much of the source code is executed during tests. Use `coverage.py` (`coverage run -m pytest` and `coverage report`). High coverage doesn't guarantee good tests but is a useful metric."],
  ["Python", "What is the difference between unit tests and integration tests?", "unit-vs-integration", "Compare test types.", "Unit tests test individual components in isolation (e.g., a function). Integration tests test the interaction between components (e.g., database, API). Both are important."],
  ["Python", "What is TDD (Test-Driven Development)?", "tdd", "Explain TDD.", "TDD is a development process where you write tests before writing the code. Red-Green-Refactor: write a failing test, write code to pass, then refactor. It leads to better design and fewer bugs."],

  // ==================== PERFORMANCE & OPTIMIZATION (10) ====================
  ["Python", "How do you optimize Python code performance?", "optimization", "Explain performance tuning.", "Use efficient algorithms and data structures. Profile with `cProfile` and `line_profiler`. Avoid global variables, use local variables for speed. Use list comprehensions over loops. Consider using built-in functions (`map`, `filter`) and `functools.lru_cache`."],
  ["Python", "What is profiling and how do you use it?", "profiling", "Explain profiling.", "Profiling measures execution time of code. Use `cProfile` (built-in) to get function call statistics. `pstats` for analysis. Also `line_profiler` for line-by-line. Visual tools: `snakeviz`."],
  ["Python", "What is the `timeit` module?", "timeit", "Explain `timeit`.", "`timeit` is used to measure the execution time of small code snippets. It avoids common pitfalls (garbage collection, system load). Use `timeit.timeit('code', number=1000)`."],
  ["Python", "How do you use `lru_cache` for memoization?", "lru-cache", "Explain `functools.lru_cache`.", "`@lru_cache(maxsize=128)` caches function results based on arguments. It automatically memoizes, improving performance for expensive repeated calls. Use for recursive functions (e.g., Fibonacci)."],
  ["Python", "What is the difference between `str` and `bytes`?", "str-vs-bytes", "Compare string and bytes.", "`str` represents Unicode text, `bytes` is a sequence of bytes. Converting: `s.encode('utf-8')` to bytes, `b.decode('utf-8')` to string. Use bytes for binary data, str for text."],
  ["Python", "How do you handle large files in Python without loading them entirely?", "large-files", "Explain handling large files.", "Use streaming: read in chunks (e.g., `for line in f:`). Use generators. For binary files, read with `read(size)`. Use memory-mapped files with `mmap`."],
  ["Python", "What is the `__slots__` optimization?", "slots-optimization", "Explain `__slots__`.", "`__slots__` reduces memory usage by preventing the creation of a `__dict__` per instance. It also speeds up attribute access. Use when you have many instances with fixed attributes."],
  ["Python", "How do you handle concurrency to improve performance?", "concurrency-performance", "Explain concurrency for performance.", "For I/O-bound tasks, use threading or asyncio. For CPU-bound tasks, use multiprocessing. Combine with pipelining or batching. Choose the right tool based on the bottleneck."],
  ["Python", "What is PyPy and how does it improve performance?", "pypy", "Explain PyPy.", "PyPy is an alternative Python implementation with a JIT (Just-In-Time) compiler. It can significantly speed up long-running programs compared to CPython. However, it may not support all C extensions."],
  ["Python", "What is the `Cython` language?", "cython", "Explain Cython.", "Cython is a superset of Python that allows compiling Python code to C extensions. It can optimize performance by adding static type declarations. Useful for CPU-intensive tasks."],

  // ==================== SECURITY (5) ====================
  ["Python", "What are common security vulnerabilities in Python applications?", "security-vulnerabilities", "List common vulnerabilities.", "Injection (SQL, command), XSS (if serving web), insecure deserialization (pickle), use of vulnerable dependencies, hardcoded secrets, insufficient logging, and improper input validation."],
  ["Python", "How do you avoid SQL injection in Python?", "sql-injection", "Explain prevention.", "Use parameterized queries with libraries like SQLAlchemy or psycopg2. Never concatenate user input into SQL strings. Use ORM features that automatically escape."],
  ["Python", "What is the danger of using `pickle`?", "pickle-dangers", "Explain pickle risks.", "`pickle` can execute arbitrary code during deserialization. Never unpickle data from untrusted sources. Use JSON or other safe serialization formats for untrusted data."],
  ["Python", "How do you securely store passwords in Python?", "password-storage", "Explain password hashing.", "Use `bcrypt`, `argon2`, or `werkzeug.security` to hash passwords. Use salts and a strong hashing algorithm. Never store plain text passwords."],
  ["Python", "What is the `secrets` module?", "secrets-module", "Explain `secrets`.", "The `secrets` module is designed for cryptographically strong random numbers. Use `secrets.token_bytes()` or `secrets.token_hex()` for secure tokens (passwords, reset links)."],

  // ==================== SCENARIO-BASED (20) ====================
  ["Python", "How would you read a large CSV file and process it efficiently?", "csv-large-file", "Explain efficient CSV processing.", "Use `pandas.read_csv()` with chunksize to iterate in chunks. Or use `csv` module with a generator to yield rows. Use vectorized operations in pandas for transformations. Avoid storing the entire file in memory."],
  ["Python", "How would you implement a simple web scraper in Python?", "web-scraper", "Explain web scraping.", "Use `requests` to fetch HTML, `BeautifulSoup` or `lxml` to parse. Handle pagination and delays. Use `robots.txt` and respect rate limits. For dynamic content, use `selenium`."],
  ["Python", "How would you connect to a database and perform CRUD operations?", "database-crud", "Explain database interaction.", "Use `sqlalchemy` ORM or raw SQL with `psycopg2` (PostgreSQL) or `sqlite3`. Use connection pooling. Use parameterized queries to prevent injection. For async, use `asyncpg` or `aiomysql`."],
  ["Python", "How would you implement a REST API using Flask?", "flask-api", "Explain Flask REST API.", "Use Flask with `flask-restx` or `flask-smorest` for validation and documentation. Define routes, handle request data, interact with database, return JSON responses. Use `jsonify`."],
  ["Python", "How would you implement a REST API using FastAPI?", "fastapi-api", "Explain FastAPI REST API.", "Use FastAPI with type hints. Define Pydantic models for request/response. Use dependency injection for DB sessions. Automatic OpenAPI docs. Async support."],
  ["Python", "How would you schedule a recurring task in Python?", "scheduling", "Explain task scheduling.", "Use `schedule` library, `APScheduler`, or `celery` for distributed. For simple tasks, use `time.sleep` in a loop. For production, use system cron (if lightweight) or Celery beat."],
  ["Python", "How would you debug a Python application?", "debugging", "Explain debugging techniques.", "Use `pdb` (built-in debugger) or `ipdb`. Use `logging` with different levels. Use `print` for quick checks. Use IDEs' debuggers (PyCharm, VS Code). Monitor logs and exceptions."],
  ["Python", "How would you handle time zones in Python?", "timezone-handling", "Explain timezone management.", "Use `datetime` with `pytz` or `zoneinfo` (Python 3.9+). Always work with UTC internally, convert to local time for display. Use `datetime.astimezone()`."],
  ["Python", "How would you implement logging in a Python application?", "logging", "Explain logging.", "Use the `logging` module. Configure with `basicConfig` or dict. Set levels, handlers (file, console), and formatters. Use `getLogger(__name__)` for module-level logging."],
  ["Python", "How would you read environment variables in Python?", "env-vars", "Explain reading env vars.", "Use `os.environ.get('VAR')`. For .env files, use `python-dotenv`. Use `pydantic` for validation."],
  ["Python", "How would you implement caching in Python?", "caching", "Explain caching.", "Use `functools.lru_cache` for function caching. Use `redis` or `memcached` for distributed caching. Use `cachetools` library for various cache policies."],
  ["Python", "How would you implement a retry mechanism for API calls?", "retry-logic", "Explain retries.", "Use `tenacity` library with `@retry` decorator. Specify exceptions, max attempts, delays (exponential backoff). Also use `requests` session with adapter for retries."],
  ["Python", "How would you parse command-line arguments in Python?", "command-line-args", "Explain argument parsing.", "Use `sys.argv` for simple. Use `argparse` for robust. Use `click` or `fire` for advanced. `argparse` supports positionals, options, subcommands, and help."],
  ["Python", "How would you create a Python package and publish it to PyPI?", "publish-package", "Explain packaging.", "Create `pyproject.toml` with `setuptools`. Write code, add tests, README. Build with `python -m build`. Upload with `twine upload dist/*`. Use `__init__.py`."],
  ["Python", "How would you handle concurrency in a web API with FastAPI?", "fastapi-concurrency", "Explain concurrency in FastAPI.", "FastAPI supports `async` endpoints for I/O-bound endpoints. Use `async` with `await` for database/HTTP calls. For CPU-bound tasks, offload to a thread pool (use `run_in_executor`) or separate process."],
  ["Python", "How would you implement authentication in a Django app?", "django-auth", "Explain Django authentication.", "Use Django's built-in `django.contrib.auth`. Use `User` model. Use decorators like `@login_required`. For token-based, use Django REST Framework's JWT or OAuth2."],
  ["Python", "How would you implement data validation in Python?", "data-validation", "Explain validation.", "Use `pydantic` for validation with type hints. Define models with field validators. Also use `dataclasses` with `__post_init__`. For web, use form validation in Django or WTForms."],
  ["Python", "How would you profile memory usage in Python?", "memory-profiling", "Explain memory profiling.", "Use `memory_profiler` with `@profile` decorator to track line-by-line memory. Use `tracemalloc` to track allocations. Use `objgraph` to find reference cycles."],
  ["Python", "How would you implement a binary search in Python?", "binary-search", "Explain binary search implementation.", "Use `bisect` module for sorted lists (`bisect_left`, `bisect_right`). Or implement manually: maintain low/high, compare middle, adjust. O(log n) time."],
  ["Python", "How would you handle circular imports in Python?", "circular-imports", "Explain handling circular imports.", "Refactor to avoid circularity. Use `import` inside functions or methods. Use `from ... import ...` at the end of the module. Use dependency injection. In some cases, use `importlib`."],
] as const;

const prisma = new PrismaClient();

const buildWhyInterviewersAsk = (question: string, shortDescription: string) =>
  `Interviewers ask this to check whether you can explain Python concepts clearly and connect them to practical engineering decisions. ${shortDescription} A strong response should address the purpose, the relevant trade‑offs, and how you would verify the result rather than reciting a command or definition.`;

const buildCommonMistakes = (question: string) => [
  `Giving a memorized definition without explaining how it applies to: ${question}`,
  "Listing Python commands without explaining the safety, performance, or operational trade‑off.",
  "Ignoring security boundaries, persistence, failure handling, or how the solution would be tested.",
];

async function main() {
  const category = await prisma.category.upsert({
    where: { slug: "python" },
    update: { name: "Python", group: "Technology", description: "Python interview questions." },
    create: { name: "Python", slug: "python", group: "Technology", description: "Python interview questions." },
  });
  const subcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: category.id, slug: "python" } },
    update: {},
    create: { name: "Python", slug: "python", categoryId: category.id },
  });

  for (let topicIndex = 0; topicIndex < topics.length; topicIndex += 1) {
    const [, question, slug, shortDescription, sampleAnswer] = topics[topicIndex];
    const commonMistakes = buildCommonMistakes(question);
    const followUpQuestions = [
      topics[(topicIndex + 1) % topics.length][1],
      topics[(topicIndex + 2) % topics.length][1],
      topics[(topicIndex + 3) % topics.length][1],
    ];
    await prisma.interviewQuestion.upsert({
      where: { slug },
      update: {
        question,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["Python"],
        isPublished: true,
      },
      create: {
        question,
        slug,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["Python"],
        isPublished: true,
      },
    });
  }

  console.log(`Imported ${topics.length} Python questions.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());

export const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");