import { PrismaClient, Difficulty, ExperienceLevel, InterviewType } from "@prisma/client";
import { articleSeeds } from "./article-seed";
const prisma = new PrismaClient();
const categories = [
  ["Software Developer", "Technology"], ["Android Developer", "Technology"], ["Java Developer", "Technology"], ["Kotlin Developer", "Technology"], ["Python Developer", "Technology"], ["JavaScript Developer", "Technology"], ["React Developer", "Technology"], ["Web Developer", "Technology"], ["SQL", "Technology"], ["QA Tester", "Technology"], ["Data Analyst", "Technology"], ["Sales", "Business"], ["Marketing", "Business"], ["Human Resources", "Business"], ["Customer Support", "Business"], ["Accountant", "Finance"], ["Banking", "Finance"], ["Finance", "Finance"], ["Fresher", "General"], ["Internship", "General"], ["HR", "General"], ["Behavioral", "General"], ["Situational", "General"],
] as const;
const topics = [
  // ---- EXISTING TOPICS (kept as-is) ----
  ["Software Developer", "How would you design a reliable service that processes customer requests?", "architecture", "Describe the trade-offs behind your design and how you would keep it observable.", "A strong answer starts with clear requirements, separated responsibilities, and failure handling. I would define the service boundaries, explain the data flow, and cover resilience choices like retries, idempotency, queueing, observability, and graceful degradation so the system stays reliable under pressure.", "I would start by clarifying the functional and non-functional requirements, then I would break the service into clear boundaries such as API handling, business logic, persistence, and monitoring. I would explain the chosen architecture in terms of reliability, scalability, and failure handling, and I would show how I would use retries, idempotent operations, structured logging, metrics, and alerting so the system stays observable under real traffic."],
  ["Android Developer", "How would you make an Android screen load quickly on a slow connection?", "performance", "Explain the measurements and improvements you would make before release.", "I would measure the current load time under throttled network conditions and focus on reducing the largest bottlenecks first. The main improvements would be lazy loading, caching, smaller payloads, pagination, skeleton states, and making sure the UI remains responsive while data is loading.", "I would first measure the screen load time and identify the bottlenecks using Android Studio profiling, network inspection, and frame rendering analysis. Then I would optimize by lazy loading expensive content, caching responses, reducing payload sizes, using pagination or incremental loading, showing skeleton states, and making sure the UI stays responsive even on weak connections. I would also validate the experience with network throttling so the fix is based on real user conditions rather than assumptions."],
  ["Java Developer", "What makes a Java application maintainable as its team grows?", "maintainability", "Connect design choices to testing and team communication.", "Maintainability comes from clean boundaries, clear conventions, and automated confidence. I would talk about modular design, dependency injection, focused classes, meaningful tests, and good documentation so the app stays understandable even as the team scales.", "A maintainable Java application is built around clear boundaries, consistent conventions, and strong test coverage. I would explain how small, focused classes, well-named methods, dependency injection, and modular design help the team reason about the system. I would also talk about automated tests, code reviews, and documentation so new engineers can learn the app quickly without breaking behavior. Long-term maintainability comes from making the code easy to understand, easy to change, and easy to verify."],
  ["Kotlin Developer", "When would you use a sealed class in Kotlin?", "language", "Give a practical example and acknowledge alternatives.", "I would use a sealed class when a value can only be one of a known set of related types, and every branch needs explicit handling. It is a good fit for state machines or API result models where exhaustive matching matters.", "I would use a sealed class when I need a closed set of related types and I want the compiler to help enforce exhaustive handling. For example, a sealed class representing API states such as Loading, Success, and Error makes it easier to handle every case in a when expression without missing branches. I would mention that enums are useful for fixed values, while sealed classes are better when each state carries different data or behavior. That makes the model both safer and more expressive."],
  ["Python Developer", "How do you investigate a Python function that has become slow?", "debugging", "Walk through a measured investigation rather than guessing.", "I would reproduce the issue and profile it first so I know whether the problem is CPU, memory, or I/O. After that, I would check algorithm complexity, repeated work, and database or network calls before making a fix.", "I would start by reproducing the slowdown and measuring the actual bottleneck with cProfile or timing logs so I know whether the issue is in CPU work, I/O, or database calls. Then I would examine algorithm complexity, test with representative data, and check for repeated work like nested loops or unnecessary conversions. If the issue is I/O-bound, I would look at network or file access; if it is CPU-bound, I would optimize data structures or processing strategy. I would validate the fix with a regression benchmark before closing the issue."],
  ["JavaScript Developer", "How do you prevent an asynchronous JavaScript feature from showing stale data?", "async", "Explain the race condition and the control you would introduce.", "I would prevent stale results by tracking request versions or request IDs and ignoring any response that is older than the latest update. That keeps the UI aligned with the latest user action instead of the last completed request.", "The key is to make each request or state update traceable and prevent older responses from overwriting newer ones. I would usually track a request ID or version, ignore stale results when a newer request has already started, and keep state updates centralized. In addition, I would design the UI so it handles loading and error states gracefully, and I would add tests for out-of-order responses so the bug does not return. The goal is to make the UI reflect the latest user intent rather than the last completed async task."],
  ["React Developer", "How do you decide where state should live in a React application?", "state", "Compare local, shared, and server state with a concrete example.", "I would keep state close to where it is used and only lift it when multiple components need to share it. Derived values should usually be computed rather than stored, so the app stays consistent and predictable.", "I keep state as close as possible to the component or feature that owns it, and I only lift it when multiple components need to share it. If the value can be derived from existing data, I avoid storing it separately. For example, form input state often belongs to the form component, while a shared dashboard filter belongs in a parent or a state management layer. I would also separate server state from UI state so I can use caching, loading, and error boundaries in a predictable way."],
  ["Web Developer", "What makes a web form accessible and resilient?", "accessibility", "Describe how you build and test it.", "Accessibility comes from clear labels, logical focus flow, and validation that helps users recover from mistakes. I would also test keyboard navigation and screen-reader announcements so the form works for real users in practice.", "A good form is understandable, keyboard-friendly, and resilient to real user error. I would make sure each field has a proper label, clear error messaging, focus management, and validation that works both on the client and server. I would also test keyboard navigation, screen-reader announcements, and failure cases such as empty submissions or invalid inputs. That gives users a clear path through the form and reduces support issues caused by confusing validation or inaccessible controls."],
  ["SQL", "How would you find and fix a slow SQL query?", "databases", "Explain the evidence you would gather before changing the query.", "I would inspect the execution plan, spot expensive operations, and check whether there is a missing index or poor filtering. After that, I would measure the change to confirm the performance improvement is real.", "I would start with the execution plan and query timing to see where the bottleneck is. Then I would check whether the query is missing an index, scanning too much data, or joining large tables inefficiently. I would look at filter selectivity, join order, and cardinality, then validate the fix by comparing query cost and runtime before and after. The important part is to use evidence and measure the improvement, not to guess at a query rewrite."],
  ["QA Tester", "How do you choose a useful regression test suite?", "quality", "Balance risk, coverage, maintenance, and feedback speed.", "I would prioritize scenarios that cover core user journeys and previously broken areas. A good regression suite catches real risk quickly without becoming brittle or expensive to maintain.", "I would prioritize areas that carry the most user or business risk, such as core flows, critical integrations, and recent bug fixes. A good regression suite should catch real defects quickly without becoming fragile or expensive to maintain. I would combine high-value automated checks with a few focused manual tests where human judgment matters. The goal is not test volume; it is confidence in the riskiest user journeys and the ability to detect breakage early."],
  ["Data Analyst", "How do you explain an unexpected change in a business metric?", "analysis", "Show how you separate data quality issues from real behavior.", "I would validate the data source and metric definition first, then break the trend into segments to isolate where the change is happening. That separates a genuine shift from an accidental reporting issue.", "I would first validate whether the metric definition or pipeline changed, because many surprises are caused by data quality issues. Then I would break the trend into meaningful segments such as geography, customer type, or product line to see where the shift is happening. I would compare against the expected baseline, look for external drivers, and communicate the likely root cause with evidence rather than intuition. That makes the explanation clearer and helps the business decide on an informed action."],
  ["Sales", "How would you prepare for a discovery call with a new prospect?", "discovery", "Show how preparation helps you listen instead of forcing a pitch.", "I would learn the company’s context and prepare a few thoughtful questions to uncover their real challenge. That lets me listen more and pitch less, which leads to a stronger conversation and a more relevant next step.", "I would research the company, understand its industry and likely pain points, and identify a few open-ended questions that help the prospect explain their situation. I would also prepare a clear outcome I want to achieve from the conversation, whether that is learning priorities, identifying urgency, or narrowing fit. The goal is to listen carefully, ask thoughtful questions, and then propose a practical next step that is relevant to their context rather than giving a generic sales pitch."],
  ["Marketing", "How do you decide whether a marketing campaign worked?", "measurement", "Describe a measurement plan before looking at results.", "I would decide the objective first and match it to the right metrics, then compare results to the baseline and any external factors. That turns the campaign review into a decision-making exercise instead of a vanity metric report.", "I would define the campaign objective first, such as traffic, lead quality, conversion, or brand awareness, and choose metrics that reflect that goal. Then I would compare performance against a baseline, look at attribution limitations, and check whether the results were driven by the campaign or by external factors. If the campaign met the objective, I would also review the cost efficiency and whether the target audience responded as expected. The point is to use measurement to make decisions, not just to report numbers."],
  ["Human Resources", "How would you improve an inconsistent hiring process?", "process", "Discuss fairness, speed, candidate experience, and evidence.", "I would standardize the evaluation criteria and train interviewers on the same rubric so decisions are more consistent and less subjective. That improves fairness and makes the process easier to improve over time.", "I would start by mapping the current hiring process and identifying where decisions vary between interviewers or teams. Then I would define a consistent rubric for each role, train interviewers on how to score candidates, and use structured questions to reduce bias and improve comparability. I would also review outcome data to see whether the process is predictive of success and whether candidates are having a frustrating experience. A strong process is fair, efficient, and based on evidence instead of personal preference."],
  ["Customer Support", "How do you respond when you cannot solve a customer issue immediately?", "service", "Demonstrate ownership without making promises you cannot keep.", "I would acknowledge the issue, explain the next step, and give a realistic timeline. That keeps the customer informed while still making the process feel supported and professional.", "I would acknowledge the issue, show empathy, and be transparent about what I know and what I am doing next. Then I would make a realistic commitment, such as a follow-up time or a clear escalation path, and document the customer context so the next person can continue without starting over. I would avoid promising a fix before I have the facts, but I would still make the customer feel supported and informed. Good service is about ownership, clarity, and consistency, not just speed."],
  ["Accountant", "How do you protect accuracy during a busy close?", "accuracy", "Explain controls that help you work quickly without cutting corners.", "I would put controls in place such as reconciliations, review checkpoints, and escalation rules so the process remains accurate even under time pressure. The key is to stay disciplined, not to rush.", "I would build a structured close process with reconciliations, review checkpoints, and clear ownership for each task. Before finalizing anything, I would check high-risk items such as journal entries, fixed assets, and unusual adjustments. I would use checklists, audit trails, and escalation thresholds so small errors do not slip through under time pressure. Accuracy comes from process discipline and review, not from working faster without controls."],
  ["Banking", "How do you evaluate risk in a customer-facing banking decision?", "risk", "Balance policy, evidence, customer needs, and escalation.", "I would look at the facts, the policy, and the customer context together, then escalate if the decision is outside my authority. That balances risk management with good customer service.", "I would start by collecting the relevant facts and checking whether the customer meets the policy requirements. Then I would assess the risk in context, including the transaction type, customer profile, and any signs of unusual activity or fraud. If the decision is outside my authority, I would escalate it with a clear recommendation and documentation. The best risk decisions balance compliance, customer needs, and good judgment, rather than relying on one rule in isolation."],
  ["Finance", "How would you explain a forecast variance to a non-finance partner?", "communication", "Turn the variance into a useful decision conversation.", "I would explain the headline, identify the main drivers, and connect the variance to the action needed. That makes the information useful instead of just technical.", "I would start with the headline: what changed, how big it was, and why it matters. Then I would break the variance into understandable drivers such as volume, pricing, mix, or timing, and explain which of those are within our control. I would end by connecting the variance to the business decision or action needed, such as pricing adjustment, capacity planning, or a revised target. The key is to make the numbers useful for the conversation, not just technically accurate."],
  ["Fresher", "Tell me about a project where you had to learn something quickly.", "learning", "Use a specific story from study, work, or personal projects.", "I would describe what I needed to learn, how I structured my learning, and what I built as a result. That shows initiative and a practical approach to learning under pressure.", "I would describe a project where I had to learn a new tool or concept quickly and explain how I structured my learning. For example, I might identify the key skills needed, read documentation, build a small prototype, and ask for feedback early. I would then talk about the challenge, how I adapted, and the result of my work. Good answers show initiative, a practical learning process, and the ability to turn unfamiliar material into useful output."],
  ["Internship", "How would you contribute during your first month on a new team?", "onboarding", "Show curiosity paired with useful action.", "I would learn the workflows, ask focused questions, and take on a small improvement that helps the team immediately. That shows both humility and usefulness.", "In my first month, I would focus on learning the business context, the team workflows, and the systems we rely on. I would also look for a small but valuable improvement, such as improving a document, automating a repetitive task, or documenting a process. I would ask targeted questions and make my progress visible so the team knows I am contributing without needing constant direction. That shows both humility and initiative, which are important in a new team."],
  ["HR", "How do you prepare for the question 'Why do you want this role?'", "motivation", "Connect your interests to the actual role rather than generic enthusiasm.", "I would explain why this role fits my goals and why the company or team is appealing. The answer should feel personal, but still grounded in real job fit and contribution.", "I would explain why the role fits my interests, strengths, and long-term goals, and I would connect that to what the company is doing. I would mention specific reasons the team or business appeals to me, such as the problem space, the product, or the way the team works. I would then explain what I believe I can contribute and what I hope to learn in the role. A strong answer is personal but grounded in real evidence, not just a generic statement about wanting to grow."],
  ["Behavioral", "Tell me about a time you received difficult feedback.", "feedback", "Show reflection without blaming the person who gave it.", "I would explain the situation, the feedback, and the behavior change that followed. That shows I can listen, improve, and stay professional under pressure.", "I would give a concise example of a situation where feedback was difficult, explain what I learned, and show how I adjusted my behavior. I would describe the context, the feedback itself, and the specific steps I took to improve, such as asking questions, changing my communication style, or adjusting my process. I would emphasize how I used the feedback constructively and what improved as a result. Good answers show self-awareness, accountability, and a real change in behavior."],
  ["Situational", "What would you do if two urgent stakeholders needed your time at once?", "prioritization", "Explain how you would make the trade-off visible.", "I would clarify impact and deadlines, communicate clearly with both sides, and make a decision based on business priority rather than personal preference. That keeps the stakeholders informed and the team aligned.", "I would first clarify the urgency, impact, and deadlines of each request so the trade-off is based on facts rather than assumptions. Then I would communicate to both stakeholders that I am reviewing priorities and propose a practical path forward, such as one short update now and a fuller response later. I would be transparent about the constraints and align on the most important task or dependency. That approach shows calm decision-making, respect for stakeholders, and ownership of the outcome."],
  ["Software Developer", "How would you review a pull request that works but is difficult to maintain?", "code review", "Balance correctness, risk, and respect for the author.", "I would focus on maintainability, clarity, and future change cost, while still respecting that the PR works. That helps the team keep the codebase healthy without being overly negative.", "I would call out the functional correctness first and then focus on maintainability concerns, such as unclear naming, duplicated logic, or hidden dependencies. I would explain why the issue matters in terms of future change cost, not just personal preference. I would separate blocking concerns from suggestions and phrase feedback in a constructive way so the author feels respected. A strong reviewer helps the team ship code that is correct, readable, and easier to support over time."],
  ["Android Developer", "How would you handle state restoration after an Android process is killed?", "lifecycle", "Distinguish transient UI state from durable application data.", "I would restore only the essential state and rely on persistent sources for anything that must survive process death. That gives recovery without duplicating or losing real data.", "I would separate transient screen state from durable business data and persist only what is necessary for recovery. Small UI details such as a selected tab or typed text can be restored through saved state, while more important data should come from an authoritative source like a database or server. I would also design the app to handle process death gracefully and test the restoration path under lifecycle changes. The goal is to restore a coherent state without duplicating or losing user input."],
  ["Java Developer", "What would you look for when diagnosing a memory leak in Java?", "diagnostics", "Describe tools and a narrowing strategy.", "I would look for long-lived references and retention paths, then confirm the issue with heap analysis. The right answer combines profiling tools, lifecycle review, and a clear fix for ownership.", "I would start by checking heap usage trends, garbage collection behavior, and thread activity to understand whether memory is growing steadily or in a specific flow. Then I would inspect object retention paths, look for long-lived references, and review whether caches or listeners are not being cleared. I would use heap dumps or profiling tools to confirm where memory is retained, then fix the ownership or lifecycle issue and add a regression check. A good answer shows methodical diagnosis and a focus on root cause rather than guessing."],
  ["Kotlin Developer", "How do coroutines change the way you structure asynchronous work?", "concurrency", "Explain structured concurrency in practical terms.", "Coroutines make async code easier to read, but the real win is structured cancellation and clear ownership. I would scope work to a lifecycle and handle exceptions intentionally so the app does not leak background tasks.", "Coroutines make asynchronous code read more like synchronous code, but they also require a clearer concept of scope and cancellation. I would organize work within a defined coroutine scope so it is cancelled with the parent lifecycle, and I would avoid leaking background work beyond the user session or request. I would also handle exceptions deliberately and keep blocking work off the main thread. In practice, coroutines help make concurrency easier to reason about when the lifecycle is designed correctly."],
  ["Python Developer", "How would you make a Python data-processing script safe to rerun?", "reliability", "Discuss partial failures and duplicate work.", "I would make the script idempotent and checkpoint progress so it can resume cleanly after failure. That is the difference between a fragile script and a reliable pipeline.", "I would make the script idempotent by writing output to a predictable location and checking whether a record or step has already been processed. I would also add checkpoints, validation around inputs, and clear logging so partial failures are easy to diagnose. If the process is writing to a database or file system, I would use transaction patterns or atomic writes to avoid inconsistent state. A rerunnable pipeline is critical in real data work because failures happen and the process has to recover cleanly."],
  ["JavaScript Developer", "How do you decide whether a browser task belongs in a web worker?", "browser", "Explain the cost of moving work away from the main thread.", "I would move CPU-heavy work to a worker when it would otherwise block the UI, but I would keep simpler tasks on the main thread because the communication overhead often outweighs the benefit.", "I would move work to a web worker when the task is CPU-intensive, does not need direct DOM access, and could block the main thread if left there. I would also consider the message-passing cost and whether the task is small or frequent enough to justify the complexity. If the work is mostly UI-related, I would keep it on the main thread to maintain responsiveness. The decision should be based on measuring the user-visible impact rather than moving everything off-thread by default."],
  ["React Developer", "How would you test a React component that depends on loading and error states?", "testing", "Focus on user-observable behavior.", "I would test the rendered UI states and the user interaction flows, not the internal implementation details. That ensures the component behaves correctly across the real states users experience.", "I would test the component through the UI, checking how it behaves when the data is loading, when it succeeds, and when it fails. I would verify that loading indicators appear, success content is rendered correctly, and retry or error actions are accessible to the user. I would avoid testing implementation details like internal state or method calls unless they are directly user-visible. Good component tests focus on behavior, reliability, and the user journey rather than the exact implementation."],

  // ---- NEW TOPICS (added to reach ~100 questions per category) ----

  // Software Developer (2 new)
  ["Software Developer", "How do you handle technical debt in a codebase?", "maintenance", "Explain how you prioritise and communicate technical debt.", "I would treat technical debt like any other backlog item: quantify its impact, align on priorities with the product team, and tackle it incrementally. The goal is to reduce future friction without halting feature delivery.", "I would start by categorising debt into maintenance overhead, scalability risks, and security issues. Then I would use metrics like code churn, defect density, or performance degradation to show the cost. I would propose a plan to refactor in small, testable chunks, always keeping the system green. Communication with stakeholders is key – I would frame it as investment in delivery speed, not just cleanup."],
  ["Software Developer", "How do you approach debugging a production issue?", "debugging", "Walk through your process from detection to resolution.", "I would first confirm the symptom, gather logs and metrics, then narrow down the root cause using hypothesis-driven investigation. The fix is always validated and monitored before closing.", "I would start by reproducing the issue in a non-production environment or reviewing logs and traces. I would use monitoring tools to pinpoint the time and service. Then I would form hypotheses and test them using structured logging or additional instrumentation. Once the root cause is found, I apply a fix, test it, and deploy with a rollback plan. I would also update runbooks and monitoring to detect similar issues earlier."],

  // Android Developer (3 new)
  ["Android Developer", "How do you manage app state across configuration changes?", "state", "Discuss strategies to preserve UI state without leaking.", "I would use ViewModels to hold UI-related data and handle configuration changes automatically. I would also save transient state with onSaveInstanceState for light data.", "I would rely on ViewModel and LiveData/StateFlow to retain data across rotations. For more complex state, I might use a combination of saved state module and persistent storage. I would avoid storing large objects or contexts in the ViewModel. I would also test orientation changes to ensure the UI restores correctly without flickering or data loss."],
  ["Android Developer", "How would you optimise battery usage in an Android app?", "performance", "Identify the biggest consumers and mitigation techniques.", "I would profile battery usage with Android Studio and focus on network calls, wake locks, and location updates. I would also minimise background work and use batching.", "I would use Battery Historian and the profiler to identify drains. Then I would reduce unnecessary network polling, use WorkManager for background jobs, and coalesce alarms. For location, I would choose appropriate accuracy and use passive updates. I would also avoid holding wake locks unnecessarily and use Doze mode optimisation. Finally, I would test battery impact over a typical usage scenario."],
  ["Android Developer", "How do you ensure your Android app is secure?", "security", "Cover data storage, network, and code protection.", "I would follow security best practices: encrypt sensitive data, use HTTPS with certificate pinning, protect against reverse engineering, and validate inputs.", "I would store sensitive data in EncryptedSharedPreferences or use Android Keystore for cryptographic keys. For networking, I would enforce HTTPS and implement certificate pinning. I would also obfuscate code with ProGuard/R8 and avoid logging sensitive info. I would regularly scan dependencies for vulnerabilities and perform security testing, including penetration testing for high-risk features."],

  // Java Developer (3 new)
  ["Java Developer", "How do you use design patterns in Java?", "design", "Give examples of patterns you use frequently.", "I use patterns like Singleton, Factory, and Observer to solve recurring problems. The key is to apply them only when they add value, not because they are patterns.", "I commonly use Factory for object creation, Singleton for shared resources, Observer for event handling, and Strategy for interchangeable algorithms. I also use Dependency Injection to manage dependencies. I would explain how these patterns improve testability and maintainability. I always consider whether a pattern is necessary – overuse can complicate the code."],
  ["Java Developer", "How do you handle concurrency in Java?", "concurrency", "Discuss threading, synchronisation, and modern alternatives.", "I prefer using the java.util.concurrent package and higher-level abstractions like Executors, Futures, and CompletableFuture. I avoid low-level synchronisation where possible.", "I would use ExecutorService to manage thread pools, and CompletableFuture for composing asynchronous tasks. For shared mutable state, I use concurrent collections like ConcurrentHashMap and atomic variables. I also consider using immutable objects and thread-safe design. I would avoid synchronised blocks unless necessary, and I always think about deadlock and performance implications."],
  ["Java Developer", "How do you test a Java application effectively?", "testing", "Cover unit, integration, and end-to-end testing.", "I would write unit tests with JUnit and Mockito, integration tests for external services, and end-to-end tests for critical flows. I aim for a test pyramid.", "I would start with unit tests for business logic, using mocking to isolate dependencies. For integration tests, I would use testcontainers or embedded databases. I also use contract tests for APIs. I would ensure tests are fast, deterministic, and run in CI. I would measure coverage but focus on meaningful scenarios. I would also incorporate performance and security testing as part of the pipeline."],

  // Kotlin Developer (3 new)
  ["Kotlin Developer", "How do you leverage Kotlin's null safety?", "safety", "Explain how you avoid NullPointerException in practice.", "I use nullable types and safe calls, and I apply early returns or the Elvis operator to handle nulls gracefully. I also use requireNotNull for invariants.", "I make use of Kotlin's type system to distinguish nullable and non-nullable types. I use safe call (?.), Elvis operator (?:), and let/run for scoping. I also use the !! operator sparingly and only when I am certain. I design APIs to return sealed classes or Result types to avoid null ambiguity. I also use lateinit and lazy for proper initialisation."],
  ["Kotlin Developer", "How do you use extension functions effectively?", "language", "Show examples where extensions improve readability.", "I use extensions to add utility functions to classes I cannot modify, like converting strings or formatting dates. They help keep code clean and expressive.", "I define extension functions for common operations, like `isValidEmail()` on String or `toPrettyDate()` on Long. I also use extension properties for lightweight accessors. I keep extensions in appropriate packages and avoid overusing them, as they can obscure the original class behaviour. They are great for DSLs and helper functions."],
  ["Kotlin Developer", "How do you handle errors in Kotlin?", "error-handling", "Compare exceptions, sealed classes, and Result types.", "I use exceptions for unexpected errors and sealed classes or Result for expected failures that need to be handled by the caller. I prefer functional approaches for clarity.", "I use try-catch for recoverable errors, but I also use sealed classes like `Result<T>` to represent success/failure. This forces callers to handle both cases. For coroutines, I use `try-catch` or `CoroutineExceptionHandler`. I avoid throwing exceptions for control flow. I also use `require`, `check`, and `assert` for preconditions."],

  // Python Developer (3 new)
  ["Python Developer", "How do you manage dependencies in a Python project?", "dependency", "Discuss virtual environments, requirements files, and lock files.", "I use `venv` or `poetry` to isolate environments, and I pin dependencies with a lock file to ensure reproducibility. I also periodically update dependencies.", "I start by creating a virtual environment (or using poetry/conda). I define dependencies in `pyproject.toml` (or `requirements.txt`) and generate a lock file (e.g., `poetry.lock`). I use `pip-tools` to compile requirements. I also separate dev and production dependencies. I run `pip-audit` or `safety` to check for vulnerabilities. This ensures consistent environments across teams."],
  ["Python Developer", "How do you write efficient Python code?", "performance", "Focus on profiling and algorithm choices.", "I profile first to find bottlenecks, then optimise loops, use built-in functions, and leverage libraries like NumPy for heavy computations. I also avoid premature optimisation.", "I use `cProfile` and `line_profiler` to measure performance. I then improve algorithmic complexity, use list comprehensions, and avoid expensive operations inside loops. I also consider using `functools.lru_cache` for repeated computations. For I/O, I use async or threading. I always measure before and after to confirm improvements."],
  ["Python Developer", "How do you structure a Python application for scalability?", "architecture", "Discuss modular design, configuration, and deployment.", "I use a modular architecture with clear separation of concerns, environment-aware configuration, and stateless components. I also use dependency injection and factory patterns.", "I structure code into modules (e.g., `domain`, `application`, `infrastructure`). I use environment variables for configuration. For scalability, I design stateless services and use message queues for background tasks. I also implement caching and database indexing. I use Docker and orchestration for deployment. I ensure logging and monitoring are in place for observability."],

  // JavaScript Developer (3 new)
  ["JavaScript Developer", "How do you handle errors in asynchronous JavaScript?", "async", "Compare callbacks, promises, and async/await.", "I use async/await with try-catch for clarity, and I handle errors at the appropriate level. I also use `.catch()` for promise chains.", "I prefer async/await because it makes error handling straightforward with try-catch. For promise chains, I attach a `.catch()` at the end. I also use `Promise.allSettled` for parallel operations where all results are needed regardless of failures. I ensure error messages are user-friendly and log the full error for debugging."],
  ["JavaScript Developer", "How do you optimise JavaScript performance?", "performance", "Identify common bottlenecks and improvements.", "I focus on reducing DOM manipulations, debouncing events, and using efficient data structures. I also use Web Workers for heavy computations.", "I use Chrome DevTools to profile and find bottlenecks. I reduce layout thrashing by batching DOM changes, use requestAnimationFrame for animations, and debounce scroll/resize events. I also use lazy loading for images and code splitting for large bundles. For data-heavy operations, I use Web Workers. I also consider using IndexedDB for local caching."],
  ["JavaScript Developer", "How do you manage state in a large JavaScript application?", "state", "Discuss different state management approaches.", "I use a centralised store like Redux or Zustand for global state, and local component state for UI-specific data. I separate server and client state.", "I would use a predictable state container for app-wide state (e.g., Redux with slices). For server state, I might use React Query or SWR to handle caching and synchronisation. I keep UI state like form inputs or toggles local to components. I also use context for theming or user session. I ensure state mutations are tracked and actions are logged for debugging."],

  // React Developer (3 new)
  ["React Developer", "How do you optimise React component rendering?", "performance", "Discuss memoisation, virtualisation, and reconciliation.", "I use React.memo, useMemo, and useCallback to prevent unnecessary re-renders. I also virtualise long lists and avoid inline functions in render.", "I wrap components with React.memo if they render often with same props. I use useMemo for expensive calculations and useCallback for stable functions. I also use the React DevTools profiler to identify slow components. For large lists, I use react-window or react-virtualized. I ensure keys are stable and unique."],
  ["React Developer", "How do you manage side effects in React?", "side-effects", "Compare useEffect, custom hooks, and external libraries.", "I use useEffect for synchronisation with external systems, but I keep effects focused and clean up. I also use custom hooks to encapsulate side effects.", "I use useEffect for data fetching, subscriptions, or DOM mutations. I always return a cleanup function. For complex data fetching, I use libraries like React Query or SWR to handle caching and retries. I also use custom hooks to reuse side-effect logic across components. I avoid putting too much logic in effects; I prefer to use event handlers for user-triggered actions."],
  ["React Developer", "How do you handle forms in React?", "forms", "Discuss controlled vs uncontrolled, validation, and submission.", "I usually use controlled components for form inputs, and I manage validation either with a library like Formik or React Hook Form. I handle submission with async/await.", "I prefer React Hook Form for performance and simplicity. I use controlled components with useState for simple forms. For validation, I use Zod or Yup schemas. I handle submit by preventing default, validating, and then sending data to an API. I also show loading states and error messages. I ensure accessibility with proper labels and aria attributes."],

  // Web Developer (3 new)
  ["Web Developer", "How do you ensure web security?", "security", "Cover common vulnerabilities and mitigation.", "I follow OWASP guidelines, use HTTPS, sanitise inputs, and implement CSRF protection. I also use Content Security Policy (CSP).", "I protect against XSS by escaping output and using CSP. For CSRF, I use tokens and SameSite cookies. I validate and sanitise all user inputs on server and client. I use HTTPS for all communications. I also keep dependencies updated and use security headers like HSTS. I perform regular security audits and penetration testing."],
  ["Web Developer", "How do you improve web performance?", "performance", "Focus on critical rendering path and resource optimisation.", "I optimise images, minify assets, use CDN, and implement lazy loading. I also use HTTP/2 and brotli compression.", "I measure performance with Lighthouse and WebPageTest. I optimise images with modern formats (WebP, AVIF) and use srcset. I minify and bundle CSS/JS, and use code splitting. I implement lazy loading for images and iframes. I also use preconnect and preload for critical resources. I ensure server response times are low by using caching and CDN."],
  ["Web Developer", "How do you handle cross-browser compatibility?", "compatibility", "Discuss testing strategies and polyfills.", "I use feature detection, polyfills for missing features, and test on multiple browsers. I also use CSS prefixes and a reset/normalize.", "I use tools like CanIUse and Babel to transpile modern JS. I add CSS prefixes with autoprefixer. I test on BrowserStack or Sauce Labs. I use feature detection (e.g., Modernizr) for missing APIs. I also ensure graceful degradation for older browsers. I keep a baseline of supported versions and test accordingly."],

  // SQL (3 new)
  ["SQL", "How do you design a database schema?", "design", "Discuss normalisation, indexing, and relationships.", "I start with an ER model, apply normalisation to reduce redundancy, and then add indexes based on query patterns. I also consider future scalability.", "I identify entities and relationships, then create tables with primary and foreign keys. I normalise to 3NF typically, but I may denormalise for performance. I choose appropriate data types. I design indexes on columns used in WHERE, JOIN, and ORDER BY. I also consider partitioning for large tables. I document the schema and maintain migration scripts."],
  ["SQL", "How do you handle database migrations?", "migrations", "Discuss version control and rollback strategies.", "I use migration tools like Flyway or Liquibase to version schema changes. I write both forward and rollback scripts and test them in CI.", "I store migration scripts in version control, each with a unique version number. I apply them in order in the target environment. I ensure that migrations are idempotent and can be rolled back safely. I also test migrations on a staging environment with production-like data. I have a process for zero-downtime migrations (e.g., adding columns without dropping)."],
  ["SQL", "How do you optimise complex queries?", "optimization", "Explain query tuning and plan analysis.", "I analyse the execution plan, look for full table scans or large sorts, and then add indexes or rewrite the query to use more selective filters.", "I start by examining the execution plan to identify costly operations. I look for missing indexes, inappropriate joins, or large sorting. I may rewrite the query using CTEs, subqueries, or temporary tables. I also consider materialised views for aggregated data. I test changes on a copy of production data and measure the performance improvement."],

  // QA Tester (3 new)
  ["QA Tester", "How do you write a test plan?", "planning", "Cover scope, resources, and exit criteria.", "I define the scope, test objectives, environment, and schedule. I prioritise features based on risk and user impact.", "I start by gathering requirements and identifying testable features. I define test levels (unit, integration, system). I list the test environments and required tools. I create a test schedule and assign resources. I also define entry and exit criteria. I ensure the plan is reviewed by stakeholders and updated as the project evolves."],
  ["QA Tester", "How do you automate testing?", "automation", "Discuss tool selection and framework design.", "I choose tools based on the application type (e.g., Selenium for web, Appium for mobile). I design a maintainable framework using Page Object Model.", "I evaluate tools by considering community support, language compatibility, and ease of integration with CI. I design a framework that separates test logic from page details (Page Object). I use data-driven testing and manage test data. I also ensure tests are stable, run in parallel, and produce clear reports. I prioritise automating regression tests and high-risk scenarios."],
  ["QA Tester", "How do you prioritise testing efforts?", "prioritization", "Balance risk, business value, and development velocity.", "I prioritise features that are critical to the business, have high complexity, or are frequently changed. I also consider user impact and legal/security requirements.", "I use risk-based testing: identify high-risk areas (complex logic, frequent changes, third-party integrations) and test them thoroughly. I also consider the business impact if a feature fails. I collaborate with developers and product owners to understand priorities. I allocate testing time accordingly, ensuring that high-value areas receive more attention."],

  // Data Analyst (3 new)
  ["Data Analyst", "How do you clean messy data?", "data-cleaning", "Describe a systematic approach to data cleaning.", "I start by exploring the data to identify missing values, outliers, and inconsistencies. I then apply standardisation, imputation, and validation.", "I use profiling tools to understand data quality. I handle missing values by imputation or removal based on context. I detect outliers using statistical methods. I standardise formats (dates, strings). I document all transformations. I also validate against business rules and ensure data types are correct. I repeat cleaning in cycles, often collaborating with data engineers."],
  ["Data Analyst", "How do you choose the right visualisation?", "visualization", "Match chart types to data and audience.", "I choose based on the message: comparisons use bar charts, trends use line charts, distributions use histograms, relationships use scatter plots. I consider the audience's technical level.", "I first define what I want to communicate: comparison, distribution, composition, or relationship. For comparing categories, I use bar charts. For time series, I use line charts. For composition, I use pie or stacked bars (but sparingly). For distribution, I use histograms or box plots. For relationships, I use scatter plots. I also consider using interactive dashboards for exploratory analysis. I ensure the visualisation is clear, labelled, and avoids clutter."],
  ["Data Analyst", "How do you communicate data insights to stakeholders?", "communication", "Tailor the message and use storytelling.", "I start with a clear summary of the key insight, then provide supporting evidence and context. I use visualisations to make it accessible.", "I focus on the business problem, not just the numbers. I structure my presentation with a narrative: context, analysis, findings, and recommendations. I use simple language and avoid jargon. I include visualisations that highlight the main points. I prepare for questions by having deeper data ready. I also follow up with a written summary."],

  // Sales (3 new)
  ["Sales", "How do you handle a price objection?", "objection-handling", "Explain your approach to value-based selling.", "I acknowledge the concern, restate the value, and then explore different pricing options or demonstrate ROI. I avoid discounting without justification.", "I first empathise with the prospect and ask clarifying questions to understand their budget constraints. Then I reiterate the value and ROI of our solution. I might offer flexible payment terms or a phased approach. I also discuss the cost of inaction. I never lower the price without receiving a concession in return, and I always maintain the perceived value."],
  ["Sales", "How do you build rapport with a prospect?", "rapport", "Discuss active listening and personalisation.", "I research the prospect and their company, find common ground, and listen actively to their concerns. I mirror their communication style.", "I do my homework before the call: read their LinkedIn, company news, and industry trends. During the conversation, I ask open-ended questions and listen more than I speak. I find points of mutual interest, like shared experiences or goals. I maintain a positive tone and use their name. I follow up with personalised messages that reference our conversation."],
  ["Sales", "How do you close a deal?", "closing", "Describe your closing techniques and timing.", "I look for buying signals and then ask for the commitment directly. I also use trial closes and handle final objections.", "I ensure all value propositions have been covered and the prospect has no unresolved questions. I use an assumptive close, like 'Shall I send over the contract?' or 'What's the next step in your approval process?'. I also use a choice-close, offering two options. If they hesitate, I ask about concerns. I always maintain a consultative approach, not pushy."],

  // Marketing (3 new)
  ["Marketing", "How do you measure brand awareness?", "brand", "Discuss metrics and methodologies.", "I use a combination of surveys (brand recall), social media mentions, search volume, and web traffic direct. I track trends over time.", "I conduct brand tracking studies with questions on aided/unaided recall. I monitor social listening for mentions and sentiment. I track branded search volume and direct traffic as proxies. I also look at share of voice in media. I set benchmarks and measure changes over quarterly periods, correlating with marketing activities."],
  ["Marketing", "How do you segment a target audience?", "segmentation", "Explain demographic, psychographic, and behavioural segmentation.", "I use a mix of demographic (age, income), psychographic (interests, values), and behavioural (purchase history, engagement) criteria to create meaningful segments for personalisation.", "I start by analysing customer data to identify patterns. I use cluster analysis for behavioural segments. I also create personas based on qualitative research. I prioritise segments by profitability and growth potential. I then tailor messaging and channels for each segment. I continuously test and refine segments based on campaign performance."],
  ["Marketing", "How do you evaluate the ROI of a marketing channel?", "roi", "Discuss attribution and cost calculations.", "I calculate ROI by comparing the revenue generated from a channel to its cost. I use multi-touch attribution to understand the channel's role in the conversion path.", "I track costs (ad spend, agency fees) and attribute revenue using models like last-click, linear, or data-driven attribution. I also consider incrementality testing to isolate the channel's true impact. I compare ROI across channels to allocate budget. I also look at customer lifetime value to assess long-term ROI."],

  // Human Resources (3 new)
  ["Human Resources", "How do you handle an employee conflict?", "conflict", "Discuss mediation and resolution steps.", "I would first speak with each party individually, then bring them together to find a mutually agreeable solution. I focus on facts and future behaviour.", "I start by creating a safe environment for each person to express their perspective. I use active listening and avoid assigning blame. I identify common goals and underlying interests. Then I facilitate a conversation with both parties, guiding them to agree on specific actions. I follow up to ensure the resolution is sustained. I also document the process for legal protection."],
  ["Human Resources", "How do you design a training program?", "training", "Cover needs assessment, content design, and evaluation.", "I would conduct a needs analysis to identify skill gaps, design interactive and practical content, and then measure effectiveness through feedback and performance metrics.", "I start by assessing the current skills and the desired outcomes through surveys and interviews with managers. I then set clear learning objectives. I design a blended program (e.g., e-learning, workshops, and on-the-job practice). I involve subject matter experts. After delivery, I measure reactions, learning, and application on the job using Kirkpatrick's model. I iteratively improve based on evaluation."],
  ["Human Resources", "How do you measure employee engagement?", "engagement", "Discuss surveys, retention, and performance.", "I use regular pulse surveys, measure participation in initiatives, and track turnover and productivity. I also conduct exit interviews.", "I administer annual or bi-annual engagement surveys with standardised questions (e.g., eNPS). I also use shorter pulse surveys for real-time feedback. I analyse turnover rates and reasons for leaving. I look at absenteeism and productivity metrics. I also conduct focus groups. I share results with leadership and co-create action plans to address gaps."],

  // Customer Support (3 new)
  ["Customer Support", "How do you de-escalate an angry customer?", "de-escalation", "Describe your communication approach.", "I remain calm, listen actively, empathise, and then offer a solution. I avoid taking it personally and focus on the issue.", "I start by using a calm and steady tone. I let the customer vent without interrupting. I acknowledge their feelings and repeat their issue to show understanding. I then take ownership and propose a clear next step. I avoid making excuses and focus on what I can do. I follow up to ensure satisfaction."],
  ["Customer Support", "How do you prioritise support tickets?", "prioritization", "Balance urgency and impact.", "I classify tickets by severity (e.g., system down vs. minor feature request) and customer impact (e.g., number of users affected). I then handle critical issues first.", "I use a priority matrix: impact (number of users affected) and urgency (business effect). Critical issues (e.g., payment failure) are escalated immediately. I also consider service level agreements (SLAs). I handle simple queries quickly to keep backlog low. I periodically review queues to ensure no high-impact tickets are missed."],
  ["Customer Support", "How do you gather customer feedback?", "feedback", "Discuss methods and analysis.", "I use surveys, follow-up emails, and social listening. I also analyse support interactions to identify common pain points.", "I send short post-interaction surveys (CSAT) and periodic NPS surveys. I also monitor social media and review sites. I analyse support ticket categories and keywords to spot trends. I hold focus groups with key customers. I compile feedback into reports and share with product teams to inform roadmap."],

  // Accountant (3 new)
  ["Accountant", "How do you handle discrepancies in financial statements?", "reconciliation", "Explain your investigation process.", "I would trace the discrepancy back to the source documents, compare entries, and reconcile accounts. I would then adjust with proper documentation.", "I start by identifying the accounts involved and reviewing the trial balance. I then check the underlying transactions, matching them to bank statements, invoices, and receipts. I use reconciliation software or spreadsheets to find mismatches. Once found, I correct the error and document the change. I ensure proper approval for adjustments."],
  ["Accountant", "How do you ensure compliance with tax regulations?", "compliance", "Discuss staying up-to-date and process controls.", "I regularly review regulatory updates, attend training, and implement internal controls. I also work with external advisors when needed.", "I subscribe to tax authority newsletters and update my knowledge through continuous education. I implement checks in the accounting system to flag potential issues. I conduct regular internal audits. I also maintain a calendar of filing deadlines. I consult with tax experts for complex matters. I document all decisions to defend in case of audit."],
  ["Accountant", "How do you manage cash flow forecasting?", "forecasting", "Describe your modelling approach.", "I use historical data, sales projections, and known expenses to build a rolling forecast. I also account for seasonal variations and collect feedback from business units.", "I create a cash flow forecast model in Excel or using software, starting with opening balance, adding expected inflows (sales, collections), and subtracting outflows (payables, payroll, debt). I use different scenarios (best, worst, base). I update weekly or monthly with actuals. I involve sales and operations for accurate inputs. I identify potential shortfalls and advise on mitigation."],

  // Banking (3 new)
  ["Banking", "How do you assess credit risk?", "credit", "Discuss quantitative and qualitative factors.", "I evaluate creditworthiness using financial ratios, credit history, and industry conditions. I also consider the borrower's character and capacity.", "I start with financial statement analysis: liquidity, leverage, profitability. I review credit reports and payment histories. I assess the industry outlook and competitive position. I also conduct qualitative interviews with management. I score the borrower using internal rating models. I then propose risk mitigation measures like collateral or covenants."],
  ["Banking", "How do you detect fraudulent transactions?", "fraud", "Explain monitoring and pattern recognition.", "I use transaction monitoring systems that flag unusual patterns, such as large amounts, unusual locations, or rapid succession of transactions. I also review alerts and escalate when needed.", "I work with fraud detection software that applies rules and machine learning to flag suspicious activity. I review alerts and investigate by checking customer history, transaction timing, and device/IP information. I also monitor for known fraud patterns. I collaborate with compliance and law enforcement when necessary. I implement periodic reviews and update detection rules based on emerging threats."],
  ["Banking", "How do you maintain customer trust in banking?", "trust", "Discuss transparency, security, and service.", "I maintain trust by being transparent about policies, protecting customer data, and delivering consistent service. I also proactively communicate changes.", "I ensure that communications are clear and honest. I protect data with strong security measures. I handle complaints promptly and fairly. I also educate customers on fraud prevention. I measure trust through surveys and retention rates. I uphold ethical standards and regulatory compliance at all times."],

  // Finance (3 new)
  ["Finance", "How do you evaluate an investment opportunity?", "investment", "Use financial metrics and qualitative assessment.", "I calculate NPV, IRR, and payback period, and also consider strategic fit and risk. I compare with alternative investments.", "I start with projected cash flows and apply discount rates to compute NPV and IRR. I also consider sensitivity analysis for key assumptions. I evaluate the competitive advantage, market size, and management team. I assess risks like technological change or regulatory. I compare the opportunity to the company's cost of capital and other available investments."],
  ["Finance", "How do you manage financial risk?", "risk", "Identify risks and mitigation strategies.", "I identify risks (market, credit, liquidity, operational) and use hedging, diversification, and insurance. I also monitor risk limits and report regularly.", "I use risk assessment tools to quantify exposure (e.g., VaR). I implement hedging strategies with derivatives for currency or interest rate risk. I diversify investments and revenue streams. I maintain liquidity buffers. I establish internal controls and audit processes. I report risk positions to senior management and the board, adjusting strategies as market conditions change."],
  ["Finance", "How do you create a budget?", "budgeting", "Discuss top-down and bottom-up approaches.", "I combine historical data with strategic goals. I involve department heads for bottom-up input, then align with top-down targets.", "I start by reviewing past performance and adjusting for known changes. I then gather projections from each department (bottom-up) and reconcile with overall corporate targets (top-down). I allocate resources based on priorities and expected ROI. I include contingency reserves. I present the budget for approval and then track actuals vs. budget, explaining variances monthly."],

  // Fresher (3 new)
  ["Fresher", "Tell me about a time you worked in a team.", "teamwork", "Describe your role and contribution.", "I was part of a team project where I contributed my skills, communicated regularly, and helped resolve conflicts. The team achieved its goal and I learned collaboration.", "I choose a project from my studies or internship. I describe the team size, my specific responsibilities, and how we coordinated (stand-ups, shared docs). I mention a challenge like a disagreement or time pressure and how we overcame it. I highlight what I learned about trust and communication."],
  ["Fresher", "How do you handle pressure or tight deadlines?", "stress", "Discuss time management and composure.", "I stay organised, break tasks into smaller steps, and communicate with my manager if I need help. I also maintain a positive attitude and focus on quality.", "I plan my time by prioritising tasks and using to-do lists. I avoid multitasking and focus on one thing at a time. I take short breaks to stay fresh. If I feel overwhelmed, I ask for clarification or extra resources. I also reflect on what worked well after the deadline to improve next time."],
  ["Fresher", "What are your career goals?", "goals", "Be specific and connect to the role.", "I want to grow into a subject matter expert in this field, and I see this role as the first step to gaining practical experience and learning from senior colleagues.", "I set short-term and long-term goals. Short-term: become proficient in the tools and processes of the team. Long-term: take on more responsibility and possibly lead projects. I tie my goals to the company's mission, showing I want to contribute meaningfully and grow within the organisation."],

  // Internship (3 new)
  ["Internship", "How do you seek feedback and improve?", "learning", "Describe your feedback-seeking process.", "I actively ask for feedback after tasks, and I treat it as a learning opportunity. I then create an action plan to address areas of improvement.", "I set up regular check-ins with my mentor. After completing a task, I ask specific questions like 'What could I have done better?' I listen without being defensive. I note feedback and incorporate it in subsequent work. I also seek feedback from peers. I keep a log of lessons learned."],
  ["Internship", "How do you manage your time as an intern?", "time-management", "Discuss prioritisation and work-life balance.", "I use a calendar and to-do list, prioritise based on deadlines and impact, and allocate time for learning. I also ensure I take breaks to avoid burnout.", "I start each day by listing tasks and ranking them by urgency/importance. I block time for focused work. I use tools like Trello or Notion. I communicate with my team about my availability. I also set aside time for learning new skills. I balance by ensuring I have time for rest and hobbies."],
  ["Internship", "How do you contribute to team meetings?", "participation", "Discuss preparation and engagement.", "I prepare by reviewing the agenda and notes beforehand. I ask thoughtful questions and share my perspectives when relevant, even if I'm new.", "I come to meetings with a list of questions or updates on my work. I listen actively and take notes. I volunteer for action items. If I'm unsure about something, I ask for clarification. I try to contribute ideas based on my research or fresh perspective. I also follow up on action items after the meeting."],

  // HR (role) (3 new)
  ["HR", "How do you handle employee grievances?", "grievance", "Discuss investigation and resolution.", "I take grievances seriously, conduct a fair investigation, and work towards a resolution that aligns with policy and employee well-being.", "I start by listening to the employee's complaint in a private setting. I gather all relevant information and interview witnesses. I maintain confidentiality. I then assess whether the grievance is valid and suggest remedies, which could include mediation, policy changes, or disciplinary action. I ensure the process is documented and that the employee feels heard."],
  ["HR", "How do you design a compensation structure?", "compensation", "Balance market competitiveness and internal equity.", "I conduct market salary surveys, evaluate job roles, and create bands that reflect value. I also consider performance and experience.", "I benchmark roles against industry data using surveys. I evaluate internal job evaluations to ensure fairness. I design salary ranges with minimum, midpoint, and maximum, considering budget and strategic goals. I also include variable pay and benefits. I review structures annually and adjust for cost of living and market shifts."],
  ["HR", "How do you improve employee retention?", "retention", "Identify drivers of turnover and implement initiatives.", "I analyse exit data, conduct stay interviews, and focus on engagement, career development, and work-life balance. I also improve onboarding and recognition.", "I review exit interview themes to identify common reasons for leaving. I conduct stay interviews with high performers to understand what keeps them. I implement career pathing, mentorship programs, and flexible work options. I also recognise achievements regularly. I measure retention rates and adjust strategies based on feedback and data."],

  // Behavioral (3 new)
  ["Behavioral", "Tell me about a time you had to adapt to change.", "adaptability", "Explain how you handled uncertainty.", "I describe a situation where I had to learn a new process or tool quickly, focusing on my adaptability and positive attitude.", "I give a specific example, like a company merger or new software rollout. I explain how I approached it with curiosity and asked for help. I describe how I adjusted my workflow and helped others adapt. I highlight the positive outcome and what I learned about being flexible."],
  ["Behavioral", "Describe a situation where you failed and what you learned.", "failure", "Show reflection and growth.", "I talk about a project that didn't go as planned, what I could have done differently, and how I applied that learning later.", "I choose a genuine failure, not a minor mistake. I explain the context, my actions, and the outcome. I reflect on the root cause, like poor planning or communication. I then describe what I changed afterward: e.g., I started using checklists or sought more feedback. I emphasise that failure is a learning opportunity."],
  ["Behavioral", "Give an example of when you showed leadership.", "leadership", "Describe leading a team or initiative without a title.", "I share a situation where I took the initiative to coordinate a team effort, even without formal authority, and achieved a positive result.", "I describe a project where I volunteered to lead a subgroup, organised tasks, and motivated others. I mention how I communicated a vision and resolved conflicts. I show how I empowered others and ensured accountability. I end with the outcome and what I learned about leadership."],

  // Situational (3 new)
  ["Situational", "What would you do if you disagreed with your manager?", "disagreement", "Focus on respectful communication and data.", "I would request a private meeting to discuss my perspective with evidence, and I would propose alternatives while acknowledging their view.", "I would prepare my case with data and examples. I would schedule a meeting and express my concerns constructively, asking clarifying questions. I would listen to their rationale and find common ground. If we still disagree, I would accept their decision but document my concerns. I would ensure the conversation remains professional."],
  ["Situational", "How would you handle a project that is falling behind schedule?", "schedule", "Prioritise tasks and communicate.", "I would assess the remaining work, re-prioritise tasks, and escalate if necessary. I would also consider adding resources or adjusting scope.", "I would first review the project plan and identify critical path items. I would reprioritise to deliver the most important features first. I would communicate the revised timeline to stakeholders and explain the reasons. I might request overtime or additional resources. I would also monitor progress more frequently. I would ensure the quality is not compromised."],
  ["Situational", "What would you do if you noticed a colleague making a mistake?", "mistake", "Address it with tact and support.", "I would approach the colleague privately, explain what I observed, and offer to help. I would avoid embarrassing them and focus on resolving the issue.", "I would choose a private moment and start with a question, like 'I noticed this – are you aware?' I would listen to their explanation. I would then offer assistance or suggest a solution. If it's a systemic issue, I would discuss with the team. I would maintain a supportive tone and ensure the mistake is corrected without blame."]
] as const;

const angles = ["for a small team", "when requirements are unclear", "under a tight deadline", "with a focus on accessibility", "with limited operational budget", "when a previous solution failed", "for a high-risk release", "when explaining your decision to a non-specialist", "while mentoring a junior teammate", "after measuring an unexpected result"];
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

async function main() {
  const categoryMap = new Map<string, string>();
  for (const [name, group] of categories) {
    const category = await prisma.category.upsert({
      where: { slug: slugify(name) },
      update: {},
      create: { name, slug: slugify(name), group, description: `Focused ${name} interview preparation.` }
    });
    categoryMap.set(name, category.id);
    await prisma.subcategory.upsert({
      where: { categoryId_slug: { categoryId: category.id, slug: slugify(name) } },
      update: {},
      create: { name, slug: slugify(name), categoryId: category.id }
    });
  }

  for (let topicIndex = 0; topicIndex < topics.length; topicIndex++) {
    const [categoryName, baseQuestion, tag, explanation, sampleAnswer, detailedAnswer] = topics[topicIndex];
    const categoryId = categoryMap.get(categoryName)!;
    const subcategory = await prisma.subcategory.findFirst({ where: { categoryId } });
    for (let angleIndex = 0; angleIndex < angles.length; angleIndex++) {
      const question = `${baseQuestion} ${angles[angleIndex]}?`;
      const slug = `${slugify(baseQuestion)}-${slugify(angles[angleIndex])}`;
      const difficulty = [Difficulty.EASY, Difficulty.MEDIUM, Difficulty.HARD][(topicIndex + angleIndex) % 3];
      const experienceLevel = [ExperienceLevel.FRESHER, ExperienceLevel.INTERNSHIP, ExperienceLevel.MID_LEVEL, ExperienceLevel.EXPERIENCED][(topicIndex + angleIndex) % 4];
      const interviewType = categoryName === "Behavioral" || categoryName === "HR" ? InterviewType.BEHAVIORAL : categoryName === "Situational" ? InterviewType.SITUATIONAL : InterviewType.TECHNICAL;
      await prisma.interviewQuestion.upsert({
        where: { slug },
        update: {
          question,
          categoryId,
          subcategoryId: subcategory?.id,
          experienceLevel,
          difficulty,
          interviewType,
          shortDescription: `A practical ${tag} question focused on ${angles[angleIndex]}.`,
          explanation,
          sampleAnswer,
          detailedAnswer,
          keyPoints: ["State your assumptions", "Use a specific example", "Explain the trade-off", "Close with the result or next step"],
          commonMistakes: ["Starting without clarifying the goal", "Listing tools without explaining judgment", "Making claims without evidence"],
          followUpQuestions: [`What would you measure after making that decision?`, `What would you change with more time?`],
          tags: [tag, slugify(categoryName)],
          isPublished: true,
          seoTitle: question,
          seoDescription: `Learn how to approach this ${tag} interview question with a clear, practical answer.`
        },
        create: {
          question,
          slug,
          categoryId,
          subcategoryId: subcategory?.id,
          experienceLevel,
          difficulty,
          interviewType,
          shortDescription: `A practical ${tag} question focused on ${angles[angleIndex]}.`,
          explanation,
          sampleAnswer,
          detailedAnswer,
          keyPoints: ["State your assumptions", "Use a specific example", "Explain the trade-off", "Close with the result or next step"],
          commonMistakes: ["Starting without clarifying the goal", "Listing tools without explaining judgment", "Making claims without evidence"],
          followUpQuestions: [`What would you measure after making that decision?`, `What would you change with more time?`],
          tags: [tag, slugify(categoryName)],
          isPublished: true,
          seoTitle: question,
          seoDescription: `Learn how to approach this ${tag} interview question with a clear, practical answer.`
        }
      });
    }
  }

  for (const article of articleSeeds) {
    const category = article.slug.includes("technical") ? categoryMap.get("Software Developer") : categoryMap.get("General");
    await prisma.article.upsert({
      where: { slug: article.slug },
      update: { ...article, categoryId: category, isPublished: true, publishedAt: new Date() },
      create: { ...article, categoryId: category, isPublished: true, publishedAt: new Date() }
    });
  }

  if (process.env.ADMIN_EMAIL) {
    await prisma.user.updateMany({
      where: { email: process.env.ADMIN_EMAIL.toLowerCase().trim() },
      data: { role: "ADMIN" }
    });
  }

  console.log(`Seeded ${topics.length * angles.length} interview questions and ${articleSeeds.length} articles.`);
}

main()
  .catch(error => { console.error(error); process.exit(1); })
  .finally(() => prisma.$disconnect());