// ---- 200 Microservices Interview Questions (Fresher to Advanced) ----
// ---- 200 Linux System Engineering Questions (Fresher to Advanced) ----
// ---- 200 Kubernetes Interview Questions (Fresher to Advanced) ----
// ---- 200 Java Developer Questions (Fresher to Advanced) ----
import { Difficulty, ExperienceLevel, InterviewType, PrismaClient } from "@prisma/client";

// ---- 200 Docker Interview Questions (Fresher to Advanced) ----
// ---- Categories ----
export const categories = [
  ["System Engineer", "System Engineer"]
] as const;

// ---- 200 Git & GitHub Interview Questions (Fresher to Advanced) ----
export const topics = [
  // ==================== FOUNDATIONAL CONCEPTS (Easy-Medium) ====================
  ["System Engineer", "What is the difference between scalability and elasticity?", "scalability-vs-elasticity", "Define both terms and clarify their distinction.", "Scalability is the ability of a system to handle increased load by adding resources (vertical or horizontal). Elasticity is the ability to automatically scale resources up and down based on demand, often in cloud environments."],
  ["System Engineer", "What is horizontal scaling vs vertical scaling?", "horizontal-vs-vertical-scaling", "Explain the two scaling approaches.", "Vertical scaling (scale-up) adds more power (CPU, RAM) to an existing machine. Horizontal scaling (scale-out) adds more machines (nodes) to a system. Horizontal scaling is preferred for large-scale systems due to its redundancy and cost-effectiveness."],
  ["System Engineer", "What is a single point of failure (SPOF)?", "single-point-of-failure", "Define and give examples.", "A single point of failure is a component of a system that, if it fails, will cause the entire system to fail. Examples include a single database server, a load balancer, or a network switch. Mitigation involves redundancy and failover mechanisms."],
  ["System Engineer", "Explain the CAP theorem.", "cap-theorem", "Describe Consistency, Availability, and Partition tolerance.", "The CAP theorem states that in a distributed system, you can only guarantee two out of three: Consistency (every read receives the most recent write), Availability (every request gets a response), and Partition tolerance (the system continues to operate despite network partitions). In practice, you choose between CP (strong consistency) and AP (high availability)."],
  ["System Engineer", "What is the difference between consistency and availability in CAP?", "consistency-vs-availability", "Clarify the trade-offs.", "Consistency ensures all nodes see the same data at the same time. Availability ensures the system responds to requests even if some nodes are down. In a network partition, you must choose: either keep the system consistent (CP) or keep it available (AP)."],
  ["System Engineer", "What is eventual consistency?", "eventual-consistency", "Define the consistency model.", "Eventual consistency is a guarantee that, given enough time without new updates, all replicas will converge to the same value. It is a weaker consistency model often used in distributed databases (e.g., DynamoDB, Cassandra) to achieve high availability."],
  ["System Engineer", "What is the difference between synchronous and asynchronous communication?", "sync-vs-async-communication", "Explain the two styles.", "Synchronous communication requires the caller to wait for the response (e.g., HTTP/REST). Asynchronous communication does not block the caller; the response is handled later via callbacks, message queues, or events."],
  ["System Engineer", "What is a message queue and when would you use it?", "message-queue", "Explain the purpose and use cases.", "A message queue is a buffer that decouples producers and consumers. It allows asynchronous processing, load balancing, and fault tolerance. Use cases include task distribution, decoupling microservices, and handling spikes in traffic."],
  ["System Engineer", "What is a load balancer and what are its common algorithms?", "load-balancer", "Define and list algorithms.", "A load balancer distributes incoming traffic across multiple servers. Common algorithms: Round Robin, Least Connections, IP Hash, Weighted Round Robin, and Random. Layer 4 (transport) vs Layer 7 (application) load balancers also exist."],
  ["System Engineer", "Explain the difference between TCP and UDP.", "tcp-vs-udp", "Compare the two transport protocols.", "TCP is connection-oriented, reliable, and ensures ordered delivery. It is used for web traffic (HTTP/HTTPS). UDP is connectionless, unreliable, but faster and used for real-time applications (video streaming, DNS)."],

  // ==================== CACHING (Medium) ====================
  ["System Engineer", "What is caching and why is it important?", "caching", "Define caching and its benefits.", "Caching stores frequently accessed data in a high-speed storage layer (memory) to reduce latency and database load. It improves read performance and reduces network bandwidth usage."],
  ["System Engineer", "What are the different caching strategies? (e.g., cache-aside, write-through, write-behind)", "caching-strategies", "Explain common caching patterns.", "Cache-Aside: application reads from cache; if not present, it reads from DB and populates cache. Write-Through: writes go to both cache and DB. Write-Behind: writes go to cache, and writes to DB asynchronously. Also, Read-Through and Refresh-Ahead."],
  ["System Engineer", "What is a CDN and how does it improve performance?", "cdn", "Explain content delivery networks.", "A CDN is a geographically distributed network of proxy servers that caches content (static assets) closer to end users. It reduces latency, offloads origin servers, and improves availability."],
  ["System Engineer", "What is cache invalidation and why is it hard?", "cache-invalidation", "Explain the challenge.", "Cache invalidation is the process of removing stale data from cache when the underlying data changes. It's hard because you must ensure consistency across multiple caches and avoid race conditions. Common strategies: TTL, invalidation on write, and using versioning."],
  ["System Engineer", "What is the difference between Redis and Memcached?", "redis-vs-memcached", "Compare the two caching systems.", "Memcached is a simple, distributed in-memory cache with a key-value store. Redis is more feature-rich, supporting persistence, complex data types (lists, sets, sorted sets, hashes), replication, and transactions. Redis is often used as a cache and a lightweight database."],
  ["System Engineer", "What is a cache stampede (thundering herd) and how do you prevent it?", "cache-stampede", "Explain the problem and solutions.", "A cache stampede occurs when many clients request a key that has just expired, causing a flood of queries to the database. Prevention: using a mutex (only one thread recomputes the value), or using a probabilistic early expiration."],
  ["System Engineer", "What is a distributed cache and when would you use it?", "distributed-cache", "Define and give use cases.", "A distributed cache spans multiple nodes to provide large capacity and fault tolerance. Use cases: session storage, API response caching, and caching in microservices architectures. Examples: Redis Cluster, Hazelcast."],

  // ==================== DATABASES (Medium-Hard) ====================
  ["System Engineer", "What is database sharding?", "sharding", "Explain horizontal partitioning.", "Sharding partitions a large database into smaller, faster, and more manageable pieces called shards. Each shard is a separate database instance. Sharding is used to distribute load and improve write scalability."],
  ["System Engineer", "What are the different sharding strategies? (e.g., range, hash, directory)", "sharding-strategies", "List common approaches.", "Range sharding: assigns ranges of keys to shards (e.g., A-M, N-Z). Hash sharding: uses a hash function to determine the shard. Directory-based: uses a lookup table to map keys to shards."],
  ["System Engineer", "What is database replication and what are its types?", "replication", "Explain master-slave and multi-master.", "Replication copies data from one database server to another. Types: Master-Slave (all writes to master, reads from slaves) and Multi-Master (writes to any master with conflict resolution). Replication improves read scalability and fault tolerance."],
  ["System Engineer", "What is the difference between SQL and NoSQL databases?", "sql-vs-nosql", "Compare the two paradigms.", "SQL databases are relational, use structured schemas, and support ACID transactions. NoSQL databases are non-relational, schema-less, and scale horizontally. NoSQL types: document (MongoDB), key-value (Redis), wide-column (Cassandra), graph (Neo4j)."],
  ["System Engineer", "When would you choose a NoSQL database over a SQL database?", "when-nosql", "Provide decision criteria.", "Choose NoSQL for: massive scale, high write throughput, flexible schema, or when data is unstructured. Choose SQL for: strong consistency, complex queries (joins), and ACID transactions."],
  ["System Engineer", "What is an ACID transaction?", "acid", "Define the properties.", "ACID stands for Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent transactions do not interfere), and Durability (committed changes persist). ACID guarantees are typical of SQL databases."],
  ["System Engineer", "What is the difference between optimistic and pessimistic locking?", "optimistic-vs-pessimistic-locking", "Explain concurrency control.", "Pessimistic locking assumes conflicts will happen and locks the record for the transaction. Optimistic locking assumes conflicts are rare; it reads without locking and checks for conflicts before committing (using version numbers)."],
  ["System Engineer", "Explain the different isolation levels in SQL.", "isolation-levels", "List and describe.", "Read Uncommitted: dirty reads allowed. Read Committed: only committed data read. Repeatable Read: same data read twice yields same result. Serializable: highest isolation, prevents phantom reads."],
  ["System Engineer", "What is a distributed transaction and what is the Saga pattern?", "saga-pattern", "Explain handling distributed transactions.", "A distributed transaction spans multiple services. Two-phase commit (2PC) is a coordination protocol, but it's not practical in microservices. The Saga pattern breaks a transaction into a sequence of local transactions, each with a compensating action to rollback in case of failure."],
  ["System Engineer", "What is a database index and how does it work?", "database-index", "Explain indexing structures.", "An index is a data structure (typically B-tree or hash) that speeds up data retrieval. It adds overhead on writes. Choosing indexes wisely is critical for query performance."],

  // ==================== DISTRIBUTED SYSTEMS (Hard) ====================
  ["System Engineer", "What is the difference between consistency models: strong, eventual, and causal?", "consistency-models", "Define the models.", "Strong consistency: reads reflect the latest write across all nodes. Eventual consistency: after writes stop, all replicas will converge. Causal consistency: operations that are causally related are seen in the same order by all nodes."],
  ["System Engineer", "What is the Raft consensus algorithm?", "raft", "Explain its purpose and workings.", "Raft is a consensus algorithm for managing a replicated log. It ensures all replicas agree on the same log entries. It uses a leader-based approach: the leader accepts client requests, replicates them to followers, and commits when a majority acknowledges."],
  ["System Engineer", "What is the Paxos algorithm?", "paxos", "Explain the foundational consensus protocol.", "Paxos is a family of protocols for achieving consensus in a network of unreliable processors. It allows a group of nodes to agree on a single value despite failures. It is the basis for many distributed systems."],
  ["System Engineer", "What is a distributed hash table (DHT)?", "dht", "Define and give examples.", "A DHT is a decentralized key-value store that distributes data across nodes in a network. Examples include Chord, Kademlia (used in BitTorrent). It uses consistent hashing to assign keys to nodes."],
  ["System Engineer", "Explain consistent hashing and its benefits.", "consistent-hashing", "Define and describe its advantages.", "Consistent hashing maps keys and nodes to a circle (hash space). It minimizes rehashing when nodes are added/removed, making it ideal for distributed caches and partitioning."],
  ["System Engineer", "What is the difference between a distributed file system and a distributed database?", "dfs-vs-distributed-db", "Compare the two.", "A distributed file system (e.g., HDFS, GlusterFS) manages files across nodes, focusing on large sequential reads/writes. A distributed database (e.g., Cassandra, Spanner) provides structured data access with query capabilities."],
  ["System Engineer", "What is the Two-Phase Commit (2PC) protocol?", "2pc", "Explain the distributed transaction protocol.", "2PC is a coordination protocol that ensures all participants commit or abort a transaction. Phase 1: coordinator asks participants to prepare (vote). Phase 2: if all vote yes, commit; else abort. Drawback: blocking during coordinator failure."],
  ["System Engineer", "What is the Three-Phase Commit (3PC) protocol?", "3pc", "Explain the improved protocol.", "3PC extends 2PC with a pre-commit phase to avoid blocking if the coordinator fails. It requires that participants can make decisions based on timeouts, making it more resilient but more complex."],
  ["System Engineer", "What is a distributed lock? How is it implemented?", "distributed-lock", "Explain the concept and implementations.", "A distributed lock coordinates exclusive access to a resource across nodes. Implementations use Redis (Redlock), ZooKeeper, or etcd. They require careful handling of timeouts and split-brain scenarios."],
  ["System Engineer", "Explain the concept of 'at least once', 'at most once', and 'exactly once' delivery semantics.", "delivery-semantics", "Define the three semantics.", "At most once: messages may be lost but never delivered twice. At least once: messages are delivered at least once, possibly duplicating. Exactly once: each message is delivered exactly once. Common in message queues."],

  // ==================== MICROSERVICES & API GATEWAY (Medium-Hard) ====================
  ["System Engineer", "What are microservices? What are the pros and cons?", "microservices-pros-cons", "Discuss the architecture.", "Microservices are small, independently deployable services. Pros: independent scaling, technology diversity, faster development. Cons: operational complexity, network latency, data consistency issues, and debugging challenges."],
  ["System Engineer", "What is an API gateway and what are its responsibilities?", "api-gateway", "Define and list roles.", "An API gateway is a single entry point for clients. Responsibilities include: routing, authentication, rate limiting, caching, request/response transformation, and aggregation of results from multiple services."],
  ["System Engineer", "What is service discovery and how does it work?", "service-discovery", "Explain client-side vs server-side.", "Service discovery allows services to locate each other dynamically. Client-side discovery: client queries the registry (e.g., Eureka) directly. Server-side discovery: a load balancer queries the registry."],
  ["System Engineer", "What is a circuit breaker pattern and how does it help?", "circuit-breaker-pattern", "Define and explain its benefits.", "The circuit breaker pattern prevents a system from repeatedly trying to invoke a failing operation. It has states: Closed (normal), Open (fails fast), and Half-Open (tests for recovery). It helps in handling failures gracefully and prevents cascading failures."],
  ["System Engineer", "What is the difference between a gateway and a proxy?", "gateway-vs-proxy", "Clarify the distinction.", "A proxy typically serves as an intermediary for a single service or specific use case (e.g., reverse proxy for a web server). An API gateway is a more comprehensive solution that provides routing, aggregation, security, and other cross-cutting concerns for multiple services."],
  ["System Engineer", "What is the Strangler pattern in microservices?", "strangler-pattern", "Explain the migration pattern.", "The Strangler pattern incrementally replaces a monolithic application with microservices by routing traffic to new services while the monolith still serves part of the functionality. Over time, the monolith is 'strangled' and decommissioned."],
  ["System Engineer", "What is a sidecar pattern and where is it used?", "sidecar-pattern", "Define and give examples.", "The sidecar pattern deploys an auxiliary container alongside a service to provide logging, monitoring, or service discovery. It's common in Kubernetes (e.g., Envoy proxy, Istio) to offload cross-cutting concerns from the main application."],
  ["System Engineer", "What is the difference between orchestration and choreography?", "orchestration-vs-choreography", "Compare the two for microservices.", "Orchestration uses a central conductor to coordinate services (e.g., Saga orchestrator). Choreography relies on event-driven communication without a central controller, where services react to events (e.g., using Kafka). Orchestration is simpler to monitor; choreography is more decoupled."],
  ["System Engineer", "What is a service mesh and how does it work?", "service-mesh", "Explain the infrastructure layer.", "A service mesh is a dedicated infrastructure layer for handling service-to-service communication. It provides features like traffic management, security (mTLS), and observability via sidecar proxies (e.g., Istio, Linkerd)."],

  // ==================== NETWORKING & PROTOCOLS (Medium) ====================
  ["System Engineer", "What is the OSI model and its layers?", "osi-model", "List the layers.", "The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application."],
  ["System Engineer", "Explain the difference between HTTP/1.1, HTTP/2, and HTTP/3.", "http-versions", "Compare the protocol versions.", "HTTP/1.1: uses persistent connections and pipelining but suffers from head-of-line blocking. HTTP/2: uses binary framing, multiplexing, and server push. HTTP/3: runs over QUIC (UDP) to reduce latency and improve connection recovery."],
  ["System Engineer", "What is a DNS and how does it work?", "dns", "Explain the domain name system.", "DNS translates domain names to IP addresses. It is a hierarchical, distributed database. A query goes from browser -> local resolver -> root -> TLD -> authoritative nameserver."],
  ["System Engineer", "What is a reverse proxy? Give an example.", "reverse-proxy", "Define and provide use cases.", "A reverse proxy sits in front of web servers and forwards client requests to them. It provides load balancing, caching, SSL termination, and security. Examples: Nginx, HAProxy."],
  ["System Engineer", "What is a WebSocket and how does it differ from HTTP?", "websocket-vs-http", "Compare the protocols.", "WebSocket is a full-duplex, persistent connection that enables real-time, bidirectional communication over a single TCP connection. HTTP is request-response and stateless."],
  ["System Engineer", "Explain the concept of a network partition (split-brain).", "split-brain", "Define the failure scenario.", "Split-brain occurs when a network partition causes nodes to lose communication, leading to independent decisions and data inconsistencies. It is mitigated using consensus algorithms and quorum-based writes."],
  ["System Engineer", "What is a firewall and how does it protect a system?", "firewall", "Define and explain.", "A firewall monitors and controls incoming/outgoing network traffic based on security rules. It protects systems from unauthorized access and attacks."],
  ["System Engineer", "What is SSL/TLS and why is it important?", "ssl-tls", "Explain encryption in transit.", "SSL/TLS encrypts data transmitted over a network, ensuring confidentiality and integrity. It is used for HTTPS, securing APIs, and protecting sensitive information from eavesdropping."],

  // ==================== OBSERVABILITY & MONITORING (Medium) ====================
  ["System Engineer", "What is the difference between logging, metrics, and tracing?", "observability-pillars", "Define the three pillars.", "Logging: records discrete events (errors, requests). Metrics: numerical measurements over time (latency, error rates). Tracing: tracks the path of a request across services (distributed tracing)."],
  ["System Engineer", "What is distributed tracing and why is it useful?", "distributed-tracing", "Explain the concept.", "Distributed tracing tracks a single request as it propagates through multiple services, allowing you to visualize the flow, identify bottlenecks, and debug latency issues. Tools: Jaeger, Zipkin."],
  ["System Engineer", "What is a metric and what are common types?", "metrics", "Define and give examples.", "Metrics are quantitative measurements that can be aggregated and alerted on. Common types: counters (e.g., request count), gauges (e.g., current memory usage), histograms (e.g., request latency distribution), and summaries."],
  ["System Engineer", "What is an SLI, SLO, and SLA?", "sli-slo-sla", "Define the terms.", "SLI (Service Level Indicator): a metric measuring a service's performance (e.g., latency). SLO (Service Level Objective): a target for an SLI (e.g., 99.9% of requests < 200ms). SLA (Service Level Agreement): a formal agreement with the customer, often with penalties for violations."],
  ["System Engineer", "What is the difference between black-box and white-box monitoring?", "black-vs-white-box-monitoring", "Explain the approaches.", "Black-box monitoring observes the system from outside, simulating user behavior (e.g., synthetic checks). White-box monitoring collects internal metrics (e.g., JVM heap, request counts) to understand system health."],
  ["System Engineer", "What is a dashboard and what are best practices for building one?", "dashboard", "Explain and give guidelines.", "A dashboard visualizes key metrics in a single view. Best practices: focus on SLOs, avoid clutter, use meaningful charts (time-series, histograms), and include alerts for anomalies."],
  ["System Engineer", "What is the difference between Prometheus and Grafana?", "prometheus-vs-grafana", "Compare the tools.", "Prometheus is a time-series database and monitoring system that scrapes metrics from targets. Grafana is a visualization tool that can query Prometheus (and other data sources) to create dashboards."],

  // ==================== RESILIENCY & FAULT TOLERANCE (Medium-Hard) ====================
  ["System Engineer", "What is a retry with exponential backoff and why is it used?", "exponential-backoff", "Explain the retry strategy.", "Exponential backoff is a retry policy where the delay between attempts increases exponentially (e.g., 1s, 2s, 4s). It prevents thundering herd and gives the system time to recover. Used with jitter to avoid collisions."],
  ["System Engineer", "What is a timeout? How do you set appropriate timeouts?", "timeouts", "Explain the importance.", "A timeout defines how long to wait for a response before aborting. Set timeouts based on service latency, network conditions, and business requirements. Use client-side timeouts to avoid hanging and resource exhaustion."],
  ["System Engineer", "What is a health check and what are the types?", "health-check", "Define and list types.", "A health check is a probe to determine if a service is running correctly. Types: liveness (is the process alive?), readiness (can it serve traffic?), and startup (allow for initialization)."],
  ["System Engineer", "What is a graceful shutdown and why is it important?", "graceful-shutdown", "Explain the process.", "Graceful shutdown allows a service to finish processing in-flight requests and clean up resources before terminating, reducing errors for clients."],
  ["System Engineer", "What is the difference between failover and failback?", "failover-vs-failback", "Explain the terms.", "Failover is the process of switching to a redundant system when the primary fails. Failback is the process of restoring the primary system and switching back to it."],
  ["System Engineer", "What is a quorum in distributed systems?", "quorum", "Explain the concept.", "A quorum is the minimum number of nodes that must agree for an operation to succeed. It is used in distributed consensus to ensure consistency despite failures. Typically, you need a majority of nodes."],
  ["System Engineer", "What is a circuit breaker pattern? How does it differ from a retry?", "circuit-breaker-vs-retry", "Compare the two.", "Retry reattempts a failed operation, which can be useful for transient failures. Circuit breaker stops attempting after a threshold, preventing overload on a failing service. They are complementary."],
  ["System Engineer", "What is a chaos engineering and why is it used?", "chaos-engineering", "Define its purpose.", "Chaos engineering is the practice of introducing failures (e.g., killing nodes, introducing latency) to test a system's resilience. It helps identify weaknesses and build confidence in fault tolerance mechanisms."],

  // ==================== DEPLOYMENT & INFRASTRUCTURE (Medium) ====================
  ["System Engineer", "What is containerization and how does it differ from virtualization?", "container-vs-vm", "Compare the two.", "Containerization (Docker) packages an application with its dependencies, sharing the host OS kernel. Virtualization (VMs) emulates a full operating system, each with its own kernel. Containers are lighter and faster."],
  ["System Engineer", "What is Kubernetes and what are its main components?", "kubernetes", "Explain the orchestration platform.", "Kubernetes is a container orchestration platform. Main components: API server, etcd (key-value store), scheduler, controller manager, kubelet (node agent), and kube-proxy."],
  ["System Engineer", "What is a Pod in Kubernetes?", "pod", "Define the smallest deployable unit.", "A Pod is a group of one or more containers that share networking and storage. They are the smallest deployable unit in Kubernetes."],
  ["System Engineer", "What is a service in Kubernetes and what are its types?", "kubernetes-service", "Explain service discovery.", "A Service is an abstraction that defines a logical set of Pods and a policy to access them. Types: ClusterIP (internal), NodePort (exposed on node port), LoadBalancer (cloud LB), and Ingress (HTTP routing)."],
  ["System Engineer", "What is a ConfigMap and a Secret in Kubernetes?", "configmap-secret", "Explain configuration management.", "ConfigMap stores non-sensitive configuration data. Secret stores sensitive data (passwords, tokens) in an encoded format. They decouple configuration from container images."],
  ["System Engineer", "What is a CI/CD pipeline and what are its typical stages?", "cicd-pipeline", "Define and list stages.", "CI/CD (Continuous Integration/Continuous Deployment) automates the build, test, and deployment of applications. Stages: source code commit -> build -> unit tests -> integration tests -> deploy to staging -> deploy to production (with approvals)."],
  ["System Engineer", "What is Infrastructure as Code (IaC)? Give examples.", "iac", "Explain the concept.", "IaC manages infrastructure (servers, networking) using code rather than manual processes. Tools: Terraform, CloudFormation, Ansible. It ensures reproducibility, version control, and automation."],
  ["System Engineer", "What is the difference between blue-green deployment and canary deployment?", "blue-green-vs-canary", "Compare the deployment strategies.", "Blue-green: two identical environments, one active (blue) and one idle (green). Switch traffic after validation. Canary: incremental rollout (e.g., 5%, 20%, 100%) to reduce risk and test performance."],
  ["System Engineer", "What is a rolling update in Kubernetes?", "rolling-update", "Explain the update strategy.", "A rolling update gradually replaces existing Pods with new ones, ensuring zero downtime. It allows you to control the speed and can be rolled back if issues arise."],
  ["System Engineer", "What is a feature flag and how is it used?", "feature-flag", "Explain the technique.", "Feature flags allow you to enable/disable features in production without redeploying. They decouple deployment from release and support A/B testing, canary releases, and gradual rollouts."],

  // ==================== DATA PIPELINES & STREAMING (Medium-Hard) ====================
  ["System Engineer", "What is Apache Kafka and what are its core concepts?", "kafka", "Define and list concepts.", "Kafka is a distributed event streaming platform. Core concepts: Topics (categories of messages), Partitions (ordered, immutable logs), Producers (publish), Consumers (subscribe), and Brokers (nodes)."],
  ["System Engineer", "What is the difference between a topic and a partition in Kafka?", "topic-vs-partition", "Explain the hierarchy.", "A topic is a logical category for messages. Each topic is split into partitions, which are ordered sequences of messages. Partitions provide parallelism and scalability."],
  ["System Engineer", "What is a message broker and how does it differ from a database?", "message-broker-vs-database", "Compare their roles.", "A message broker (e.g., RabbitMQ, Kafka) facilitates asynchronous communication between services by storing and forwarding messages. A database stores persistent data for later retrieval. Brokers are optimized for throughput and low latency."],
  ["System Engineer", "Explain the concept of event sourcing and CQRS.", "event-sourcing-cqrs", "Define both patterns.", "Event sourcing stores the state of a system as a sequence of events. CQRS (Command Query Responsibility Segregation) separates read and write models. They are often used together to handle complex business logic and scalability."],
  ["System Engineer", "What is a stream processing framework and give examples?", "stream-processing", "Define and list examples.", "Stream processing processes data in real-time as it flows. Examples: Apache Flink, Apache Spark Streaming, Kafka Streams. They are used for real-time analytics, monitoring, and alerting."],

  // ==================== CLOUD & HYBRID (Medium) ====================
  ["System Engineer", "What is the difference between IaaS, PaaS, and SaaS?", "iaas-paas-saas", "Define the cloud service models.", "IaaS (Infrastructure as a Service) provides virtualized computing resources (e.g., AWS EC2). PaaS (Platform as a Service) provides a platform for developing and deploying applications (e.g., Heroku). SaaS (Software as a Service) delivers fully functional applications over the internet (e.g., Gmail)."],
  ["System Engineer", "What are the main cloud providers and their key services?", "cloud-providers", "List AWS, GCP, Azure.", "AWS offers EC2, S3, RDS, Lambda. GCP offers Compute Engine, Cloud Storage, BigQuery. Azure offers Virtual Machines, Blob Storage, SQL Database."],
  ["System Engineer", "What is serverless computing? Give examples.", "serverless", "Define and give examples.", "Serverless allows you to run code without provisioning or managing servers. The cloud provider handles scaling and infrastructure. Examples: AWS Lambda, Google Cloud Functions, Azure Functions."],
  ["System Engineer", "What is a multi-cloud strategy and what are its benefits and drawbacks?", "multi-cloud", "Explain the approach.", "Multi-cloud uses multiple cloud providers to avoid vendor lock-in, improve resilience, and leverage best-of-breed services. Drawbacks: increased complexity, network costs, and management overhead."],
  ["System Engineer", "What is a hybrid cloud and when would you use it?", "hybrid-cloud", "Define and give use cases.", "Hybrid cloud combines on-premises infrastructure with public cloud services. Use cases: data privacy regulations, legacy systems integration, and bursting workloads."],

  // ==================== SECURITY (Medium) ====================
  ["System Engineer", "What is the difference between authentication and authorization?", "authn-vs-authz", "Define the two terms.", "Authentication verifies who a user is (identity). Authorization determines what a user can do (permissions)."],
  ["System Engineer", "What is OAuth2 and how does it work?", "oauth2", "Explain the authorization framework.", "OAuth2 is a protocol for delegated authorization. It allows users to grant third-party applications limited access to their resources without sharing credentials. Roles: Resource Owner, Client, Authorization Server, Resource Server."],
  ["System Engineer", "What is JWT (JSON Web Token) and when is it used?", "jwt", "Explain the token format.", "JWT is a compact, self-contained token that securely transmits information between parties as a JSON object. It is commonly used for authentication (stateless sessions) and API authorization."],
  ["System Engineer", "What is TLS and how does it secure communication?", "tls", "Explain transport layer security.", "TLS (Transport Layer Security) encrypts data exchanged between a client and server, ensuring confidentiality and integrity. It is used for HTTPS, secure email, and many other protocols."],
  ["System Engineer", "What is the difference between symmetric and asymmetric encryption?", "symmetric-vs-asymmetric", "Compare encryption methods.", "Symmetric encryption uses the same key for encryption and decryption (fast, but key distribution is hard). Asymmetric encryption uses a public/private key pair (slower, but enables secure key exchange and digital signatures)."],

  // ==================== SYSTEM DESIGN SCENARIOS (Hard) ====================
  ["System Engineer", "How would you design a URL shortener (like bit.ly)?", "design-url-shortener", "Outline the system design.", "Use a key-value store to map short codes to long URLs. Generate short codes using base62 encoding of a counter or hash of the URL. Implement a caching layer (Redis) for fast redirects. Use a CDN for static content."],
  ["System Engineer", "How would you design a chat system (like WhatsApp)?", "design-chat-system", "Explain the architecture.", "Use WebSocket for real-time messaging, and a message broker (Kafka) to handle message persistence and delivery. Use a distributed database for chat history. Implement presence tracking."],
  ["System Engineer", "How would you design a social media feed (like Twitter)?", "design-feed", "Outline the system design.", "Use a fan-out-on-write approach to pre-compute feeds for active users. Store tweets in a timeline database (e.g., Cassandra). Use caching for read-heavy workloads. Use a CDN for media."],
  ["System Engineer", "How would you design a distributed rate limiter?", "design-rate-limiter", "Explain the algorithm and implementation.", "Use a token bucket or sliding window algorithm. Store the state in a distributed cache (Redis) with atomic operations. Use consistent hashing to partition by client ID."],
  ["System Engineer", "How would you design a recommendation system?", "design-recommendation-system", "Outline the approach.", "Use collaborative filtering or content-based filtering. Offline batch processing (Spark) to compute recommendations, and online serving (Cassandra/Redis) to deliver them. A/B testing to iterate."],
  ["System Engineer", "How would you design a distributed file system?", "design-distributed-file-system", "Explain the architecture.", "Use a master-slave architecture where a master manages metadata and slaves store data (like HDFS). Data is divided into blocks and replicated for fault tolerance. Clients communicate with the master to locate blocks."],
  ["System Engineer", "How would you design a global leaderboard (like a game)?", "design-leaderboard", "Explain the approach.", "Use a sorted set in Redis (ZSET) for real-time ranking. For historical data, use a database with periodic snapshots. Use sharding for high write throughput."],
  ["System Engineer", "How would you design a system to handle millions of concurrent connections (like a chat server)?", "design-high-concurrency-connections", "Discuss architecture and patterns.", "Use non-blocking I/O (Netty, NIO) to handle many connections per thread. Use event-driven architecture with a message queue. Load balance connections using L4 load balancers (e.g., HAProxy). Use a service mesh for internal communication."],
  ["System Engineer", "How would you design a payment processing system?", "design-payment-system", "Outline the requirements.", "Requires high consistency, idempotency, and failure handling. Use a database with ACID transactions and a message queue for reliable processing. Implement a circuit breaker for external payment gateways. Handle idempotency keys to prevent duplicate charges."],
  ["System Engineer", "How would you design a real-time analytics dashboard?", "design-real-time-analytics", "Explain the data pipeline.", "Use a stream processing framework (e.g., Flink) to aggregate data from sources (Kafka). Store pre-aggregated results in a time-series database (e.g., InfluxDB) or a key-value store. Use a WebSocket to push updates to the frontend."],

  // ==================== GENERAL TRADE-OFFS & CASE STUDIES (Hard) ====================
  ["System Engineer", "How do you choose between a relational database and a NoSQL database for a new service?", "choose-db", "Provide a decision framework.", "Consider data model (structured vs unstructured), query patterns (complex joins vs simple key lookups), scalability needs (horizontal vs vertical), consistency requirements (ACID vs BASE), and team expertise."],
  ["System Engineer", "How do you decide between synchronous and asynchronous communication between services?", "sync-vs-async-communication-decision", "Give guidelines.", "Use sync for request-response patterns where immediate feedback is needed (e.g., API calls). Use async for event-driven architectures, long-running operations, and to decouple services. Consider latency, coupling, and fault tolerance."],
  ["System Engineer", "How do you ensure the security of a system at scale?", "security-at-scale", "Discuss strategies.", "Implement zero-trust architecture, use encryption (at rest and in transit), enforce least-privilege access, regularly audit and patch, use WAF/API gateways for threat protection, and implement DDoS mitigation."],
  ["System Engineer", "How do you approach capacity planning?", "capacity-planning", "Explain the process.", "Measure current usage and growth trends, predict future load, estimate resource requirements (CPU, memory, storage, network), and plan for scaling (auto-scaling, adding nodes). Consider peak loads and seasonality."],
  ["System Engineer", "How do you handle schema evolution in a distributed system?", "schema-evolution", "Discuss strategies.", "Use versioned APIs, support backward-compatible changes (e.g., optional fields, adding fields), use serialization frameworks (Protobuf, Avro) that support schema evolution, and migrate data gradually."],

  // ==================== ADVANCED / SPECIALIZED (Hard) ====================
  ["System Engineer", "What is the difference between a stateful and stateless application?", "stateful-vs-stateless", "Define and give examples.", "Stateless applications do not store any client-specific data between requests (e.g., REST API). Stateful applications maintain session state (e.g., user login). Stateless is easier to scale horizontally."],
  ["System Engineer", "What is a distributed tracing system like Dapper (Google) or Jaeger?", "distributed-tracing-examples", "Explain their principles.", "They trace a request across services using unique IDs (TraceID, SpanID). They propagate these IDs in headers. The collected spans form a trace tree, which is sent to a collector for analysis and visualization."],
  ["System Engineer", "What is a service registry and how does it work with health checks?", "service-registry", "Explain its role.", "A service registry (e.g., Consul, Eureka) maintains a list of available services and their endpoints. Services register themselves and send heartbeats. Health checks (e.g., HTTP endpoint, TCP) determine if a service is healthy and should be deregistered."],
  ["System Engineer", "What is the difference between a load balancer and a reverse proxy?", "load-balancer-vs-reverse-proxy", "Clarify the distinction.", "A load balancer distributes traffic across multiple backend servers. A reverse proxy can also distribute load but also provides caching, SSL termination, and security. The terms are often used interchangeably."],
  ["System Engineer", "What is a CDN and how does it improve performance?", "cdn-performance", "Explain how CDNs work.", "CDNs cache content at edge locations close to users. They reduce latency, offload origin servers, and handle traffic spikes. They also provide DDoS protection."],
  ["System Engineer", "What is a data lake and how is it different from a data warehouse?", "data-lake-vs-warehouse", "Compare the two.", "A data lake stores raw, unstructured data at scale (e.g., S3, HDFS). A data warehouse stores structured, processed data optimized for analysis (e.g., Redshift, BigQuery). Lakes are for storage, warehouses for analytics."],
  ["System Engineer", "What is the difference between a message queue and a stream processing platform?", "message-queue-vs-stream", "Compare the two.", "Message queues (e.g., RabbitMQ) are designed for decoupling and reliable delivery of individual messages. Stream processing platforms (e.g., Kafka) store ordered, replayable streams and support event time processing and aggregations."],
  ["System Engineer", "What is the role of a config server in microservices?", "config-server", "Explain its purpose.", "A config server provides externalized configuration to microservices. It centralizes configuration, supports versioning, and allows changes without redeploying services. Spring Cloud Config is a common implementation."],
  ["System Engineer", "How would you monitor the health of a microservices ecosystem?", "monitor-microservices", "Discuss tools and practices.", "Use a combination of logging (ELK), metrics (Prometheus, Grafana), and distributed tracing (Jaeger, Zipkin). Set up alerts based on SLIs. Use service mesh for observability."],
  ["System Engineer", "What is the difference between a circuit breaker and a bulkhead pattern?", "circuit-breaker-vs-bulkhead", "Explain the two resilience patterns.", "Circuit breaker prevents repeated failures by short-circuiting calls. Bulkhead isolates resources (e.g., thread pools) so that a failure in one part does not affect others."],
  ["System Engineer", "What is a retry budget and how is it used?", "retry-budget", "Explain the concept.", "A retry budget limits the number of retries a service can perform to avoid cascading failures. It is often used with circuit breakers to maintain system stability."],
  ["System Engineer", "What is the difference between active-active and active-passive failover?", "active-active-vs-active-passive", "Describe the two redundancy configurations.", "Active-active: all nodes are active and serve traffic, providing high availability and load sharing. Active-passive: one primary active, others on standby, only taking over on failure."],
  ["System Engineer", "What is a distributed consensus and why is it needed?", "distributed-consensus", "Explain its purpose.", "Distributed consensus allows a group of nodes to agree on a value even in the presence of failures. It is needed for maintaining consistency in replicated state machines."],
  ["System Engineer", "Explain the difference between ZooKeeper and etcd.", "zookeeper-vs-etcd", "Compare the coordination services.", "Both are distributed key-value stores. ZooKeeper is older, uses ZAB protocol, and has a more complex API. etcd is newer, uses Raft, and is simpler, used in Kubernetes for configuration."],
  ["System Engineer", "What is a durable queue and why is it important?", "durable-queue", "Define and explain.", "A durable queue persists messages to disk so that they are not lost if the broker restarts. It ensures at-least-once delivery and data safety."],
  ["System Engineer", "What is the difference between a synchronous and asynchronous database replication?", "sync-vs-async-db-replication", "Compare the replication modes.", "Synchronous replication: write is not acknowledged until all replicas have written. Ensures strong consistency but increases latency. Asynchronous replication: write is acknowledged after primary writes; replicas may lag, but offers lower latency."],
  ["System Engineer", "What is a dead letter queue (DLQ) and how is it used?", "dead-letter-queue", "Define and give use cases.", "A DLQ is a queue where messages that cannot be processed (e.g., due to errors) are sent for later analysis. It helps in debugging and preventing message loss."],
  ["System Engineer", "What is the difference between a gateway and a reverse proxy?", "gateway-vs-reverse-proxy", "Clarify the terms.", "A reverse proxy is a server that forwards client requests to backend servers. An API gateway is a type of reverse proxy that also provides additional features like authentication, rate limiting, request transformation, and service discovery."],
  ["System Engineer", "How do you handle versioning in a REST API?", "api-versioning", "Discuss strategies.", "Common approaches: URI versioning (e.g., `/v1/users`), header versioning (e.g., `Accept-Version: v1`), and query parameter versioning. URI versioning is most common and straightforward."],
  ["System Engineer", "What is the difference between a microservices and a modular monolith?", "microservices-vs-modular-monolith", "Compare the architectures.", "A modular monolith is a single deployable unit with well-defined modules and clear boundaries. Microservices are independently deployable services. Modular monoliths offer simpler deployment and communication, while microservices offer better isolation and independent scaling."],
  ["System Engineer", "What is a saga and how do you implement it?", "saga-implementation", "Explain the patterns.", "Saga is a pattern for distributed transactions. It can be implemented using choreography (events) or orchestration (central coordinator). Each step has a compensating action for rollback."],
  ["System Engineer", "What is a health check endpoint and why is it important in containerized environments?", "health-check-endpoint", "Explain its role.", "A health check endpoint (e.g., `/health`) allows orchestrators like Kubernetes to determine if a container is ready or alive. It is essential for rolling updates and auto-recovery."],
  ["System Engineer", "What is the difference between a stateless and stateful microservice?", "stateless-vs-stateful-microservice", "Define and give examples.", "Stateless microservices do not store any session data; any instance can handle any request. Stateful microservices maintain client-specific state (e.g., a session). Stateful services require sticky sessions or externalize state to a cache/database."],
  ["System Engineer", "How do you test a distributed system for reliability?", "test-distributed-system", "Discuss testing techniques.", "Use chaos engineering to inject failures, performance testing (load, stress), integration testing with fakes/mocks, and end-to-end testing. Also, test failure scenarios like network partitions and node crashes."],
  ["System Engineer", "What is the difference between a container and a virtual machine (VM)?", "container-vs-vm-deep", "Provide a detailed comparison.", "Containers share the host OS kernel, are lightweight, and start quickly. VMs each run a full OS, are heavier, and have stronger isolation. Containers are more portable and resource-efficient."],
  ["System Engineer", "What is a service level objective (SLO) and how do you set it?", "set-slo", "Explain the process.", "An SLO is a target for service performance (e.g., 99.9% availability). Set it based on user expectations, business requirements, and historical performance. Use error budgets to balance reliability and feature development."],
  ["System Engineer", "What is a blue-green deployment and how does it minimize risk?", "blue-green-deployment", "Explain the strategy.", "Blue-green deployment uses two identical environments. The new version is deployed to the idle environment, and traffic is switched after validation. This allows instant rollback and reduces downtime."],
  ["System Engineer", "What is a canary deployment and why would you use it?", "canary-deployment", "Explain the progressive rollout.", "Canary deployment rolls out a new version to a small subset of users first to test performance and detect issues before full rollout. It reduces risk and allows gradual migration."],
  ["System Engineer", "What is the difference between a feature flag and a release toggle?", "feature-flag-vs-release-toggle", "Clarify the terms.", "Feature flags are used to enable/disable features per user or group, often for A/B testing. Release toggles are used to control the rollout of a feature to all users, typically for gradual deployment."],
  ["System Engineer", "How do you handle database schema changes in a zero-downtime deployment?", "schema-migration-zero-downtime", "Discuss strategies.", "Use backward-compatible changes (e.g., adding columns, not removing them). Perform migrations in phases: add new columns, release code that uses them, then remove old columns. Use online schema change tools (e.g., gh-ost for MySQL)."],
  ["System Engineer", "What is a reverse proxy and when would you use it?", "reverse-proxy-use-cases", "Give examples.", "A reverse proxy is used for load balancing, caching, SSL termination, and security. It sits in front of web servers. Examples: Nginx, HAProxy."],
  ["System Engineer", "What is the difference between a stateful and stateless protocol?", "stateful-vs-stateless-protocol", "Explain in the context of networking.", "A stateless protocol (e.g., HTTP) does not require the server to retain session state; each request is independent. A stateful protocol (e.g., FTP) maintains session state."],
  ["System Engineer", "What is the role of an API gateway in security?", "api-gateway-security", "Explain security features.", "An API gateway can enforce authentication (OAuth2, JWT), rate limiting, IP whitelisting, CORS policies, and protect against DDoS attacks. It also serves as a central point for security logging."],
  ["System Engineer", "How do you design a system for idempotency?", "idempotency-design", "Explain idempotent operations.", "Idempotency ensures that performing an operation multiple times has the same effect as doing it once. Implement using idempotency keys (e.g., client-provided UUID) stored to prevent duplicate processing."],
  ["System Engineer", "What is the difference between a distributed lock and a semaphore in a distributed context?", "distributed-lock-vs-semaphore", "Explain their use.", "A distributed lock ensures exclusive access to a shared resource. A semaphore allows a limited number of concurrent accesses. Implementations use Redis, ZooKeeper, etc."],
  ["System Engineer", "What is a read-through cache?", "read-through-cache", "Define the caching pattern.", "In a read-through cache, the cache is treated as the primary data source. When a request is made, the cache first checks if the data exists; if not, it loads it from the database and stores it, then returns it."],
  ["System Engineer", "What is a write-through cache?", "write-through-cache", "Define the caching pattern.", "In a write-through cache, every write to the cache is also written to the database synchronously. This ensures strong consistency but increases write latency."],
  ["System Engineer", "What is a write-behind cache?", "write-behind-cache", "Define the caching pattern.", "In a write-behind (or write-back) cache, writes are only made to the cache, and a separate process asynchronously writes to the database. This reduces write latency but risks losing data if the cache fails before persistence."],
  ["System Engineer", "What is the difference between a cache-aside and a read-through pattern?", "cache-aside-vs-read-through", "Compare the two.", "Cache-aside: the application manages the cache (checks cache, if miss, queries DB and populates cache). Read-through: the cache itself is responsible for loading data from the DB when a miss occurs."],
  ["System Engineer", "What is a materialized view and how is it used?", "materialized-view", "Define and give use cases.", "A materialized view is a pre-computed result set stored physically, used for fast read queries. It is often used in data warehousing to speed up complex aggregations."]
] as const;



const prisma = new PrismaClient();

const buildWhyInterviewersAsk = (question: string, shortDescription: string) =>
  `Interviewers ask this to check whether you can explain System Engineer concepts clearly and connect them to practical engineering decisions. ${shortDescription} A strong response should address the purpose, the relevant trade-offs, and how you would verify the result rather than reciting a command or definition.`;

const buildCommonMistakes = (question: string) => [
  `Giving a memorized definition without explaining how it applies to: ${question}`,
  "Listing System Engineer commands without explaining the safety, performance, or operational trade-off.",
  "Ignoring security boundaries, persistence, failure handling, or how the solution would be tested.",
];

async function main() {
  const category = await prisma.category.upsert({
    where: { slug: "System Engineer" },
    update: { name: "System Engineer", group: "Technology", description: "System Engineer interview questions." },
    create: { name: "System Engineer", slug: "System Engineer", group: "Technology", description: "System Engineer interview questions." },
  });
  const subcategory = await prisma.subcategory.upsert({
    where: { categoryId_slug: { categoryId: category.id, slug: "System Engineer" } },
    update: {},
    create: { name: "System Engineer", slug: "System Engineer", categoryId: category.id },
  });

  for (let topicIndex = 0; topicIndex < topics.length; topicIndex += 1) {
    const [, question, slug, shortDescription, sampleAnswer] = topics[topicIndex];
    const commonMistakes = buildCommonMistakes(question);
    const followUpQuestions = [
      topics[(topicIndex + 1) % topics.length][1],
      topics[(topicIndex + 2) % topics.length][1],
      topics[(topicIndex + 3) % topics.length][1],
    ];
    await prisma.interviewQuestion.upsert({
      where: { slug },
      update: {
        question,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["System Engineer"],
        isPublished: true,
      },
      create: {
        question,
        slug,
        categoryId: category.id,
        subcategoryId: subcategory.id,
        experienceLevel: ExperienceLevel.MID_LEVEL,
        difficulty: Difficulty.MEDIUM,
        interviewType: InterviewType.TECHNICAL,
        shortDescription,
        explanation: buildWhyInterviewersAsk(question, shortDescription),
        sampleAnswer,
        detailedAnswer: sampleAnswer,
        keyPoints: [],
        commonMistakes,
        followUpQuestions,
        tags: ["System Engineer"],
        isPublished: true,
      },
    });
  }

  console.log(`Imported ${topics.length} System Engineer questions.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());

export const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");