import { z } from "zod";
import { requireAdminApi } from "@/lib/admin";
import { prisma } from "@/lib/prisma";

const idSchema = z.object({ id: z.string().min(1).max(100) });
const questionSchema = z.object({ question: z.string().trim().min(10).max(500), slug: z.string().regex(/^[a-z0-9-]+$/).max(180), categoryId: z.string().min(1), shortDescription: z.string().trim().min(10).max(500), explanation: z.string().trim().min(10).max(5000), sampleAnswer: z.string().trim().min(10).max(5000), experienceLevel: z.enum(["FRESHER", "INTERNSHIP", "MID_LEVEL", "EXPERIENCED"]), difficulty: z.enum(["EASY", "MEDIUM", "HARD"]), interviewType: z.enum(["TECHNICAL", "BEHAVIORAL", "HR", "CASE_STUDY", "SITUATIONAL"]), isPublished: z.boolean().default(false) });
const articleSchema = z.object({ title: z.string().trim().min(10).max(200), slug: z.string().regex(/^[a-z0-9-]+$/).max(180), excerpt: z.string().trim().min(20).max(500), content: z.string().trim().min(100).max(50000), author: z.string().trim().max(120).optional(), categoryId: z.string().min(1).optional(), isPublished: z.boolean().default(false) });
const categorySchema = z.object({ name: z.string().trim().min(2).max(100), slug: z.string().regex(/^[a-z0-9-]+$/).max(120), group: z.string().trim().min(2).max(80), description: z.string().trim().max(500).optional(), sortOrder: z.number().int().min(0).max(10000).default(0) });
const faqSchema = z.object({ question: z.string().trim().min(10).max(300), answer: z.string().trim().min(10).max(5000), sortOrder: z.number().int().min(0).max(10000).default(0), isPublished: z.boolean().default(true) });
export async function POST(request: Request, context: { params: Promise<{ resource: string }> }) { const guard = await requireAdminApi(); if (guard.response) return guard.response; const resource = (await context.params).resource; const body: unknown = await request.json(); try { if (resource === "questions") { const data = questionSchema.parse(body); return Response.json(await prisma.interviewQuestion.create({ data: { ...data, keyPoints: [], commonMistakes: [], followUpQuestions: [], tags: [] } }), { status: 201 }); } if (resource === "articles") { const data = articleSchema.parse(body); return Response.json(await prisma.article.create({ data: { ...data, publishedAt: data.isPublished ? new Date() : null } }), { status: 201 }); } if (resource === "categories") return Response.json(await prisma.category.create({ data: categorySchema.parse(body) }), { status: 201 }); if (resource === "faqs") return Response.json(await prisma.fAQ.create({ data: faqSchema.parse(body) }), { status: 201 }); return Response.json({ error: "Unsupported admin resource." }, { status: 404 }); } catch (error) { if (error instanceof z.ZodError) return Response.json({ error: "Invalid input.", details: error.flatten() }, { status: 400 }); return Response.json({ error: "Could not create this record." }, { status: 409 }); } }
export async function PATCH(request: Request, context: { params: Promise<{ resource: string }> }) { const guard = await requireAdminApi(); if (guard.response) return guard.response; const resource = (await context.params).resource; const body = await request.json(); const parsed = idSchema.safeParse(body); if (!parsed.success) return Response.json({ error: "Invalid record ID." }, { status: 400 }); const data = body as Record<string, unknown>; try { if (resource === "users" && typeof data.isDisabled === "boolean") return Response.json(await prisma.user.update({ where: { id: parsed.data.id }, data: { isDisabled: data.isDisabled }, select: { id: true, isDisabled: true } })); if (resource === "questions" && typeof data.isPublished === "boolean") return Response.json(await prisma.interviewQuestion.update({ where: { id: parsed.data.id }, data: { isPublished: data.isPublished }, select: { id: true, isPublished: true } })); if (resource === "articles" && typeof data.isPublished === "boolean") return Response.json(await prisma.article.update({ where: { id: parsed.data.id }, data: { isPublished: data.isPublished, publishedAt: data.isPublished ? new Date() : null }, select: { id: true, isPublished: true } })); if (resource === "contacts" && typeof data.isRead === "boolean") return Response.json(await prisma.contactMessage.update({ where: { id: parsed.data.id }, data: { isRead: data.isRead }, select: { id: true, isRead: true } })); return Response.json({ error: "Unsupported admin update." }, { status: 400 }); } catch { return Response.json({ error: "Record not found or update failed." }, { status: 404 }); } }
export async function DELETE(request: Request, context: { params: Promise<{ resource: string }> }) { const guard = await requireAdminApi(); if (guard.response) return guard.response; const resource = (await context.params).resource; const parsed = idSchema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Invalid record ID." }, { status: 400 }); const id = parsed.data.id; try { if (resource === "questions") await prisma.interviewQuestion.delete({ where: { id } }); else if (resource === "articles") await prisma.article.delete({ where: { id } }); else if (resource === "categories") await prisma.category.delete({ where: { id } }); else if (resource === "faqs") await prisma.fAQ.delete({ where: { id } }); else if (resource === "contacts") await prisma.contactMessage.delete({ where: { id } }); else return Response.json({ error: "Unsupported admin delete." }, { status: 400 }); return Response.json({ deleted: true }); } catch { return Response.json({ error: "Record not found or delete failed." }, { status: 404 }); } }
