import { Difficulty, ExperienceLevel, InterviewType, Prisma } from "@prisma/client";
import ExcelJS from "exceljs";
import { prisma } from "@/lib/prisma";
import { findPotentialDuplicate } from "@/lib/question-similarity";

export const IMPORT_HEADERS = ["question", "slug", "category", "subcategory", "experienceLevel", "difficulty", "interviewType", "shortDescription", "explanation", "sampleAnswer", "keyPoints", "commonMistakes", "followUpQuestions", "tags", "seoTitle", "seoDescription", "isPublished"] as const;
export const MAX_IMPORT_BYTES = 5 * 1024 * 1024;
export const MAX_IMPORT_ROWS = 2000;
type RawRow = Record<string, string>;
export type ImportRow = RawRow & { rowNumber: string };
const strip = (value: string) => value.replace(/<[^>]*>/g, "").replace(/[\u0000-\u001f\u007f]/g, "").trim();
const csvRows = (text: string) => { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let index = 0; index < text.length; index++) { const char = text[index]; if (char === '"') { if (quoted && text[index + 1] === '"') { cell += '"'; index++; } else quoted = !quoted; } else if (char === "," && !quoted) { row.push(cell); cell = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[index + 1] === "\n") index++; row.push(cell); rows.push(row); row = []; cell = ""; } else cell += char; } if (cell || row.length) { row.push(cell); rows.push(row); } return rows.filter(item => item.some(value => value.trim())); };
export async function parseImportFile(file: File) { if (file.size > MAX_IMPORT_BYTES) throw new Error("File exceeds the 5 MB limit."); const name = file.name.toLowerCase(); if (!name.endsWith(".csv") && !name.endsWith(".xlsx")) throw new Error("Only CSV and XLSX files are supported."); const buffer = await file.arrayBuffer(); let rows: string[][]; if (name.endsWith(".csv")) rows = csvRows(new TextDecoder().decode(buffer)); else { const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(buffer); const sheet = workbook.worksheets[0]; if (!sheet) throw new Error("Workbook contains no worksheet."); rows = []; sheet.eachRow({ includeEmpty: false }, row => { rows.push((row.values as unknown[]).slice(1).map(value => String(value ?? ""))); }); } if (rows.length < 2 || rows.length > MAX_IMPORT_ROWS + 1) throw new Error(`File must contain 1-${MAX_IMPORT_ROWS} data rows.`); const headers = rows[0].map(value => String(value).trim()); const missing = IMPORT_HEADERS.filter(header => !headers.includes(header)); if (missing.length) throw new Error(`Missing columns: ${missing.join(", ")}`); return rows.slice(1).map((values, index) => Object.fromEntries(IMPORT_HEADERS.map(header => [header, strip(String(values[headers.indexOf(header)] ?? ""))])) as ImportRow).map((row, index) => ({ ...row, rowNumber: String(index + 2) })); }
const parseList = (value: string) => { if (!value) return []; try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.map(item => strip(String(item))).filter(Boolean) : value.split("|").map(strip).filter(Boolean); } catch { return value.split("|").map(strip).filter(Boolean); } };
const enumValue = <T extends string>(value: string, values: T[]) => values.includes(value as T) ? value as T : undefined;
export async function validateImportRows(rows: ImportRow[]) { const [categories, existing] = await Promise.all([prisma.category.findMany({ include: { subcategories: true } }), prisma.interviewQuestion.findMany({ select: { slug: true, question: true } })]); const categoryMap = new Map(categories.map(item => [item.name.toLowerCase(), item])); const existingSlugs = new Set(existing.map(item => item.slug)); const seenSlugs = new Set<string>(); const seenQuestions = new Set<string>(); return rows.map(row => { const errors: string[] = []; const warnings: string[] = []; if (!row.question || row.question.length < 10) errors.push("Missing question or question is too short"); if (row.question.length > 500) errors.push("Question exceeds 500 characters"); const category = categoryMap.get(row.category.toLowerCase()); if (!category) errors.push("Invalid or missing category"); const subcategory = category?.subcategories.find(item => item.name.toLowerCase() === row.subcategory.toLowerCase()); if (row.subcategory && !subcategory) errors.push("Invalid subcategory"); if (!enumValue(row.experienceLevel, Object.values(ExperienceLevel))) errors.push("Invalid experience level"); if (!enumValue(row.difficulty, Object.values(Difficulty))) errors.push("Invalid difficulty"); if (!enumValue(row.interviewType, Object.values(InterviewType))) errors.push("Invalid interview type"); if (!/^[a-z0-9-]{1,180}$/.test(row.slug)) errors.push("Invalid slug"); if (seenSlugs.has(row.slug) || existingSlugs.has(row.slug)) warnings.push("Duplicate slug"); if (seenQuestions.has(row.question.toLowerCase()) || existing.some(item => item.question.toLowerCase() === row.question.toLowerCase())) warnings.push("Duplicate question"); seenSlugs.add(row.slug); seenQuestions.add(row.question.toLowerCase()); for (const field of ["shortDescription", "explanation", "sampleAnswer"]) if (!row[field]) errors.push(`Missing ${field}`); if (row.seoTitle.length > 70) errors.push("SEO title exceeds 70 characters"); if (row.seoDescription.length > 160) errors.push("SEO description exceeds 160 characters"); return { row, errors, warnings, categoryId: category?.id, subcategoryId: subcategory?.id }; }); }
export function toQuestionData(item: Awaited<ReturnType<typeof validateImportRows>>[number]) { const row = item.row; return { question: row.question, slug: row.slug, categoryId: item.categoryId!, subcategoryId: item.subcategoryId, experienceLevel: row.experienceLevel as ExperienceLevel, difficulty: row.difficulty as Difficulty, interviewType: row.interviewType as InterviewType, shortDescription: row.shortDescription, explanation: row.explanation, sampleAnswer: row.sampleAnswer, keyPoints: parseList(row.keyPoints), commonMistakes: parseList(row.commonMistakes), followUpQuestions: parseList(row.followUpQuestions), tags: parseList(row.tags), seoTitle: row.seoTitle || null, seoDescription: row.seoDescription || null, isPublished: row.isPublished.toLowerCase() === "true" }; }
export type ImportQuestionData = ReturnType<typeof toQuestionData>;
export async function commitImport(items: ImportQuestionData[], mode: "skip" | "update" | "new") { let imported = 0; let updated = 0; let skipped = 0; for (let start = 0; start < items.length; start += 100) { const batch = items.slice(start, start + 100); const existingResult = await prisma.interviewQuestion.findMany({ select: { id: true, question: true, slug: true } }); const existingQuestions = Array.isArray(existingResult) ? existingResult : []; await prisma.$transaction(async transaction => { const accepted = [...existingQuestions]; for (const data of batch) { const existing = await transaction.interviewQuestion.findUnique({ where: { slug: data.slug }, select: { id: true } }); if (existing && mode !== "update") { skipped++; continue; } const duplicate = findPotentialDuplicate(data.question, accepted).find(({ item }) => item.slug !== data.slug); if (duplicate) throw new Error(`Duplicate question rejected: ${data.question} is highly similar to ${duplicate.item.question} (${duplicate.item.slug}).`); if (existing && mode === "update") { await transaction.interviewQuestion.update({ where: { id: existing.id }, data }); updated++; } else { const created = await transaction.interviewQuestion.create({ data, select: { id: true, question: true, slug: true } }); if (created && typeof created.question === "string") accepted.push(created); imported++; } } }); } return { imported, updated, skipped, processed: items.length }; }
