import { getServerSession } from "next-auth";
import { z } from "zod";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { rateLimit, requestSizeLimit, tooManyRequests } from "@/lib/request-security";
const schema = z.object({ questionId: z.string().min(1).max(100) });
async function guard(request: Request) { const limiter = rateLimit(request, "saved-question", 60, 15 * 60 * 1000); if (!limiter.allowed) return { session: null, response: tooManyRequests(limiter.retryAfter) }; if (!requestSizeLimit(request)) return { session: null, response: Response.json({ error: "Request is too large." }, { status: 413 }) }; const session = await getServerSession(authOptions); if (!session?.user?.id) return { session: null, response: Response.json({ error: "Authentication required." }, { status: 401 }) }; return { session, response: null }; }
export async function POST(request: Request) { const access = await guard(request); if (access.response) return access.response; const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Invalid question." }, { status: 400 }); const question = await prisma.interviewQuestion.findFirst({ where: { id: parsed.data.questionId, isPublished: true }, select: { id: true } }); if (!question) return Response.json({ error: "Question not found." }, { status: 404 }); await prisma.savedQuestion.upsert({ where: { userId_questionId: { userId: access.session!.user.id, questionId: question.id } }, create: { userId: access.session!.user.id, questionId: question.id }, update: {} }); return Response.json({ saved: true }); }
export async function DELETE(request: Request) { const access = await guard(request); if (access.response) return access.response; const parsed = schema.safeParse(await request.json()); if (!parsed.success) return Response.json({ error: "Invalid question." }, { status: 400 }); await prisma.savedQuestion.deleteMany({ where: { userId: access.session!.user.id, questionId: parsed.data.questionId } }); return Response.json({ saved: false }); }
