"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, Lightbulb, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { PracticeQuestion } from "@/lib/practice";
import { simpleScore } from "@/lib/practice";

type Props = { questions: PracticeQuestion[] };
type Draft = { answers: Record<string, string>; skipped: Record<string, boolean>; startedAt: string };
const storageKey = "interviewprep-practice-draft";
export function PracticeSession({ questions }: Props) {
  const [draft, setDraft] = useState<Draft>({ answers: {}, skipped: {}, startedAt: new Date().toISOString() });
  const [current, setCurrent] = useState(0); const [showExplanation, setShowExplanation] = useState(false); const [finished, setFinished] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const stored = window.localStorage.getItem(storageKey); if (stored) { try { setDraft(JSON.parse(stored) as Draft); } catch { window.localStorage.removeItem(storageKey); } } }, []);
  useEffect(() => { window.localStorage.setItem(storageKey, JSON.stringify(draft)); }, [draft]);
  const question = questions[current]; const answer = draft.answers[question.id] ?? ""; const answered = questions.filter(item => (draft.answers[item.id] ?? "").trim()).length; const skipped = questions.filter(item => draft.skipped[item.id]).length;
  const updateAnswer = (value: string) => setDraft(previous => ({ ...previous, answers: { ...previous.answers, [question.id]: value }, skipped: { ...previous.skipped, [question.id]: false } }));
  const toggleSkip = () => setDraft(previous => ({ ...previous, skipped: { ...previous.skipped, [question.id]: !previous.skipped[question.id] } }));
  async function finish() { const completedAt = new Date().toISOString(); const results = questions.map(item => ({ questionId: item.id, answer: draft.answers[item.id] ?? "", skipped: Boolean(draft.skipped[item.id]), score: draft.answers[item.id]?.trim() ? simpleScore(draft.answers[item.id], item.keyPoints) : null })); const scored = results.filter(item => item.score !== null); const score = scored.length ? Math.round(scored.reduce((sum, item) => sum + (item.score ?? 0), 0) / scored.length) : null; try { const response = await fetch("/api/practice/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ responses: results, score, startedAt: draft.startedAt, completedAt }) }); if (!response.ok) throw new Error("save"); setSaved(true); } catch { setError("Your result is available, but we could not save it. You can still review it below."); } setFinished(true); window.localStorage.removeItem(storageKey); }
  if (finished) { const completion = Math.round((answered / questions.length) * 100); const resultScores = questions.map(item => draft.answers[item.id]?.trim() ? simpleScore(draft.answers[item.id], item.keyPoints) : null).filter((value): value is number => value !== null); const score = resultScores.length ? Math.round(resultScores.reduce((sum, value) => sum + value, 0) / resultScores.length) : null; return <div className="mx-auto max-w-4xl"><div className="rounded-3xl bg-ink p-8 text-paper sm:p-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-coral">Session complete</p><h1 className="mt-4 font-display text-4xl font-bold">A useful first pass.</h1><p className="mt-3 max-w-xl leading-7 text-paper/65">Review what you answered, then return to the questions where you want more clarity.</p><div className="mt-10 grid gap-4 sm:grid-cols-3">{[["Answered", answered], ["Skipped", skipped], ["Completion", `${completion}%`]].map(([label, value]) => <div className="rounded-2xl bg-paper/10 p-4" key={label as string}><p className="text-sm text-paper/60">{label as string}</p><p className="mt-2 font-display text-3xl font-bold">{value}</p></div>)}</div></div><div className="mt-6 rounded-2xl border border-ink/10 bg-white/70 p-6"><h2 className="font-display text-2xl font-bold">Practice score</h2><p className="mt-3 text-ink/60">{score === null ? "No answer was scored." : `${score}% based on a simple answer-length and key-point check.`}</p><p className="mt-2 text-sm text-ink/50">This is a lightweight self-check, not a scientifically accurate evaluation.</p>{error && <p role="alert" className="mt-4 text-sm font-semibold text-coral">{error}</p>}<div className="mt-6 flex flex-wrap gap-3"><Button href="/interview-questions">Explore more questions</Button><Button onClick={() => window.location.reload()} variant="outline">Practice again <RotateCcw size={16} /></Button></div>{saved && <p className="mt-4 text-sm font-semibold text-ink/55">Saved to your dashboard.</p>}</div></div>; }
  return <div className="mx-auto max-w-4xl"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-coral">Practice session</p><p className="mt-2 text-sm font-semibold text-ink/55">Question {current + 1} of {questions.length}</p></div><p className="text-sm font-bold text-ink/55">{Math.round(((current + 1) / questions.length) * 100)}%</p></div><div className="mt-4 h-2 rounded-full bg-mint"><div className="h-full rounded-full bg-coral transition-all" style={{ width: `${((current + 1) / questions.length) * 100}%` }} /></div><div className="mt-10 rounded-3xl border border-ink/10 bg-white/70 p-6 sm:p-10"><div className="flex flex-wrap gap-2 text-xs font-bold text-ink/55"><span className="rounded-full bg-mint px-3 py-1">{question.category.name}</span><span className="rounded-full bg-ink/5 px-3 py-1">{question.category.slug}</span></div><h1 className="mt-7 font-display text-3xl font-bold leading-tight sm:text-4xl">{question.question}</h1><button type="button" onClick={() => setShowExplanation(!showExplanation)} className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-coral"> <Lightbulb size={17} /> {showExplanation ? "Hide guidance" : "Show guidance"}</button>{showExplanation && <div className="mt-4 rounded-2xl bg-mint/60 p-5 text-sm leading-7 text-ink/70">{question.explanation}<p className="mt-3 font-bold">Think about: {question.keyPoints.join("; ")}</p></div>}<label className="mt-8 block text-sm font-bold" htmlFor="answer">Your answer<textarea id="answer" value={answer} onChange={event => updateAnswer(event.target.value)} placeholder="Write your answer in your own words..." className="mt-2 min-h-44 w-full resize-y rounded-2xl border border-ink/15 bg-paper p-4 font-normal leading-7" /></label><p className="mt-3 text-xs text-ink/50">Your answer is kept in this browser while you practice.</p><div className="mt-8 flex flex-wrap justify-between gap-3"><Button type="button" variant="outline" onClick={() => setCurrent(Math.max(0, current - 1))} className={current === 0 ? "invisible" : ""}><ArrowLeft size={16} /> Previous</Button><button type="button" onClick={toggleSkip} className={`rounded-full border px-5 py-2 text-sm font-bold ${draft.skipped[question.id] ? "border-coral text-coral" : "border-ink/15 text-ink/65"}`}>{draft.skipped[question.id] ? "Unskip" : "Skip"}</button>{current === questions.length - 1 ? <Button type="button" onClick={finish}>Finish <Check size={16} /></Button> : <Button type="button" onClick={() => { setShowExplanation(false); setCurrent(current + 1); }}>Next <ArrowRight size={16} /></Button>}</div></div></div>;
}
