import { z } from "zod";

export const generatedQuestionSchema = z.object({ question: z.string().trim().min(10).max(500), shortDescription: z.string().trim().min(10).max(500), explanation: z.string().trim().min(10).max(5000), sampleAnswer: z.string().trim().min(10).max(5000), keyPoints: z.array(z.string().trim().min(1).max(300)).min(1).max(12), commonMistakes: z.array(z.string().trim().min(1).max(300)).min(1).max(12), followUpQuestions: z.array(z.string().trim().min(1).max(300)).min(1).max(12), tags: z.array(z.string().trim().min(1).max(80)).max(12), seoTitle: z.string().trim().max(70), seoDescription: z.string().trim().max(160) });
export const generatedQuestionsSchema = z.array(generatedQuestionSchema).min(1).max(50);
export type GeneratedQuestion = z.infer<typeof generatedQuestionSchema>;
export type GenerationInput = { category: string; subcategory?: string; experienceLevel: string; difficulty: string; interviewType: string; topic: string; count: number; instructions?: string };
export interface QuestionGenerationService { generate(input: GenerationInput): Promise<GeneratedQuestion[]>; }
export class OpenAiCompatibleQuestionService implements QuestionGenerationService { async generate(input: GenerationInput) { if (process.env.AI_ENABLED !== "true" || !process.env.AI_API_KEY) throw new Error("AI generation is disabled or not configured."); const response = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${process.env.AI_API_KEY}` }, body: JSON.stringify({ model: process.env.AI_MODEL || "gpt-4o-mini", temperature: 0.4, response_format: { type: "json_object" }, messages: [{ role: "system", content: "Return only JSON with a questions array. Create original interview preparation drafts. Every question must test a meaningfully different concept, scenario, debugging problem, implementation, trade-off, or edge case. Never create wording-only variations, append generic context such as scalability or global teams, or repeat a question from another draft. Do not make employment guarantees, copy sources, or include HTML." }, { role: "user", content: JSON.stringify(input) }] }), signal: AbortSignal.timeout(30000) }); if (!response.ok) throw new Error("AI provider request failed."); const payload = await response.json() as { choices?: [{ message?: { content?: string } }] }; const content = payload.choices?.[0]?.message?.content; if (!content) throw new Error("AI provider returned no content."); const parsed: unknown = JSON.parse(content); const questions = parsed && typeof parsed === "object" && "questions" in parsed ? (parsed as { questions: unknown }).questions : parsed; return generatedQuestionsSchema.parse(questions); } }
export const questionGenerationService: QuestionGenerationService = new OpenAiCompatibleQuestionService();
